### ISSUE TITLE
Render settings not passed to the render delegate via husk

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#1006]
When setting AA_samples, or the adaptive sampling settings (AA_samples_max, AA_adaptive_threshold, enable_adaptive_sampling) on the render settings LOP, these are passed to the render delegate in Solaris.  However these aren't used by the delegate when rendering in husk.

**Comment by chrisbrejon** [comment]
Hello guys,

before I forget and to avoid any ambiguity, I just would like to add this information that was shared on slack :
_In the delegate only works via display options and as you can see the name of the parameter is different. If you select a specific render settings primitive to drive the delegate then adaptive sampling properties are ignored._

With an attached screenshot. Thanks 
![image](https://user-images.githubusercontent.com/70026961/164295525-55a2b7b0-822f-4cca-9503-461d345519b0.png)
!
