### ISSUE TITLE
Crash resizing viewport in Solaris

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#101]
I got a instant crash when I resized the viewport with Arnold. It was not rendering when I did the resize.

error in terminal:
00:11:49 81425MB ERROR   |                   signal caught: SIGSEGV -- Invalid memory reference

****
* Arnold 6.0.1.0 [aee812b8] linux clang-5.0.0 oiio-2.1.4 osl-1.11.0 vdb-4.0.0 clm-1.1.1.118 rlm-12.4.2 optix-6.5.0 2019/12/02 11:48:29
* CRASHED in libai.so (0x00007f50d0140945) at 00:00:00, pixel (297, 352)
* signal caught: SIGSEGV -- Invalid memory reference (address not mapped to object)
*
* backtrace:
*  0 0x00007f50d030cbd2 [libai.so       ]       
*  1 0x00007f51412115df [libpthread.so.0]       
>> 2 0x00007f50d0140945 [libai.so       ]       
*  3 0x00007f50d0140945 [libai.so       ]       
*  4 0x00007f50d02434a9 [libai.so       ]       
*  5 0x00007f50d023e4f0 [libai.so       ]       
*  6 0x00007f50d0310d4d [libai.so       ]       
*  7 0x00007f5141209e24 [libpthread.so.0]       
*  8 0x00007f5133f2234c [libc.so.6      ] clone 
*
* loaded modules:
*    0x00007f50cf90b000  libai.so
*    0x00007f5141202000  libpthread.so.0
*    0x00007f5133e2a000  libc.so.6
*
* memory: VM 265956 MB, RSS 81438 MB, 798 page faults
****
26787 ThreadId=0x7f5077fff700: Fatal error: Segmentation fault
26787: Fatal error: Segmentation fault (sent by pid 26787)
Saving application data to /tmp/houdini_temp/crash.untitled.flord_26787.hip
Crash log saved to /tmp/houdini_temp/crash.untitled.flord_26787_log.txt

crash log file:
Crash report from flord; Houdini Core Version 18.0.287 [linux-x86_64-gcc6.3]
Uptime 743 seconds
Wed Dec  4 09:24:34 2019
Caught signal 11

Traceback from 26787 ThreadId=0x7f5077fff700
AP_Interface::si_CrashHandler::handledSignal(UTsignalHandlerArg) <libHoudiniUI.so>
signalCallback(UTsignalHandlerArg) <libHoudiniUT.so>
UT_Signal::UT_ComboSignalHandler::operator()(int, siginfo_t*, void*) const <libHoudiniUT.so>
UT_Signal::processSignal(int, siginfo_t*, void*) <libHoudiniUT.so>
_L_unlock_13 <libpthread.so.0>
AiShaderGlobalsEdgeLength <libai.so>
AiShaderGlobalsEdgeLength <libai.so>
AiShaderGlobalsEdgeLength <libai.so>
AiShaderGlobalsEdgeLength <libai.so>
AiPromptADPDialog <libai.so>
start_thread <libpthread.so.0>
__clone <libc.so.6>

Traceback from 26787 ThreadId=0x7f512dfecd40
AP_Interface::coreDumpChaser(UTsignalHandlerArg) <libHoudiniUI.so>
AP_Interface::si_CrashHandler::chaser(UTsignalHandlerArg) <libHoudiniUI.so>
signalCallback(UTsignalHandlerArg) <libHoudiniUT.so>
UT_Signal::UT_ComboSignalHandler::operator()(int, siginfo_t*, void*) const <libHoudiniUT.so>
UT_Signal::processSignal(int, siginfo_t*, void*) <libHoudiniUT.so>
_L_unlock_13 <libpthread.so.0>
__writev <libc.so.6>
xcb_connect_to_fd <libxcb.so.1>
xcb_get_maximum_request_length <libxcb.so.1>
xcb_writev <libxcb.so.1>
_XSend <libX11.so.6>
_XReply <libX11.so.6>
glXCreateNewContext <libGLX_nvidia.so.0>

I get the following stack trace when I have a render settings node in the stage, I also don't have any Arnold settings in the render settings node

00:00:00  1514MB ERROR   | signal caught: SIGSEGV -- Invalid memory reference

****
* Arnold 6.0.1.0 [aee812b8] linux clang-5.0.0 oiio-2.1.4 osl-1.11.0 vdb-4.0.0 clm-1.1.1.118 rlm-12.4.2 optix-6.5.0 2019/12/02 11:48:29
00:00:00  1514MB WARNING | Aborted by user:  received abort signal
* CRASHED in pxrInternal_v0_19__pxrReserved__::HdArnoldRenderBuffer::Blit at 00:00:00
* signal caught: SIGSEGV -- Invalid memory reference (address not mapped to object)
*
* backtrace:
*  0 0x00007f558dd2dbd2 [libai.so              ] AiPromptADPDialog
*  1 0x00007f560620f5cf [libpthread.so.0       ] _L_unlock_13   
>> 2 0x00007f54f6dcf388 [hdArnold.so           ] pxrInternal_v0_19__pxrReserved__::HdArnoldRenderBuffer::Blit(pxrInternal_v0_19__pxrReserved__::HdFormat, int, int, int, int, unsigned char const*)                                           
*  3 0x00007f54f6dcf388 [hdArnold.so           ] pxrInternal_v0_19__pxrReserved__::HdArnoldRenderBuffer::Blit(pxrInternal_v0_19__pxrReserved__::HdFormat, int, int, int, int, unsigned char const*)                                             
*  4 0x00007f55fbb4e62c [libpxr_hdx.so         ] pxrInternal_v0_19__pxrReserved__::HdxRenderTask::Execute(std::unordered_map<pxrInternal_v0_19__pxrReserved__::TfToken, pxrInternal_v0_19__pxrReserved__::VtValue, pxrInternal_v0_19__pxrReserved__::TfToken::HashFunctor, std::equal_to<pxrInternal_v0_19__pxrReserved__::TfToken>, std::allocator<std::pair<pxrInternal_v0_19__pxrReserved__::TfToken const, pxrInternal_v0_19__pxrReserved__::VtValue> > >*) 
*  5 0x00007f55fc2d18b2 [libpxr_hd.so          ] pxrInternal_v0_19__pxrReserved__::HdEngine::Execute(pxrInternal_v0_19__pxrReserved__::HdRenderIndex*, std::vector<hboost::shared_ptr<pxrInternal_v0_19__pxrReserved__::HdTask>, std::allocator<hboost::shared_ptr<pxrInternal_v0_19__pxrReserved__::HdTask> > >*)            
*  6 0x00007f56029feba6 [libpxr_usdImagingGL.so] pxrInternal_v0_19__pxrReserved__::UsdImagingGLEngine::_Execute(pxrInternal_v0_19__pxrReserved__::UsdImagingGLRenderParams const&, std::vector<hboost::shared_ptr<pxrInternal_v0_19__pxrReserved__::HdTask>, std::allocator<hboost::shared_ptr<pxrInternal_v0_19__pxrReserved__::HdTask> > >)  
*  7 0x00007f5622cf4be1 [libHoudiniUSD.so      ] HUSD_Imaging::finishRender(bool)   
*  8 0x00007f5622cf4e70 [libHoudiniUSD.so      ] HUSD_Imaging::checkRender(bool) 
*  9 0x00007f5631e2de4a [libHoudiniAPPS3.so    ] jedi_UsdNonNative::beautyRender(RE_Render*, GUI_DisplayOption&, GR_ShadingPass, GR_AlphaPass, GR_RenderMode, GR_RenderFlags)  
* 10 0x00007f5631b79455 [libHoudiniAPPS3.so    ] DM_VPortAgent::renderSingleGeo(RE_Render*, GUI_GeoRender*, GR_RenderMode, GR_ShadingPass, GR_AlphaPass, bool, bool)   
* 11 0x00007f5631b88f03 [libHoudiniAPPS3.so    ] DM_VPortAgent::renderGeometry(RE_Render*, GR_RenderMode, GR_ShadingPass, GR_AlphaPass, OP_Bundle*, DM_GeoSortMode)                        
* 12 0x00007f5631b8a69d [libHoudiniAPPS3.so    ] DM_VPortAgent::normalQualityRender(RE_Render*, GUI_DisplayOption*, GR_AlphaPass, DM_GeoSortMode, UT_Array<GUI_DetailLook*> const*)        
* 13 0x00007f5631b8bfbf [libHoudiniAPPS3.so    ] DM_VPortAgent::renderBeautyPass(RE_Render*, int, int, GUI_DisplayOption*, bool&) 
* 14 0x00007f5631b8c4f8 [libHoudiniAPPS3.so    ] DM_VPortAgent::renderSceneView(RE_Render*, int, int) 
* 15 0x00007f5631b91ce0 [libHoudiniAPPS3.so    ] DM_VPortAgent::renderViewport(RE_Render*, int, int)
* 16 0x00007f5631b99bc1 [libHoudiniAPPS3.so    ] DM_VPortAgent::doRender(RE_Render*, int, int) 
* 17 0x00007f5631b54d03 [libHoudiniAPPS3.so    ] DM_Viewport::doRender(RE_Render*, int, int)        
* 18 0x00007f562f97c435 [libHoudiniUI.so       ] UI_Feel::renderMe(RE_Render*, int, int)          
* 19 0x00007f562f97cfa9 [libHoudiniUI.so       ] UI_Feel::doRenderKids(RE_Render*, int, int)     
* 20 0x00007f562f975dd3 [libHoudiniUI.so       ] UI_Feel::doRender(RE_Render*, int, int)      
* 21 0x00007f562f97c435 [libHoudiniUI.so       ] UI_Feel::renderMe(RE_Render*, int, int)
* 22 0x00007f562f97cfa9 [libHoudiniUI.so       ] UI_Feel::doRenderKids(RE_Render*, int, int) 
* 23 0x00007f562f975dd3 [libHoudiniUI.so       ] UI_Feel::doRender(RE_Render*, int, int) 
* 24 0x00007f562fadb42b [libHoudiniUI.so       ] UI_Viewport::reRender(RE_Render*, bool)  
* 25 0x00007f562fae29e8 [libHoudiniUI.so       ] UI_Window::renderChildViews(RE_Render*) 
* 26 0x00007f562fae313b [libHoudiniUI.so       ] UI_Window::doRedrawSubclass() 
* 27 0x00007f5631b3f871 [libHoudiniAPPS3.so    ]   
* 28 0x00007f562fade504 [libHoudiniUI.so       ] UI_Window::doRedraw()         
* 29 0x00007f562fa57ae0 [libHoudiniUI.so       ] UI_Queue::doWindowRedraws()    
* 30 0x00007f562fa57e72 [libHoudiniUI.so       ] UI_Queue::processNextEvent()   
* 31 0x00007f562fa57efb [libHoudiniUI.so       ] UI_Queue::drain()     
* 32 0x00007f562fa587ff [libHoudiniUI.so       ] UI_Queue::eventLoop()      
* 33 0x00007f562f7b6327 [libHoudiniUI.so       ] main 
* 34 0x00007f55f8e413d4 [libc.so.6             ] __libc_start_main 
* 35 0x0000000000402d84 [houdini-bin           ]   
*
* loaded modules:
*    0x00007f558d32c000  libai.so
*    0x00007f5606200000  libpthread.so.0
*    0x00007f54f6d85000  hdArnold.so
*    0x00007f55fba91000  libpxr_hdx.so
*    0x00007f55fc229000  libpxr_hd.so
*    0x00007f5602989000  libpxr_usdImagingGL.so
*    0x00007f562293a000  libHoudiniUSD.so
*    0x00007f56311f1000  libHoudiniAPPS3.so
*    0x00007f562f571000  libHoudiniUI.so
*    0x00007f55f8e1f000  libc.so.6
*    0x0000000000400000  houdini-bin
*
* memory: VM 170301 MB, RSS 1513 MB, 10 page faults
****

**Comment by sirpalee** [comment]
I was unable to reproduce the crash on Linux and Houdini-18.0.287. Can you share more details?

**Comment by sirpalee** [comment]
@jhodgson could your #246 PR fix this issue as well?

**Comment by jhodgson** [comment]
After #246 there it is not crashing (tested on OSX).  

There is a temporary glitch in the display that looks like there is an update with an incorrect stride.
