### ISSUE TITLE
[build error]  syntax error: 'namespace'

### ISSUE THREAD

**Issue by kreppene** [Autodesk/arnold-usd#102]
**Describe the bug**
With the latest commits  i'm getting this errors when compiling
`LINK : fatal error LNK1181: cannot open input file 'libsdf.lib'`, the librarys inn my usd/lib folder is not prefixed with lib,

looks liker setting **USD_LIB_PREFIX=''**  inn the custom.py file fixses that problem, but now  i'm getting these errors

`e:\dev\build\arnold-usd\build\windows_x86_64\msvc_opt\usd-0.19.11_arnold-5.4.0.2\schemas\source\.//tokens.h(2980): error C2059: syntax error: 'namespace'
e:\dev\build\arnold-usd\build\windows_x86_64\msvc_opt\usd-0.19.11_arnold-5.4.0.2\schemas\source\.//tokens.h(2980): error C2238: unexpected token(s) preceding ';'`

**To Reproduce**
1.  Pull the latest commits, 
2.  Set USD_LIB_PREFIX='' in the custom.py 
3.  Build

**Used Software Versions**
 - Arnold: [e.g. 5.4.0.2]
 - USD: [e.g. 0.19.11]
 - Compiler: [visual stdio 2017]
 - OS: [e.g. windows 10]

**Comment by sebastienblor** [comment]
This 'namespace' issue should be fixed in PR #98

**Comment by kreppene** [comment]
i tested it @sebastienblor  and it works, im clssoing this issue, thanks
