### ISSUE TITLE
USD Instanceable Bug

### ISSUE THREAD

**Issue by brycegbrazen** [Autodesk/arnold-usd#1021]
**Describe the bug**
When creating a basic scene with 2 cubes, 2 cones, and 2 torus' that all have the Instanceable Metadata set to True, every time we render with Arnold inside of Maya, the instanceable prototype groups that get generated are being randomly assigned to each instance group. Every time you render, the instances swap places. For instance, the first render may be (Cube, Cube, Cone, Cone, Torus, Torus) and the next may be (Torus, Torus, Cube, Cube, Cone, Cone). Loading this same USD into Houdini and rendering with Arnold seems to render everything fine consistently.

**To Reproduce**
1. Download 
[cube_cone_torus.zip](https://github.com/Autodesk/arnold-usd/files/8037126/cube_cone_torus.zip)
2. Open Maya with Arnold and mayaUSD plugins active.
3. Load the zipped cube_cone_torus USD as a stage.
4. Add some sort of light so you can see the objects.
5. Render the scene and note the placement of the objects.
6. Render again, and note the placement of the objects.
7. Render a few more times to be sure that the objects are swapping places.

**Expected behavior**
I expect the Instanceable objects to render in the same spot every time.

**Screenshots**
![render1](https://user-images.githubusercontent.com/69012021/153315502-f57a59cc-0302-4c46-a0f8-827bb70c0664.png)
![render2](https://user-images.githubusercontent.com/69012021/153315506-9e00cb5b-2126-43d2-aea1-e69c7faac3a2.PNG)

**Used Software Versions**
 - Arnold: 6.2.1.1
 - MtoA: 4.2.4
 - mayaUSD: v0.13.0
 - OS: Windows 10
 - Houdini (for comparison testing): Houdini v19.0.383

**Additional context**
None.

**Comment by stephenrblair** [comment]
When I tried with the supplied scene in Maya, I got "Cache ID not valid" errors

**Comment by sebastienblor** [comment]
The issue also existed directly with a usd procedural (e.g. with a standin or in standalone with a usd procedural).
