### ISSUE TITLE
Smart opaque doesn't work with instancer in Hydra or in the procedural

### ISSUE THREAD

**Issue by stephenrblair** [Autodesk/arnold-usd#1023]
**Describe the bug**
Instances have an image plugged into standard_surface.opacity
The opacity is ignored. I have to use a Render Geometry Settings to set Opaque off

**To Reproduce**
1. Render the attached hip file in Solaris. Or kick test0274.usda file.
2. The planes render a solid color. There should be an xsilogo shaped cutout.

[opacity.zip](https://github.com/Autodesk/arnold-usd/files/8044285/opacity.zip)

**Expected behavior**
Smart opaque should work.

**Screenshots**

**Used Software Versions**
 - Houdini 19.0.455
 - HtoA 6.0.2.0

**Comment by compso** [comment]
ARNOLD-10677
