### ISSUE TITLE
Melanin Redness in Standard Hair shader does not work in Arnold 7

### ISSUE THREAD

**Issue by jacobberrier** [Autodesk/arnold-usd#1070]
**Describe the bug**

Melanin redness attribute in Arnold Standard Hair does not affect hair color. 

**To Reproduce**
1. Add a hair shader to curves or hair groom. 
2. Adjust melanin redness in shader.

**Expected behavior**

Expected to function as shown in documentation
![image](https://user-images.githubusercontent.com/101427306/157968010-d9604e18-bfd6-428f-bebf-270e96797fd0.png)

**Screenshots**

Arnold 6
![image](https://user-images.githubusercontent.com/101427306/157968174-cd6595f5-16b2-45f1-80d1-e626c4426721.png)

Arnold 7
![image](https://user-images.githubusercontent.com/101427306/157968236-e83a272a-482f-4cbb-850c-363f5d6efb32.png)

**Used Software Versions**
 - Arnold: [7.0.0.*]
 - HtoA: Present since 6.0.0.0
 - USD: [21.08]
 - OS: [Windows]
 - Any 3rd-party app: [Houdini 19.0.531]

**Additional context**

**Comment by sebastienblor** [comment]
Hi @jacobberrier would it be possible to send us a repro scene ? I'm not getting the same results than you're showing, but maybe I'm not doing the same steps.
Thanks !

**Comment by cpichard** [comment]
Hi,
this was fixed in the core and should be available in the next release.
Cyril
