### ISSUE TITLE
Asset with UDIMs dont render in Arnold USD Maya

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#111]
**Describe the bug**
Asset with UDIM textures don't render in Maya Arnold USD

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Maya with asset(has UDIMs)
2. Try to render it.

**Expected behaviour**
Should just render the way it does in Houdini

**Screenshots**
See added video:
[2019-12-19 09-36-07.flv.tar.gz](https://github.com/Autodesk/arnold-usd/files/3982263/2019-12-19.09-36-07.flv.tar.gz)

**Used Software Versions**
 - Arnold:  5.4.0.2
 - USD: 0.19.11
 - Compiler:  GCC 4.8.5
 - OS: Linux Centos 7
 - Any 3rd-party app: none

**Additional context**
Should I be using Arnold 6 in Maya?

**Comment by sirpalee** [comment]
Generally, yes, you should be using Arnold 6 as it includes some nice improvements to interactivity and GPU rendering, but we aim to support Arnold 5.4 and 6 currently.

**Comment by suesauer** [comment]
Will UDIMs work in 6?

**Comment by sirpalee** [comment]
UDIMs were supported a long time ago in the arnold core, so that's not the problem. I need to investigate how is Hydra passing and usd maya is passing the udim paths, and what can we do in either of those projects to make it work with the render delegate.

**Comment by dlekanis** [comment]
Any news on that? Still not rendering properly if usd is used as a procedural for arnold, both Houdini and Maya, rendering fine through solaris and usd render in houdini, but not through the standin.

error:
00:00:05  4106MB ERROR   |  [texturesys] could not read resolved image filename = "../../libs/textures/diff/Ch11_Diffuse_1001.exr"

**Comment by ansuter** [comment]
This is hitting us as well now. Are there any updates?

**Comment by cpichard** [comment]
Hi @ansuter , @suesauer, @dlekanis ,
The new version of the procedural should fix this issue, there was a patch to find the relative path anchors to the textures and I am guessing this addressing this issue. Unfortunately the example can't be downloaded now and I can't double check, so please let us know on this ticket if you still have issues with this new version of the procedural. Thanks !

**Comment by suekieza** [comment]
hey guy's this was one of my old accounts, I believe this ticket is resolved

**Comment by cpichard** [comment]
Thanks for confirming @suekieza.
