### ISSUE TITLE
Arnold USD Maya stage not updating changes in USD

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#112]
**Describe the bug**
Please see video, Stage doesn't seem to be updating in maya USD Arnold

**To Reproduce**
Steps to reproduce the behaviour:
1. Create simple asset with coloured shader, try changing colours

**Expected behaviour**
When updating the asset I expect it to work like a "Reference" as shown in video with Houdini USD. Updating should not require me to "re-open Maya" from scratch.

**Screenshots**
See Video below:
[2019-12-19 10-52-44.flv.tar.gz](https://github.com/Autodesk/arnold-usd/files/3982604/2019-12-19.10-52-44.flv.tar.gz)

**Used Software Versions**
 - Arnold: 5.4.0.2
 - USD: 0.19.11
 - Compiler:  GCC 4.8.5
 - OS: Linux Centos 7
 - Any 3rd-party app: None

**Additional context**
Perhaps this is a Maya-USD issue?

**Comment by sirpalee** [comment]
Hey @suesauer do you see the same behavior with HdStorm and HdEmbree?

**Comment by suesauer** [comment]
After a bit more testing it appears that the whole stage doesn't update unless you restart Maya from scratch.
