### ISSUE TITLE
Ambient light always on

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#113]
**Describe the bug**
Ambient light is always on in maya usd. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create usd asset with lights/or without. See asset as if light by a "skydome" in maya.

**Expected behaviour**
Perhaps it is better to work as seen in Houdini, where the asset is "black" until lights are added. Else ambient lighting must turn off when lights are actually already present in USD.

**Screenshots**
With no lights:
![Screenshot from 2019-12-19 12-02-15](https://user-images.githubusercontent.com/58251706/71164640-29aea800-2258-11ea-8540-4a0021c874bb.png)

With lights:
![Screenshot from 2019-12-19 11-27-55](https://user-images.githubusercontent.com/58251706/71164693-3f23d200-2258-11ea-98ed-fb714ed4cd40.png)

As you can see the ambient light is still on in the maya scene.

**Used Software Versions**
 - Arnold:  5.4.0.2
 - USD:  0.19.11
 - Compiler: GCC 4.8.5
 - OS: Linux Centos 7
 - Any 3rd-party app: None

**Comment by sirpalee** [comment]
Do you see the same behavior with HdStorm?

Otherwise, I believe this bugreport is for the maya-usd project, not this project. The render delegate renders whatever is in the Hydra Render Index.

**Comment by suesauer** [comment]
Hard to tell because Arnold shaders don't work in those delegates

**Comment by sirpalee** [comment]
What if you are using the pxr preview shaders? Or just a simple lambert? AFAIK both of those should be translated properly.

**Comment by sebastienblor** [comment]
The ambient light is determined by the scene delegate, so in this case is owned by the mayaUSD plugin and cannot be addressed here. Closing the ticket
