### ISSUE TITLE
Regression: shader discovery returns NdrNodes instead of SdrShaderNodes

### ISSUE THREAD

**Issue by JGamache-autodesk** [Autodesk/arnold-usd#1131]
**Describe the bug**
Prior to PR #974 the shader discovery parser was returning SdrShaderNodes. It now returns NdrNodes, which are considered legacy by USD. See https://github.com/PixarAnimationStudios/USD/issues/1836 for details.

**To Reproduce**

**Expected behavior**
Revert the NdrArnoldParserPlugin changes found in #974 while still making sure the results are sane.

**Screenshots**

**Used Software Versions**
 - Arnold: latest
 - USD: 21.11
 - Compiler: As shipping with MtoA
 - OS: Windows

**Additional context**

**Comment by sebastienblor** [comment]
I'm seeing in the comment that the reason to switch to SdrShaderNodes was because some attributes needed by Arnold were not supported through NdrNodes. It says "some attributes like 4 component colors", does it mean that RGBA attribute won't be supported ?

**Comment by sebastienblor** [comment]
ok good to know. I'll try to make it work as a vector4.

**Comment by sebastienblor** [comment]
@JGamache-autodesk  there's a PR in #1182 , but I cannot set you as a reviewer. Do you think it's ok ?

**Comment by JGamache-autodesk** [comment]
Code look OK to me. Definitely fixes the issue. Thanks.
