### ISSUE TITLE
Dome light is blown out

### ISSUE THREAD

**Issue by stephenrblair** [Autodesk/arnold-usd#1167]
**Describe the bug**
Dome light renders like it is over-exposed, but it seems to be more than that. Adjusting exposure isn't enough to fix the problem.

**To Reproduce**
1. Create a dome light.
2. Attach a texture to the dome light color
3. Render (either in Solaris, or by exporting a usd file and kicking it)

**Expected behavior**
Dome light should render as it did in previous versions.

**Screenshots**
Solaris. Dome light has a texture, but we get white.
![image (2)](https://user-images.githubusercontent.com/98059981/170722497-ce4e05ca-f82d-4769-a594-928098f9294b.png)

Kick versus Arnold Render View:
![image (3)](https://user-images.githubusercontent.com/98059981/170723125-4e47c5c8-b6c2-4033-9418-ffa11152598c.png)
![image (4)](https://user-images.githubusercontent.com/98059981/170723138-02dfe974-aab7-4ce6-82f3-f3ac886e1c52.png)

**Used Software Versions**
- Arnold: 7.1.2
- OS: Windows

**Additional context**
Reported by two different users.

**Comment by sebastienblor** [comment]
the issue in Solaris is actually the same as #1168. It's fixed in #1169
