### ISSUE TITLE
Change the default filter to box filter

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#117]
**Describe the feature you'd like**
Change the default filter type from gaussian to box.

**Additional context**
This improves interactivity with newer Arnold cores.

**Comment by kikou** [comment]
To clarify, this is to improve performance and specifically memory consumption when rendering in progressive mode. This is a limitation of the current version of Arnold (6.0.1) that should be removed in the future with gaussian filtering.
