### ISSUE TITLE
HtoA v6.1.2.0 and above break the prinicpled shader in Karma

### ISSUE THREAD

**Issue by Ahmed-Hindy** [Autodesk/arnold-usd#1196]
**Describe the bug**
using v6.1.2.0 or any above versions will render the principled shader useless in Karma but not in Mantra.

**To Reproduce**
1. I tried on a simple cube, couple of megascans assets and meshed FLIP tank
2. Import any/ all objects to solaris using "scene import" LOP and make sure the materials are applied to object.
3. add a light and a Karma LOP then enable the Karma hydra viewer
4. also try rendering to MPLAY, same issue persists

**Expected behavior**
objects should render with principled shader applied, either simple diffuse colors or texture maps like with megascans assets.

**Screenshots**

**Used Software Versions**
 - Arnold: [6.1.2.0 and 6.1.2.1]
 - OS: [win 10 21H2]
 - Any 3rd-party app: [Houdini v19.0.622 and v19.0.561]

**Additional context**
Arnold installed via package systems, other installed packages include megascans bridge, Qlib, and SideFX Labs

![image](https://user-images.githubusercontent.com/23151881/176473960-5702e696-dc3e-44c7-a94f-1d4a734f51cd.png)
![image](https://user-images.githubusercontent.com/23151881/176473955-abf62197-22f5-48b3-8152-0bc953bdccc7.png)

**Comment by Starzilla29** [comment]
I was able to recreate this bug with a simply sphere and a principle shader assigned from a material library.

**Comment by Ahmed-Hindy** [comment]
UPDATE: the new update 6.1.2.2 fixes the issue.

the update reads: "HTOA-2003 - Use the arnold render mask for shader vops to avoid conflict with other renderers" which I was skeptical at first but apparently yes this fixes the issue

**Comment by Ahmed-Hindy** [comment]
now you can mark this bug as fixed.

**Comment by jhodgson** [comment]
I'm glad this fixed your issue, thanks for the report.
