### ISSUE TITLE
Parsing of HOUDINI_PATH fails when it includes ;&

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#120]
**Describe the bug**
When the render delegate's volume adapter tries to load HtoA's `pygeo` library for supporting Houdini's in-memory volumes, the `HOUDINI_PATH` environment variable is not parsed properly.

**To Reproduce**
1. Include `;&` in `HOUDINI_PATH` and set it outside the `houdini.env` file on Linux or MacOS.

**Expected behavior**
The render delegate finds `pygeo`.

**Used Software Versions**
 - Arnold: 6.0.1.0
 - OS: MacOS 10.15/Centos7
 - Any 3rd-party app: Houdini-18

**Comment by Undsyr** [comment]
Hello! What if you already have added the **;&** but Arnold still displays: **[HdArnold] Cannot load _htoa_pygeo library required for volume rendering in Solaris** when rendering the standar volume shader within solaris? Is there any other way to approach this issue? My OS is Windows, so when you say to "set it outside the houdini.env file on Linux or MacOS" I guess I don't have to do it, right?

**Comment by sirpalee** [comment]
> Hello! What if you already have added the **;&** but Arnold still displays: **[HdArnold] Cannot load _htoa_pygeo library required for volume rendering in Solaris** when rendering the standar volume shader within solaris? Is there any other way to approach this issue? My OS is Windows, so when you say to "set it outside the houdini.env file on Linux or MacOS" I guess I don't have to do it, right?

Hi! No, you don't have to set HOUDINI_PATH outside the houdini.env file, it should work. Can you share the value of the HOUDINI_PATH env var inside Houdini?
