### ISSUE TITLE
Add support for building via cmake

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#121]
**Describe the feature you'd like**
Add support for building the project using CMake.

**Describe the solution you'd like**
I already have parts of the project build via cmake here: https://github.com/sirpalee/arnold-usd/tree/dev . We need to extend this to the testsuite, writer, translator, and the procedural and test on Windows/macOS.

**Additional context**
To reach full parity with scons, the most challenging part is the testsuite result generation. While running individual tests is trivial (and easier to extend than the current scons system), generating the webpage for the test results is mixed in with the code running the testsuite. So either we have to move it to an external module that can deal with testsuite results from any source, or offer an alternative.

**Comment by sirpalee** [comment]
I'm currently considering adding cmake without generating the testsuite results HTML file, so we can include this in the current sprint and create a separate ticket for the HTML file generation because there is room for improvement if we are going to redo the HTML generation. (like being able to open logs from the webpage, create reusable code for other Arnold team projects that both works with cmake and scons, etc.)

**Comment by sirpalee** [comment]
I created several tickets for this task and a project, so tracking progress on this is simpler.

The cmake config is now functional for all the targets (Render Delegate, Ndr, Translator, CMD, Writer) and tested on Linux.

**Comment by charlesfleche** [comment]
Does a CMake branch exists somewhere ? I'd be happy to test it here at RodeoFX. Thanks !

**Comment by sirpalee** [comment]
@charlesfleche That would be great! You can find my ongoing work [here](https://github.com/sirpalee/arnold-usd/tree/dev).

**Comment by charlesfleche** [comment]
I'm going through your CMake branch. Out of curiosity, is the dependency to CMake 3.1.1 an hard requirement ? Starting with CMake 3.12, the module `FindPython` is available, and much nicer to use with custom python builds that are located outside of the system default locations.

**Comment by sirpalee** [comment]
@charlesfleche I followed maya-usd's CMake requirement, as the preferred cmake version is not part of the VFX platform. USD requires 2.8 or 3.1 on windows, AL_USDMaya requires 3.1, usd-qt requires 3.1, OIIO requires 3.12, and OSL requires 3.12, to cherry-pick a few VFX/USD related projects.

With OIIO and OSL, we have the precedent of using 3.12, so I have nothing against bumping it up.

**Comment by charlesfleche** [comment]
I've never tried it, but maybe we could use `doxygen_add_docs` ? I'd expect this function to prevent unecessary doc rebuilds.
https://cmake.org/cmake/help/v3.9/module/FindDoxygen.html#command:doxygen_add_docs

**Comment by charlesfleche** [comment]
Available in CMake >= 3.9, though.
