### ISSUE TITLE
Create utility to render from the delegate in a file

### ISSUE THREAD

**Issue by cpichard** [Autodesk/arnold-usd#1250]
Currently the render delegate renders in a live buffer owned and managed by the usd hosts, like Houdini, usdview, etc.
There are some solution to render in a file, like husk or usdrecord, for comparing the render produced by the delegate to the one produced by kick, however none are convenient and scalable.

We would like a command line tool which allows to render on disk using the render delegate code path.

**Describe alternatives you've considered**
- husk, need an Houdini license
- usdrecord needs python and doesn't allow to pass render params.

**Comment by sebastienblor** [comment]
See #840
