### ISSUE TITLE
Issue adding image sequence in a light with the USD publisher

### ISSUE THREAD

**Issue by rosaMiraflores** [Autodesk/arnold-usd#1256]
**Describe the bug**
When trying to export in the USD publisher an image sequence linked to a light (a gobo image sequence for an instance), it gets only the current frame image from the exportation. We are not getting the Time Samples information by default (needed to get the complete image sequence linked to a light).  
We are doing a workaround in order to fix this behavior: adding a Edit Properties on the filename of the gobo image. 

**To Reproduce**
You can find attached a simple scene to reproduce this issue. You would just need to re path the image sequence of the gobo to your local folder. 

[light_animated_images.zip](https://github.com/Autodesk/arnold-usd/files/9301977/light_animated_images.zip)

**Expected behavior**
We expect to get the Time Samples info into the USD publisher automatically when you add an image sequence with the code "$F4" in the file name. 

**Screenshots**

![screenshot01](https://user-images.githubusercontent.com/110995569/183956225-8ca4cd96-af4b-4744-b039-87daa2d0804a.PNG)

![screenshot02](https://user-images.githubusercontent.com/110995569/183956372-b2b6aeac-d3dc-4f5a-b098-5615070c309a.PNG)

**Used Software Versions**
- HtoA: 6.1.3.0
- Arnold: 7.1.3.0
- Houdini: 19.0.561

**Comment by cpichard** [comment]
Hi @rosaMiraflores , after discussions, we feel this is a feature that should be included in houdini, otherwise we would be hacking and deviating from the usd standard and also potentially slow down the time to first pixel.
C
