### ISSUE TITLE
Instanceable prim as prototype of PointInstancer in Maya

### ISSUE THREAD

**Issue by ZimuQin** [Autodesk/arnold-usd#1262]
**Describe the bug**
Using Maya as the production software, when using an instanceable prim, which has payload or references composition arc, as the prototype of a PointInstancer, the rendering result is wrong. There would be one more object at the origin being rendered.

**To Reproduce**
1. Create USD stage with "point_instancer_bug.usda"
2. Add Arnold light
3. Use Arnold Render

**Expected behavior**
The rendered result should have the same amount of the models as defined in PointInstancer. There should be no objects at the origin.

**Attachments**
[point_instancer_bug.zip](https://github.com/Autodesk/arnold-usd/files/9356474/point_instancer_bug.zip)

**Screenshots**
![instanceable_off](https://user-images.githubusercontent.com/16183601/185038776-c53929f6-b018-4b57-bbd8-b912e2573629.png)
instanceable = false
![instanceable_on](https://user-images.githubusercontent.com/16183601/185038785-48a9784a-f075-4d13-9a8e-1eb94a426591.png)
instanceable = true

**Used Software Versions**
I have tested with both Maya 2022 and Maya 2023 in Windows and Linux, and tried with the latest mtoa and maya-usd releases. The result is the same.
Arnold: [e.g. 5.4.0.2] arnold 7.1.3.0, mtoa 5.2.0
USD: [e.g. 0.19.11] USD 21.11
Compiler: [e.g. GCC 4.8.5]
OS: [e.g. MacOS 10.15] Windows/Linux
Any 3rd-party app: Maya 2022, Maya 2023

**Additional context:**
The contents of the USD files:
*point_instancer_bug.usda*:
```
#usda 1.0
def PointInstancer "points"{
    point3f[] positions = [(10,0,0), (20,0,0), (30,0,0), (40,0,0), (50,0,0), (60,0,0), (70,0,0), (80,0,0)]
    int[] protoIndices = [0, 0, 0, 0, 0, 0, 0, 0]
    rel prototypes = </points/Prototype>
    def Scope "Prototype"(
        instanceable = true
        references = @./cube.usda@</MASTER>
    )
    {
    }
}
```

*cube.usda*:
```
#usda 1.0
(
    defaultPrim = "MASTER"
)
def Xform "MASTER"
(
    instanceable = true
)
{
    def Cube "box"
    {
        double size = 5
    }
}
```

**Comment by cpichard** [comment]
Thanks for reporting the issue @ZimuQin , we are having a look.
