### ISSUE TITLE
Solaris Arnold ignores some light parameters

### ISSUE THREAD

**Issue by Ahmed-Hindy** [Autodesk/arnold-usd#1274]
**Describe the bug**
setting some primvars like "primvars:arnold:cast_shadows = 0" or "primvars:arnold:shadow_color = {0,1,0}" wont result in an update to the hydra viewer. restarting the hydra viewer doesnt solve it.

**Steps to reproduce**
1. use the "light" LOP to add some arnold light parameters like disabling "cast shadows" and setting "shadow color" to {0,1,0}
2. start the Arnold hydra delegate

**Expected behavior**
no shadows from lights, or if shadows are enabled then the shadows should be green.

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - win 10, multiple builds across different machines
 - version Arnold 7.1.3.0
 - multiple PCs, first is "2 x Intel(R) Xeon(R) CPU E5-2680 v2", 2nd is "Ryzen 9 5950x"

First screenshot: Hydra viewer not respecting the "disable shadows"
2nd screenshot: Arnold USD procedural rendering the plain baked usd scene without any extras. Note how the shadows arent there !!

![Untitled](https://user-images.githubusercontent.com/23151881/186001548-dcba93ed-fef3-47df-b524-5ca94411f60e.png)
![Screenshot_14](https://user-images.githubusercontent.com/23151881/186001581-7ed92171-7eb9-42e4-9668-0b85a7b1fffd.png)

**Comment by cpichard** [comment]
Hi @Ahmed-Hindy , thanks a lot for reporting this issue. Which version of usd and houdini are you using ?
Thanks,
Cyril

**Comment by Ahmed-Hindy** [comment]
this issue was witnessed in H19.5.303 py3.9 with Arnold 7.1.3.0

issue was originally witnessed on a different machine with a H19.0 and a Arnold 7.1+ couple of weeks back. I can check later for exact specs

**Comment by compso** [comment]
We think this is fixed in HtoA 6.1.3.2 (#1272) can you please confirm if this issue still exists?

**Comment by Ahmed-Hindy** [comment]
the issue got fixed in the latest bug release @compso

**Comment by cpichard** [comment]
Thanks for confirming @Ahmed-Hindy .
