### ISSUE TITLE
AiSceneLoad does not load array type user parameter from usd

### ISSUE THREAD

**Issue by cpichard** [Autodesk/arnold-usd#1315]
**Describe the bug**
The attached archive has the test code.
The test code does the following:
create a node
declare a user array parameter on the node
save the node to .usd
load the node from .usd
verify if the node has the user array parameter set
The test fails with the following error:
WARNING | myimager: could not read ARRAY parameter "my_array"
[ERROR] 'my_array' is defined null 
Changing the format to .ass works fine.
Writing to usda and looking at the file, I can tell that the array is written correctly, so it's likely an issue with the loader:
    float[] primvars:my_array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] (
        elementSize = 16
        interpolation = "constant"
    )

[UsdUserArrayTest.cpp.zip](https://github.com/Autodesk/arnold-usd/files/9707554/UsdUserArrayTest.cpp.zip)

**Comment by sebastienblor** [comment]
This change broke a high amount of tests, so it's been reverted. Re-opening the ticket
