### ISSUE TITLE
Skinned instances in wrong world position

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#1352]
In the attached scene, the skinning is rendering properly, but the whole mesh is in the wrong position. There seems to be an error in the matrix computation
[arnold_crowd_render_repro.zip](https://github.com/Autodesk/arnold-usd/files/10029173/arnold_crowd_render_repro.zip)

**Comment by cpichard** [comment]
While looking at the scene, we found out that deactivating the animated matrix on /sopcrowdimport1/female_outfit_0 fixes the issue and gives the same render between procedural and delegate. This should help for finding the issue in the code
