### ISSUE TITLE
Solaris viewport render crashes when you change radius of sphere prototype for instancer

### ISSUE THREAD

**Issue by arnold-support** [Autodesk/arnold-usd#1359]
**Describe the bug**
Solaris viewport render crashes when you change radius of sphere prototype for instancer

**To Reproduce**
1. Load attached [scene](https://github.com/Autodesk/arnold-usd/files/10078207/instancer_crash.zip)
[instancer_crash.hip.txt](https://github.com/Autodesk/arnold-usd/files/10510775/instancer_crash.hip.txt)
2. Change radius of sphere. Houdini crashes.
On Windows, I get a CER (see Report 334117192)

**Used Software Versions**
 - Arnold: 7.1.4
 - OS: Windows, Linux
 - Any 3rd-party app: Houdini 19.5.403

**Additional context**

**Comment by cpichard** [comment]
Hi, the attached scene is invalid, @arnold-support could you resubmit it ?

**Comment by cpichard** [comment]
Hi,
It looks like it is an issue with arnold, I have filled an internal ticket.
C
