### ISSUE TITLE
USD writer not setting `timeCodesPerSecond` or `framesPerSecond` on stage

### ISSUE THREAD

**Issue by johnhaddon** [Autodesk/arnold-usd#1395]
**Describe the bug**

The USD writer does not set the `timeCodesPerSecond` or `framesPerSecond` fields on the USD stage when exporting from Maya. This means that the mapping between time samples and seconds is inaccurate for all FPS except 24 (the default).

**To Reproduce**

1. Export an animation from Maya at 25fps.
2. Examine the resulting USD file, and note that `timeCodesPerSecond` and `framesPerSecond` have not been authored.
3. Play back the file in an application that samples using seconds (e.g. Gaffer), and compare to a Maya export via the standard USD exporter or the Alembic exporter. Note that the Arnold version is offset.

**Expected behavior**

The `framesPerSecond` and `timeCodesPerSecond` metadata should be authored. It looks like the required value is already available on the `fps` parameter of the Arnold `options` node, as this is being written as `arnold:fps` on the `options` prim in the USD file.

**Screenshots**

![image](https://user-images.githubusercontent.com/1133871/213730604-eb9995d1-a8f1-4563-968e-2b73ce6f3c8e.png)

**Used Software Versions**

Unknown, but I have checked the head of the repo and can't see any evidence that the latest version is authoring the required metadata.

**Additional context**

Originally reported on the gaffer-dev mailing list here : https://groups.google.com/g/gaffer-dev/c/-R5QhXjBvW8?hl=en.

**Comment by cpichard** [comment]
Thanks for the report @johnhaddon , I can reproduce the issue on my side.

**Comment by cpichard** [comment]
Hi @johnhaddon , we have updated arnold-usd to correctly set the fps and tcps in the layer metadata, hopefully that should be included in the next release of mtoa.

**Comment by johnhaddon** [comment]
Nice! Thanks for the speedy turnaround!
