### ISSUE TITLE
CMake build does not include `read_skinning.cpp` in translator source list

### ISSUE THREAD

**Issue by nrusch** [Autodesk/arnold-usd#1414]
**Describe the bug**

CMake build does not include `read_skinning.cpp` in translator sources.

This results in link-time errors for any components relying on `libtranslator.a`.

The fix is to add `read_skinning.cpp` to the `SRC` list in [`translator/CMakeLists.txt`](https://github.com/Autodesk/arnold-usd/blob/e9b14480395c2cd07cc56d6ff4249254fe1512ad/translator/CMakeLists.txt#L1-L11):

**Used Software Versions**
 - arnold-usd: fix-7.1.4 branch (https://github.com/Autodesk/arnold-usd/commit/e9b14480395c2cd07cc56d6ff4249254fe1512ad)
 - Arnold: 7.1.4.1
 - USD: 22.05
 - Compiler: GCC 6.3.1
 - OS: CentOS 7.8

**Comment by cpichard** [comment]
Hi @nrusch , thanks for the report. 
The files were added in the CMakeLists in the most recent versions of arnold-usd, only the fix-7.1.4 has the issue, I'll push a fix. Did you try using the main branch instead ? it can fix many other issues as well.
C

**Comment by nrusch** [comment]
Hey @cpichard, thanks for the info. I was using the `fix-7.1.4` branch because I assumed that's what you used to build the arnold-usd components that ship with the Arnold SDK, but I guess that must not be the case? Or does the Scons build not have this same issue?

Generally speaking, I've been avoiding using the main branch because it's not at all clear whether it's considered a volatile "development" branch where things may break at any time, or what versions of Arnold it is/isn't intended to support. The tagging in this repo is a bit inconsistent, so it's hard to know exactly what code you are/aren't actively using.
