### ISSUE TITLE
Inconsistent arnold node names with instances

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#1419]
When a usd scene has instances, the naming of the prototype can change randomly. 
This causes flickering in cryptomatte, as it relies on the nodes names. It would also cause problems with operators

**Comment by cpichard** [comment]
When arnold-usd converts a scene containing instances, the generated prototypes might not have the same name between different runs, which can causes issues later on in cryptomatte. There is an environment variable USD_ASSIGN_PROTOTYPES_DETERMINISTICALLY to make sure that the prototypes will always get the same names. 
https://github.com/PixarAnimationStudios/USD/blob/dc710925675f7f58f7a37f6c18d046a687b09271/pxr/usd/usd/instanceCache.cpp#L41
