### ISSUE TITLE
Solaris fails to translate shader node that grouped in a subnet into USD materials correctly

### ISSUE THREAD

**Issue by xiaosi7700** [Autodesk/arnold-usd#1428]
**Describe the bug**

I am trying to create an arnold shader HDA but Solaris fails to translate shader node that grouped in a subnet into USD materials correctly.

**To Reproduce**
1. Create an Arnold Material Builder inside the Material Library .
2. Create a standard_surface shaders and two image node inside the Arnold Material Builder node and connect it .
3. Grouped this standard_surface shaders in a subnet .
4. You will find that only one image node and standard_surface can be translated into USD materials .
5. Here's a repro Houdini scene:[shader_Bug.zip](https://github.com/Autodesk/arnold-usd/files/10704567/shader_Bug.zip)

**Expected behavior**
All the shader nodes should be translated into USD materials.

**Screenshots**
![translate correctly](https://user-images.githubusercontent.com/65776638/218025103-5f537ccf-b3ff-437a-961f-a7e76687e4fa.jpg)
![fails](https://user-images.githubusercontent.com/65776638/218025106-2bd4c955-8207-4482-81e7-d24446a50a00.jpg)

**Used Software Versions**
 - HtoA 6.1.4.0
 - Houdini 19.5.403 py3.7

**Comment by ACE199704** [comment]
Is there any solution？I also meet this question.
![image](https://user-images.githubusercontent.com/23281568/222325627-69c970ca-89c7-4c34-a4e5-8d1d979833eb.png)
this is a subnet 
![image](https://user-images.githubusercontent.com/23281568/222326084-2bcf6ebb-e583-432c-94c3-0ec9175ced0b.png)

**Comment by sebastienblor** [comment]
This was fixed in the HtoA side and is planned to be shipped in a future release
