### ISSUE TITLE
st not translated to uv for curves

### ISSUE THREAD

**Issue by arnold-support** [Autodesk/arnold-usd#1435]
**Describe the bug**
In the attached Houdini scene, you need to set the checkerboard uv set to st to get the right result.
[arnold_curves.zip](https://github.com/Autodesk/arnold-usd/files/10784919/arnold_curves.zip)

**Comment by Ahmed-Hindy** [comment]
this isnt just for st/ uv, you can test it with Cd/ displayColor.
Arnold uses the new names of attributes after their conversion to their respective Pixar names.

**Comment by sebastienblor** [comment]
In my understanding that would be a different thing. Since "Cd" doesn't mean anything in arnold shaders it won't give you the expected the result. But the issue with uv/st seems to be something specific for this attribute.
