### ISSUE TITLE
Usd skel has inverted scale

### ISSUE THREAD

**Issue by haggi** [Autodesk/arnold-usd#1441]
**Describe the bug**
Loading a crowd agent via usd export from Houdini where the agents are scaled by a transform node results in a inverted scale in rendering.

**To Reproduce**
1. create crowd agent in houdini, transform it before export, export as usd.

**Expected behavior**
Scale should correspond to the one in Houdini.

**Used Software Versions**
- MtoA 5.2.2.3

**Additional context**
I attached the files, usd, ass, maya and Houdini to show the problem.
[usdAgentScale.zip](https://github.com/Autodesk/arnold-usd/files/10897694/usdAgentScale.zip)

**Comment by cpichard** [comment]
Hi @haggi,
thanks for the bug report. We recently fixed this issue in https://github.com/Autodesk/arnold-usd/pull/1412, I double checked your example and it is working with the next beta of mtoa.
C
