### ISSUE TITLE
Incorrect connections when using MaterialX nodes with multiple outputs

### ISSUE THREAD

**Issue by AdrienHerubel** [Autodesk/arnold-usd#1459]
MaterialX nodes with multiple outputs such as separate are not correctly connected.

See repro [data.zip](https://github.com/Autodesk/arnold-usd/files/11023844/data.zip)

There is also a pending Arnold fix preventing the OSL code from being generated in ARNOLD-13074, this fix should be applied first.

When resaving to an ass file the connection to the node appear as : 
```
 param_shader_in1 /World/materials/mtlxstandard_surface1/mtlxseparate3c1
 param_shader_in2 /World/materials/mtlxstandard_surface1/mtlxseparate3c1
 param_shader_in3 /World/materials/mtlxstandard_surface1/mtlxseparate3c1
```

instead of
```
 param_shader_in1 /World/materials/mtlxstandard_surface1/mtlxseparate3c1.param_outr
 param_shader_in2 /World/materials/mtlxstandard_surface1/mtlxseparate3c1.param_outg
 param_shader_in3 /World/materials/mtlxstandard_surface1/mtlxseparate3c1.param_outb
```

**Comment by compso** [comment]
Duplicates #714
