### ISSUE TITLE
Indirect AOVs are not rendered with Direct USD Render or kick

### ISSUE THREAD

**Issue by arnold-support** [Autodesk/arnold-usd#1495]
**Describe the bug**
The indirect AOVs come out black (for example, indirect or diffuse_indirect).
They render ok in the Solaris viewport.

**To Reproduce**
You can use the attached Houdini scene, or kick the attached usda files.
I also tried using the indirect LPE, and that didn't work either.

[indirect_aovs.zip](https://github.com/Autodesk/arnold-usd/files/11200803/indirect_aovs.zip)

**Used Software Versions**
 - Arnold 7.2.1

**Comment by cpichard** [comment]
It looks like we have the same result with other version, it is possible that the arnold:GI_diffuse_depth parameter is not set and defaulting to 0 which would remove the indirect contributions
