### ISSUE TITLE
Support materialx color spaces in hydra

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#1496]
In #1494  we added support for the colorSpace metadata of materialx shaders, when we render through the procedural. 

But this wasn't implemented in the render delegate yet. This ticket is about implementing it there as well

**Comment by Ahmed-Hindy** [comment]
this is much needed if we want MTLX to be intercompatible with other render engines like Karma. Right now it just treats everything as raw. For now dual shaders for both render engines seems the only way to go

**Comment by JGamache-autodesk** [comment]
Please note that USD 23.11 added support via https://github.com/PixarAnimationStudios/OpenUSD/commit/a8ec74c274da6d63ae964205c08e968f1642c5eb to have color space information transmitted via Hydra.
