### ISSUE TITLE
usd procedural loses material assignments for layered crowd sim

### ISSUE THREAD

**Issue by xsisupport** [Autodesk/arnold-usd#1524]
**Describe the bug**
Layered usd set up for a crowd sim, like this:
```
#usda 1.0
(
    endTimeCode = 1
    framesPerSecond = 24
    metersPerUnit = 1
    startTimeCode = 1
subLayers= [
@./stickAnim.usd@,
@./stickMatAssign.usda@,
@./stickColl.usda@,
@./stickStatic.usda@,
@./stickMaterialLib.usda@
    ]
    timeCodesPerSecond = 24
    upAxis = "Y"
)
```
Renders fine in Solaris viewport, USD View, and the Maya viewport (with Maya USD). But the usd procedural does not render with the assigned materials. All the geometry gets the default Arnold shader.

**To Reproduce**
Scene is attached

**Screenshots**
![usd-layered-crowd-sim](https://github.com/Autodesk/arnold-usd/assets/3514355/4487f747-566c-44b6-97c3-2fa09ecde723)

**Used Software Versions**
 - Arnold 7.2.1.1

**Comment by cpichard** [comment]
Hi @xsisupport , would you have the test scene ?
