### ISSUE TITLE
Light-linking on geometry lights not working correctly

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#1547]
The attached scene has a geometry light and light-linking, but the light linking doesn't seem to be applied properly
[geomLights.zip](https://github.com/Autodesk/arnold-usd/files/11633437/geomLights.zip)

**Comment by xsisupport** [comment]
Here's another Houdini scene that shows another asapect of the light linking problems with geometry lights.
As soon as you use light linking on some other light, the geometry light stops working.
[geometry_light_light_linking.zip](https://github.com/Autodesk/arnold-usd/files/14126439/geometry_light_light_linking.zip)

The HDDEBUG ass file shows that the geometry light is not added to the polymesh light_groups.
Like this:
`polymesh
{
 name /sphere1

 use_light_group on
 light_group 2 1 NODE
"/lights/arealight1" "/lights/arealight_yellow"

}

mesh_light
{
 name /sphere1/light
 color 0 0 1
 exposure 12
 mesh "/sphere1"
}`
