### ISSUE TITLE
Issue with the render context priority (procedural)

### ISSUE THREAD

**Issue by pierre-ed** [Autodesk/arnold-usd#155]
**Describe the bug**
Hello everyone.

Maybe it is not an actual bug, but the priority with which the procedural sorts a UsdShadeMaterial's resolved surface outputs for different render contexts seems counter-intuitive. A material `outputs:surface` property takes precedence over a more specific `outputs:arnold:surface` property. 

Karma behaves the other way for instance: using the material's `outputs:surface` as a fallback when `outputs:karma:surface` is undefined instead.

The involved code seems to be [here](https://github.com/Autodesk/arnold-usd/blob/47711e8839a230f1210722653a698911ff09357b/translator/reader/utils.cpp#L317-L319).

**To Reproduce**
1. Unzip the [archive](https://github.com/Autodesk/arnold-usd/files/4087357/context_issue.zip).
2. Run the following from the archive's directory
```
kick context_issue.ass
```

**Expected behavior**
The cube appears blue, whereas an Arnold-dedicated surface output is defined on its bound material and should make it appear red instead. Removing the property `/my_material/outputs:surface` enables the procedural to use the surface source resolved for the Arnold context.

**Used Software Versions**
 - Arnold: 6.0.1.0
 - USD: 0.19.11
 - Compiler: GCC 4.8.5
 - OS: CentOS Linux release 7.6.1810

**Comment by sirpalee** [comment]
Thank you for the report! One thing to note, your suggested behavior is what the Render Delegate / Hydra is doing and it's the same behavior across other Render Delegates.

#156 fixes your issue.

**Comment by sirpalee** [comment]
Reopening the ticket, as updating the test suite reference image was not part of PR #156 .

**Comment by sirpalee** [comment]
I confirmed that the pull request works fine with USD 0.19.5, but fails with 0.19.11 and 0.20.2.

I'm keeping the ticket open and looking for a solution.

**Comment by sirpalee** [comment]
The code was behaving as expected, but the explicit definitions for the outputs ports on the shaders were missing from the test file. This didn't cause an issue in the older USD version, but newer ones fail with it. Created a new pull request that fixes the testsuite for 0.19.11 and 0.20.2.
