### ISSUE TITLE
Crash when rendering usd exported from SpeedTree

### ISSUE THREAD

**Issue by peterhorvath111** [Autodesk/arnold-usd#1593]
The attached usd file is exported from [SpeedTree](https://store.speedtree.com/), which is a vegetation modeling software. Arnold crashes in the node initialization stage when rendering. The same usd file loads fine in Cinema 4D.

**To Reproduce**
- Download and unzip the attached [SpeedTree_usd_error.zip](https://github.com/Autodesk/arnold-usd/files/12080276/SpeedTree_usd_error.zip)
- Run `kick -dp Trellis_Growth_v05.usd`

Tested on Windows with Arnold 7.2.2.1 and Arnold 7.2.3.0.beta56.

**Comment by cpichard** [comment]
Hi, as a first look at the scene we can see materials defined under the mesh. I am guessing the Mesh primvars are inherited in the shaders and we don't want that or at least the arnold usd procedural doesn't work well in this situation.

**Comment by cpichard** [comment]
Hi @peterhorvath111 , 
I found out that the crash is due to a UsdPrimvarReader shader where the varname is missing, the code was assuming that the varname is always set, as otherwise the primvar reader is not reading anything.
Do you know if the material is created by speedtree or any third party ??
Thanks

**Comment by peterhorvath111** [comment]
I believe it's created by SpeedTree. Is this something which goes against the usd specs, and should be fixed in their exporter? Or something we should handle in our code? Cinema 4D imports the file correctly, so they must handle this use-case. Here's the material, loaded in C4D:
![image](https://github.com/Autodesk/arnold-usd/assets/75612144/b8dd7414-42e5-4c92-8b55-09f7454e6126)
