### ISSUE TITLE
Trouble compiling on linux centos 7

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#160]
**Describe the bug**
Tried to compile but it errors out

**To Reproduce**
My build:
scl enable devtoolset-6 bash
$ ./abuild ARNOLD_PATH="/opt/solidangle/mtoa/2019" USD_PATH='/home/sue.sauer/Documents/USD' USD_BUILD_MODE='monolithic' BOOST_INCLUDE='/usr/include' PYTHON_INCLUDE='/usr/include/python2.7' PYTHON_LIB='/usr/lib' PYTHON_LIB_NAME='python2.7' PREFIX='/home/sue.sauer/Documents/Maya_arnold-usd'

2.
Building Arnold-USD:
 - Build mode: 'opt'
 - Host OS: 'linux'
 - Arnold version: '5.4.0.2'
00:00:00    59MB         | log started Thu Jan 23 10:59:50 2020
00:00:00    59MB         | Arnold 5.4.0.2 [30d7daaa] linux clang-5.0.0 oiio-2.1.0 osl-1.11.0 vdb-4.0.0 clm-1.0.3.513 rlm-12.4.2 optix-6.0.0 2019/10/09 17:02:02
00:00:00    59MB         | running on localhost.localdomain, pid=9228
00:00:00    59MB         |  1 x AMD Ryzen Threadripper 2990WX 32-Core Processor (32 cores, 64 logical) with 128686MB
00:00:00    59MB         |  NVIDIA driver version 430.50 (Optix 60102)
00:00:00    59MB         |  GPU 0: GeForce RTX 2080 SUPER @ 1860MHz (compute 7.5) with 7981MB (6467MB available) (NVLink:0)
00:00:00    59MB         |  CentOS Linux 7 (Core), Linux kernel 3.10.0-1062.4.1.el7.x86_64
00:00:00    59MB         |  soft limit for open files raised from 1024 to 4094
00:00:00    59MB         |  
00:00:00    59MB         | loading plugins from /opt/solidangle/mtoa/2019/bin/../plugins ...
00:00:00    59MB         | loaded 5 plugins from 3 lib(s) in 0:00.01
00:00:00    59MB         |  
00:00:00    59MB         | releasing resources
00:00:00    52MB         | Arnold shutdown

**Expected behaviour**
I use to be able to build with this(December20) now it errors out.

**Screenshots**
Here's the error in the terminal:
![Screenshot from 2020-01-23 11-09-00](https://user-images.githubusercontent.com/58251706/72970692-d7215800-3dd0-11ea-8980-f6251598edae.png)

**Used Software Versions**
 - Arnold: 5.4.0.2
 - USD: Latest USD dev branch
 - Compiler: GCC 4.8.5]
 - OS: Linux Centos 7
 - Any 3rd-party app: Maya and Houdini

**Comment by sirpalee** [comment]
@suesauer what is the name of your monolithic, USD library? The linker is unable to find it.

Also, from the looks of it, you are using GCC 6.3.1. (which is supported, so that's not an issue)

**Comment by suesauer** [comment]
I believe its /home/sue.sauer/Documents/Maya_arnold-usd

**Comment by sirpalee** [comment]
Please run `ls /home/sue.sauer/Documents/USD/lib` and paste the results here. That's the directory that should contain the usd library. I suspect you might have a shared build, or the monolithic library is prefixed.

**Comment by suesauer** [comment]
screen grab
![Screenshot from 2020-01-23 14-03-17](https://user-images.githubusercontent.com/58251706/72983050-23789200-3de9-11ea-9eee-69b1517f58a4.png)

**Comment by sirpalee** [comment]
Changing `USD_BUILD_MODE` to `'shared_libs'` should fix your problem. Please let me know if that helped.

**Comment by suesauer** [comment]
will do

**Comment by suesauer** [comment]
Now it says:

![Screenshot from 2020-01-23 14-30-37](https://user-images.githubusercontent.com/58251706/72984676-f75f1000-3dec-11ea-9cb0-46c566079e2f.png)

**Comment by sirpalee** [comment]
Correct, we need to update our code to work with the latest USD development builds. I suspect some functions got removed and we need to use alternatives.

**Comment by suesauer** [comment]
Will try rebuild with master and see what breaks, will let you know. Thanks for the help. Should I mark this as closed?
