### ISSUE TITLE
Bucket size and similar parameters missing in Arnold Render Settings LOP

### ISSUE THREAD

**Issue by luisfos** [Autodesk/arnold-usd#1640]
HtoA 6.2.3.1 
H19.5.682

**Comment by TomMinor** [comment]
Closing this as it's on the HtoA side and will be fixed by HTOA-2414

**Comment by TomMinor** [comment]
Hi @luisfos, this has been fixed in the [latest bugfix release of HtoA (6.2.4.2)](https://help.autodesk.com/view/ARNOL/ENU/?guid=arnold_for_houdini_6242_html)
