### ISSUE TITLE
Render delegate treating mesh points like primvars

### ISSUE THREAD

**Issue by nrusch** [Autodesk/arnold-usd#169]
**Describe the bug**

The changes in 2c560850f5b42812cc6ffb2d964c6bb60326c850 (specifically the removal of [this block](https://github.com/Autodesk/arnold-usd/commit/2c560850f5b42812cc6ffb2d964c6bb60326c850#diff-d49dcdd0b5485576daf540fbaa4015a4L63-L67)) switched to handling mesh points the same way as other primvars. This means that unless scene delegates return a primvar descriptor for the points (which seems unnecessarily redundant), the render delegate won't actually generate a vertex list in Arnold.

While I don't think Hydra explicitly states whether or not points should be treated the same way as other primvars, there are enough examples of them being handled separately that I think the change above should be considered a regression.

Examples:

- `HdChangeTracker::DirtyBits` differentiates points from other primvars, and `HdChangeTracker::MarkPrimvarDirty/IsPrimvarDirty` have special-case handling to set `DirtyPoints` instead of `DirtyPrimvar`.
- The `UsdImagingDelegate` handles points separately from primvars.
- The Renderman and 3Delight render delegates handle points separately.

**Comment by nrusch** [comment]
Just as a follow-up, since `HdRprim` now includes the concept of "core" geometric primvars for derived types (via the new-ish `GetBuiltinPrimvarNames` method), it seems like there should be an implicit awareness of those that is separate from other generic primvars.

**Comment by sirpalee** [comment]
Hey @nrusch , thanks for reporting this and pointing me to `HdChangeTracker::IsPrimvarDirty`!

I think the safest option would be to reinstate the old bits for translating points, but keep the code in the primvar loop running, if points weren't set earlier. This would support the case when points are not part of the primvar descriptors and when `DirtyPoints` is not set, but `DirtyPrimvars` is.

I'll create a pull request for the issue, and please let me know what you think about the solution.

We also should ask Pixar for a clarification of what Hydra expects and refine the solution in a future issue/pull request.

**Comment by nrusch** [comment]
Thanks @sirpalee , I think your solution makes sense.
