### ISSUE TITLE
Maya USD Export does not include material correctly

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/arnold-usd#1721]
**Describe the bug**

When exporting from Maya 2024.1 with MayaUSD 0.25.0 and Mtoa 5.3.4 via the Maya USD export the shaders/materials do not get exported correctly with the `Arnold` job context (Plug-in configuration) set for the export.

![image](https://github.com/Autodesk/arnold-usd/assets/2439881/6ebb033c-a23f-4c8d-bff1-484cd3678878)

It comes out like this:

```usda
def Scope "mtl"
{
    def Material "aiStandardSurface1SG"
    {
    }
}
```

This is for both export selection and export all. Due to the missing data it does not render the shader as it was intended originally.

When instead using the `Arnold-USD` exporter it comes out like this:
```usda
def "mtl"
{
    def Material "aiStandardSurface1"
    {
        token outputs:arnold:surface.connect = </mtl/aiStandardSurface1/aiStandardSurface1.outputs:surface>

        def Shader "aiStandardSurface1"
        {
            uniform token info:id = "arnold:standard_surface"
            float inputs:base = 0.80128205
            color3f inputs:base_color = (0.26923078, 0, 0)
            float inputs:diffuse_roughness = 0.42948717
            float inputs:metalness = 0.4551282
            float inputs:specular = 0.30769232
            color3f inputs:specular_color = (0.17948718, 0.17948718, 0.17948718)
            float inputs:transmission = 0.21794872
            token outputs:surface
        }
    }
}
```

**To Reproduce**
1. Create a cube
2. Assign aiStandardSurface
3. Select cube
4. File > Export Selected > USD Export > with Arnold plug-in configuration

_There's no difference if I do export all or when exporting selected also select the material + shading engine_

Example MEL that executes for me is:
```
file -force -options ";exportUVs=1;exportSkels=none;exportSkin=none;exportBlendShapes=0;exportDisplayColor=0;;exportColorSets=1;exportComponentTags=1;defaultMeshScheme=catmullClark;animation=0;eulerFilter=0;staticSingleSample=0;startTime=1;endTime=1;frameStride=1;frameSample=0.0;defaultUSDFormat=usda;parentScope=;shadingMode=useRegistry;convertMaterialsTo=[UsdPreviewSurface,rendermanForMaya,MaterialX];exportRelativeTextures=automatic;exportInstances=1;exportVisibility=1;mergeTransformAndShape=1;stripNamespaces=0;worldspace=0;jobContext=[Arnold]" -typ "USD Export" -pr -es "C:/Users/User/Desktop/arnold_test.usda";
```

**Expected behavior**

Exported USD file should render fine when loaded back into Maya USD Proxy Shape.

**Used Software Versions**

 - Maya: 2024.1
 - MayaUSD: 0.25.0
 - Mtoa: 5.3.4
 - OS: Windows

**Additional context**

Tested with other versions - same behavior:

- Mtoa 5.3.4 + MayaUSD 0.24.0
- Mtoa 5.3.2 + MayaUSD 0.25.0
- Mtoa 5.3.4 + MayaUSD 0.23.1 (= default MayaUSD for Maya 2024.1)

**Comment by BigRoy** [comment]
Interestingly enough I also don't see "Materials" listed for Arnold materials. Could this be a misconfiguration? Or is that expected behavior and would job context "Arnold" solve that instead?

![image](https://github.com/Autodesk/arnold-usd/assets/2439881/9bce6967-1e57-4d0e-8e16-0a4aadefe5fb)

**Comment by BigRoy** [comment]
The export seems to work fine in Maya 2023.3 + MayaUSD 0.20.0 + Mtoa (maya2023 install = 5.2.1.1). ✅ 

There I also see the **usdArnold** sub menu here.

![image](https://github.com/Autodesk/arnold-usd/assets/2439881/b82d3b40-808b-4b59-98aa-f37c273dd690)

---

In the failing Maya 2024.1 + MayaUSD 0.25.0 + Mtoa 5.3.4 I get:

![image](https://github.com/Autodesk/arnold-usd/assets/2439881/f3de0044-56cc-4e3d-92a8-1c230d1c3b0b)

---

As such, it's either a regression OR a misconfiguration on my end. The `usdArnold` menu lacking completely in All Registered types for Add New Prim hints to me the latter - but I'm not sure what configuration in particular is missing.

**Comment by sebastienblor** [comment]
Hi @BigRoy  indeed the Arnold plugin configuration replaced the previous "Arnold" checkbox for materials. Enabling it will automatically export the arnold shaders.

You must be facing a problem in the installation or some version mismatch issue (although the versions you're showing seem to be compatible). I just tried your steps and I do have the expected shader
![Capture](https://github.com/Autodesk/arnold-usd/assets/13153907/832f988e-2b4f-4ca1-bbe9-2a8464b686f5)

This is something that is continuously tested by our automation in all OSes and with the different versions of Maya that we support.
Do you see something in the log mentionning an error with the Arnold plugin configuration ?

**Comment by sebastienblor** [comment]
The fact that the arnold node types don't show up in the list is also an indicator that something isn't loaded properly, but it should now be explicitely dumped in the log

**Comment by BigRoy** [comment]
Found it - it seems I managed to misconfigure: `MAYA_PXR_PLUGINPATH_NAME` to an invalid path. 
Somehow had my `.mod` file that I was testing versions with use:

- wrong:  `MAYA_PXR_PLUGINPATH_NAME += usd`
- correct:  `MAYA_PXR_PLUGINPATH_NAME +:= usd`

**Comment by sebastienblor** [comment]
it should be in the script editor. This was added recently and should be in MtoA 5.3.4

**Comment by BigRoy** [comment]
Should I be seeing that _on render_ or _on export_ or _on maya launch_? I couldn't find anything.

Maybe just the types not being registered is different than what logs might have shown if anything else was misconfigured. Maybe it wouldn't know what it'd be missing if the types aren't registered to begin with. ;)
