### ISSUE TITLE
Endless refresh loop in USD 23.08/23.11

### ISSUE THREAD

**Issue by RichardFrangenberg** [Autodesk/arnold-usd#1751]
**Describe the bug**
When setting Arnold as the active renderer in Usdview, it starts to render a first pixelated frame and then seems to be in a constant refresh loop.

**To Reproduce**
1. Set Arnold as the active renderer in Usdview.

Here's a recording of the problem:
https://github.com/Autodesk/arnold-usd/assets/12097019/7f8d155d-a5f8-4348-a6a8-d8c545c745cc
(I set a thread limit to save some performance for the screen capture)

**Expected behavior**
The rendering should progressively add more samples in the image and refresh only when objects or the camera is transformed.

**Used Software Versions**
 - Arnold: 7.2.4.1
 - USD: 23.08, 23.11
 - OS: Windows 11

**Additional context**
I've seen that other people have have the same problem, so it's not something specific only to my machine or my USD build.

**Comment by cpichard** [comment]
Thanks ! we'll have a look

**Comment by cpichard** [comment]
Hi @RichardFrangenberg ,
We were able to reproduce the issue only with usdview and found out that for each render iteration usdview is updating a render setting parameter which in turn restarts the render. The line is here: https://github.com/PixarAnimationStudios/OpenUSD/blob/0b18ad3f840c24eb25e16b795a5b0821cf05126e/pxr/usdImaging/usdviewq/stageView.py#L1453C6-L1453C6

It's in the python code and removing it will solve the issue. I'll make a ticket on the pixar usd repo.

**Comment by cpichard** [comment]
follow up here: https://github.com/PixarAnimationStudios/OpenUSD/issues/2870
