### ISSUE TITLE
kick and sick do not render ArnoldProceduralCustom

### ISSUE THREAD

**Issue by xsisupport** [Autodesk/arnold-usd#1753]
**Describe the bug**
An ArnoldProceduralCustom does not render with kick or sick. It does render with husk.

**To Reproduce**

- Loaded the attached Houdini scene and render with Direct USD Render.
- Or export a usd file and kick it.

[hip_yeti_example.zip](https://github.com/Autodesk/arnold-usd/files/13342811/hip_yeti_example.zip)

**Used Software Versions**
 - Houdini 6.2.4.x
 - Windows

**Comment by cpichard** [comment]
Hi,
it looks like the ArnoldProceduralCustom prim has a transform which isn't converted by the procedural.
