### ISSUE TITLE
Procedural does not render motion blur for SkelAnimation

### ISSUE THREAD

**Issue by xsisupport** [Autodesk/arnold-usd#1781]
**Describe the bug**
Arnold usd procedural does not render motion blur for SkelAnimation. Render delegate in Solaris does.

**To Reproduce**
1. In Maya, load [agent.usda](https://github.com/Autodesk/arnold-usd/files/13636204/agent.zip) with an aiStandIn.
2. Render.
3. No motion blur. The first and last frames look to have some blur, but all the frames in-between have no blur.

Changing frames while the ARV is running crashes Maya. CERs point to usd_proc.

Also, USD for Maya does not render motion blur. Create a stage from file, and render that with Arnold. No blur.

**Expected behavior**
Motion blur, as in Solaris with the Arnold Render Delegate.

**Used Software Versions**
 - Latest Arnold

**Comment by cpichard** [comment]
Hi, the motion blur will depend on the shutter_open and shutter_close parameter of the camera. I am guessing the default maya perspective camera doesn't have shutter_open and shutter_close set, that would explain why there is no motion blur.
However I can confirm it crashes in the arnold viewport when changing the frame.

**Comment by cpichard** [comment]
Hi,
with the patch which fixes the crash #1830, I can see the motion blur but only if it is enabled in the render settings :

<img width="1097" alt="Screenshot 2024-01-26 at 15 56 15" src="https://github.com/Autodesk/arnold-usd/assets/300243/425e9387-5a2d-4a8b-a398-457a6dc810f7">

Could you double check on your end ?

Thanks !
