### ISSUE TITLE
HTOA,win64 ,Can not run arnold in pure CPU renderfarm.

### ISSUE THREAD

**Issue by dishuman** [Autodesk/arnold-usd#1786]
**Describe the bug**

htoa-6.2.5.0_r82d49d1_houdini-20.0.547
Arnold cannot run on a PC without a GPU or any graphics card; it is designed solely for CPU rendering in a pure CPU render farm node.

I have tried the following methods:

Using the Deadline Houdini plugin for rendering.
Executing husk.exe xxx.usd.
Running kick.exe xxx.ass.
Attempting to list renderers with husk.exe --list-renderers.
Checking for help with kick.exe --help.
In all cases, Arnold exits without any error code. Installing a GPU resolved the issue. I also attempted to use CUDA_VISIBLE_DEVICES=-1 to skip the GPU check, but it did not work.

However, when I tested htoa-6.0.2.2_r01f7d08_houdini-19.0.561 and versions before it (e.g., htoa-5.5.0.0_r5b05c8c_houdini-18.5.351), they worked perfectly on a pure CPU render farm.

Here is the only log that HUSK prints:

"C:\Program Files\Side Effects Software\Houdini 20.0.506\bin\husk.exe" -s /Render/rendersettings --make-output-path -f 1 -R HdArnoldRendererPlugin --purpose geometry,render --complexity high --stderr c:\husk_error.log --verbose 9 "s:/render.usda"

[11:02:47] CPU Genuine Intel(R) CPU @ 2.20GHz
[11:02:47] Architecture - AMD64: mmx xmmx sse sse2 cmov fpcmov ht sse3 ssse3 sse4.1 sse4.2 avx avx2
[11:02:47] System limit: 8192 file descriptors

**To Reproduce**

1, Prepare a PC without any GPU or graphics card. Do not use "CUDA_VISIBLE_DEVICES=-1" to emulate.
2, Open CMD.
3, Run kick.exe --help or husk.exe --list-renderers.
4, You won't receive any output or error logs.

**Screenshots**
![image](https://github.com/Autodesk/arnold-usd/assets/19814259/616b057a-cc41-4fee-9298-5d9c498e2329)

**Used Software Versions**
from
htoa-6.1.3.3_rdb15014_houdini-19.5.368
to
htoa-6.2.5.0_r82d49d1_houdini-20.0.547
all have this bug.

**Additional context**
The last version that worked for a CPU farm was "htoa-6.0.2.2_r01f7d08_houdini-19.0.561." After that, it appears that Arnold requires a DCH driver, which might explain why it's not working now.

**Comment by sebastienblor** [comment]
Hi @dishuman , as this issue is not related to arnold-usd I will close this ticket. I see you also posted about this in the HtoA forum so we'll keep the discussion in there. Cheers
