### ISSUE TITLE
USD Skel motionblur is inverted 

### ISSUE THREAD

**Issue by xsisupport** [Autodesk/arnold-usd#1837]
**Describe the bug**
The motion blur on a USDSkel loaded with the usd procedural does not match the motion blur on an alembic version of the same character (see screenshot below: left is usd, right is alembic)

The right character has - for my eyes - the correct motionblur since the right foot does not move what I can see in the maya UI. This one is created with a aiStandin and an alembic file exported from Houdini.
The left one is created with an aiStandIn and an USD file showing the same frame but the motionblur is somehow inverted. The characters right foot has motionblur even if it does not move.

I checked the alembic and usd in Karma in Houdini and both show the same motionblur which looks like the right character in the image. So I suppose it may be somehow related to the arnold usd procedural.

**Screenshots**
![mb](https://github.com/Autodesk/arnold-usd/assets/3514355/ba1b2977-c202-4fd8-897a-cdeb3bb24862)

**Used Software Versions**
 - Arnold: 7.2.5.1

**Comment by BigRoy** [comment]
@xsisupport Are you able to provide the Alembic or USD file for this test?

On the USD one - could it be that the motion blur (velocity) stays the same throughout the whole frame range? E.g. it maybe samples the velocity on e.g. the start frame of the sequence? Could it be that there maybe is velocity data written along with the mesh (accidentally?) that is not timesampled?

**Comment by xsisupport** [comment]
[mb_problem.zip](https://github.com/user-attachments/files/16459540/mb_problem.zip)

**Comment by cpichard** [comment]
This happens when the skinned geo is instanced, the procedural reads the matrices from the prototypes instead of the current prim
