### ISSUE TITLE
Moving the camera triggers an update of the scene in the render delegate.

### ISSUE THREAD

**Issue by cpichard** [Autodesk/arnold-usd#1854]
**Describe the bug**
When we move the camera in the render delegate, it looks like Arnold is updating the scene while it should be only re-rendering. On big scene this could be very slow.
This happens since this PR: https://github.com/Autodesk/arnold-usd/pull/1692

**Comment by BigRoy** [comment]
Should be fixed with #1855 and likely can be closed?

**Comment by cpichard** [comment]
It should have been closed automatically indeed.

**Comment by sebastienblor** [comment]
the fix hasn't been included in Arnold 7.2.5.3. But it will land in the next one
