### ISSUE TITLE
Make arnold relative path optional in image nodes

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#1878]
Depending on how a usd file was authored, we can want the image filename relative paths to be considered the "Arnold way" (i.e. relative to the arnold texture_search_path), or the "USD way" (relative to the layer). 

This is important when relative paths have UDIMs, as we're currently trying to solve this only for UvTexture shaders, but not for arnold image shaders.

The Arnold relative paths are needed when an arnold scene is converted to usd, in order to ensure a roundtrip between ass & usd is possible.
However, when the usd file was authored from another source (i.e. Lookdevx), it's more natural to consider relative paths as USD would.

A solution for that could be that the writer adds a special attribute on the UsdShade primitive (e.g. arnold_relative_path), and that the reader looks for it to know what to do. This way, all usd files authored from an arnold scene will keep behaving as arnold expects, but files created elsewhere would now behave as UvTexture does, and would support UDIM tokens on relative paths.

**Comment by BigRoy** [comment]
How about storing this as metadata on the asset paths' attributes? I believe MaterialX for example does that in Houdini Solaris to specify the colorspace of a particular filepath being loaded. It's not a separate attribute but instead becomes metadata of the asset path.

As a quick example, see this screenshot:
![image](https://github.com/Autodesk/arnold-usd/assets/2439881/90af54a1-8c6d-4b97-b04f-b4b9d9564c7e)

Which looks e.g. like this in the usda file:
```usda
...
        def Shader "mtlximage1"
        {
            uniform token info:id = "ND_image_color3"
            asset inputs:file = @/path/to/my/file.exr@ (
                colorSpace = "ACES - ACEScg"
            )
            color3f outputs:out
        }
...
```

---

As such, we could e.g have attribute metadata like:
```
            asset inputs:file = @/path/to/my/file.exr@ (
                arnold_relative_path = "/path/to/search/path"
            )
```

Potentially we could have a special string value that could indicate using a 'global' search path as opposed to needing to author a search path per attribute - if that's something we'd ever need.

**Comment by sebastienblor** [comment]
Good point about the metadata, it will be cleaner indeed. Just a detail, we don't want to specify a relative path in the metadata, but just a boolean flag to let arnold deal with the search path as it usually does (through the global attribute options.texture_search_path)

**Comment by BigRoy** [comment]
> but just a boolean flag to let arnold deal with the search path as it usually does (through the global attribute options.texture_search_path)

Great, even better!

What I like about the metadata is that you can set it per attribute, instead of per prim.
