### ISSUE TITLE
Support hydra curves

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#19]
Add support for hydra curves.

We can use [hdPrman/basisCurves.cpp](https://github.com/PixarAnimationStudios/USD/blob/4b1162957b2ad219e1635c81de8343be490e41fc/third_party/renderman-22/plugin/hdPrman/basisCurves.cpp) as an example implementation.

**Comment by sirpalee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Render Delegate] Support curves](https://trello.com/c/JX6hHd7l/31-render-delegate-support-curves)

**Comment by musbel** [comment]
Logiciel Lumiere is asking about this on the HtoA mailing list.
