### ISSUE TITLE
clip_geo does not work with PointInstancers when you render with kick or sick

### ISSUE THREAD

**Issue by xsisupport** [Autodesk/arnold-usd#1905]
**Describe the bug**
clip_geo works with the render delegate. But when you render with kick or sick, the clipped geometry is visible, and it renders black.

**To Reproduce**
Extract and kick the attached usda file.
[clip_geo_test.zip](https://github.com/Autodesk/arnold-usd/files/15180152/clip_geo_test.zip)

A similar setup created in Maya and exported with Maya USD works.
The main diff in the usda that I see is the prototype.
From Solaris, it is

```
`    def Scope "Prototypes" (
        kind = "group"
    )
    {
        def Xform "torus1" (
            apiSchemas = ["MaterialBindingAPI"]
            kind = "component"
        )
```
From Maya USD:

```
    def "Prototypes" (
        kind = "group"
    )
    {
        def Mesh "pHelix1_0" (
            prepend apiSchemas = ["ArnoldPolymeshAPI"]
            kind = "component"
        )
```

**Screenshots**
![clip_geo](https://github.com/Autodesk/arnold-usd/assets/3514355/0b51288b-9bc6-436e-800f-73e5c92991f5)

**Used Software Versions**
 - Arnold 7.3.1
 - HtoA 6.3.1

**Comment by cpichard** [comment]
After some investigation, the issue happens in the core when the clip geo has to affect instances of procedural, this is not related to USD and can be simplified to add file procedurals. This has been passed to the core team.

**Comment by cpichard** [comment]
this is now fixed in the core, closing the ticket
