### ISSUE TITLE
husk with arnold product always renders float 

### ISSUE THREAD

**Issue by xsisupport** [Autodesk/arnold-usd#1999]
**Describe the bug**
You can set up a mix of float and half render vars, but you get all float

**To Reproduce**
1. Load attached the scene [mixed_half_float.zip](https://github.com/user-attachments/files/16275726/mixed_half_float.zip)
.
2. Render
3. Check render vars with oiiotool, they are all float

**Expected behavior**
A mix of half and float, as specified in the render settings.

**Used Software Versions**
 - Latest HtoA available to Arnold support 
as of July 2024

**Additional context**

**Comment by cpichard** [comment]
this is a duplicate of #1989
