### ISSUE TITLE
UV Index order reversed in render delegate

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#207]
After 776ea72323fd674c79863918708d9d5bfdf31b80 the Arnold render delegate in Solaris is showing the wrong uvs.  

We need to apply isLeftHanded logic to the uvidxs as well, reversing the ordering, and potentially other face varying properties too.

**Comment by sirpalee** [comment]
The challenge here is that for reversing the winding for additional data requires keeping a copy of the vertexCounts. VtArrays share their data and generally COW, so we should be able to store the VtArray without duplicating memory.
