### ISSUE TITLE
Failing to build the simplest of shading networks... (procedural)

### ISSUE THREAD

**Issue by pierre-ed** [Autodesk/arnold-usd#211]
**Describe the bug**
Hello everyone!
I must be missing something obvious, but I cannot manage to embed a very simple Arnold shading network in UsdShade and have the procedural correctly handle it. 
I am trying to feed the `base_color` input of a `standard_surface` shader with the output of an `image` shader. Unfortunately, in all my attempts, the connection between those shaders is not considered as valid and is superseded by the `base_color`'s default value.

**To Reproduce**
1. Unzip the [archive](https://github.com/Autodesk/arnold-usd/files/4187322/issue_shading_network.zip)
2. Run the command `kick scene.ass`

**Expected behavior**
The same shading setup is described in the `reference.ass`. Just run `kick reference.ass` to have the expected image rendered.

**Used Software Versions**
 - Arnold: 6.0.1.0
 - USD: 0.20.02
 - Compiler: GCC 4.8.5
 - OS: CentOS Linux release 7.6.1810 (Core)

**Comment by pierre-ed** [comment]
Hello.
Turns out I did miss something obvious. :)
After a quick look at the code, it appears connections between shaders do not require the specification of any output attribute : the connection's target must directly match another shader's name (which is its prim's path). [Here](https://github.com/Autodesk/arnold-usd/blob/699d762fba8ebd123c4e16019bab692f5ef7363a/translator/reader/reader.cpp#L396) is the code involved.

The following material hence perfectly works (Note that `</myMaterial/myImage>` does not explicitly declares any output anymore): 
```
def Material "myMaterial"
{
    token outputs:surface.connect = </myMaterial/myShader.outputs:surface>
    def Shader "myShader"
    {
        uniform token info:id = "arnold:standard_surface"

        token outputs:surface
        color3f inputs:base_color.connect = </myMaterial/myImage>

    }
    def Shader "myImage"
    {
        uniform token info:id = "arnold:image"

        asset inputs:filename = @./texture.jpg@
        string inputs:uvset = "st"
    }
}
```
Sorry for the noise. 
Cheers.

**Comment by sirpalee** [comment]
Hey @pierre-ed you should be able to connect an output parameter to an input. I'm reopening the ticket, as I think it's still a valid problem and I want to give you a proper answer about what's going wrong in your example.

**Comment by Jordibastide** [comment]
Hello all, I was about creating a new issue linked to this one. The solution you mentioned @pierre-ed is not supported by the hydra render delegate. So we do not get the same behavior between Hydra and the procedural (a bit confusing).

Thanks for the reopening !
