### ISSUE TITLE
Create motion keys using the velocity attribute

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#221]
To implement velocity motion blur when the velocity attribute is present in the usd file, we should create two motion keys based on the velocity and the position as we do for example in the alembic procedural and when exporting geometry in HtoA.

**Comment by sebastienblor** [comment]
This relates to #564

**Comment by jhodgson** [comment]
Example file with velocity atttribute

[test.usd_rop1.usda.zip](https://github.com/Autodesk/arnold-usd/files/6050200/test.usd_rop1.usda.zip)
