### ISSUE TITLE
Support material binding for UsdGeomSubsets (procedural)

### ISSUE THREAD

**Issue by pierre-ed** [Autodesk/arnold-usd#224]
**Describe the bug**
Hi everyone!
It seems the Arnold procedural does not currently support material assignment per face set. Either when stated in the `*.ass` scene or directly in the USD stage, the material assignment statements are ignored and no material is applied to the geometry.
![render](https://user-images.githubusercontent.com/5444972/74749139-fabdae00-5269-11ea-824e-b73e00336890.jpg)

This issue is certainly linked with #29 (although the later targets the render delegate and not the procedural).

**To Reproduce**
1. Unzip the [archive](https://github.com/Autodesk/arnold-usd/files/4219906/issue_geomsubset.zip)
2. Either run `kick material_assign_in_ass.ass` or `kick material_assign_in_usd.ass`

**Expected behavior**
Depending on which UsdGeomSubset it falls into, each face should be shaded with the material bound to said subset. Follows a screenshot of the `shaded_suzanne.usda` scene rendered by Karma.
![karma](https://user-images.githubusercontent.com/5444972/74748779-5a678980-5269-11ea-92d4-3a03405a5299.jpg)

**Used Software Versions**
 - Arnold: 6.0.1.0
 - USD: 0.20.02
 - Compiler: GCC 4.8.5
 - OS: CentOS Linux release 7.6.1810

**Comment by sirpalee** [comment]
#29 is the render delegate equivalent of this.
