### ISSUE TITLE
Support varying user data on points node

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#228]
Currently varying usd attributes are exported to varying user data on the arnold nodes.  This is correct for the polymesh case.  However there is a special case for the arnold points node that the data should be declared as uniform to interpolate correctly.  

This will need to be taken into account for the usd procedural and the render delegate.

**Comment by jhodgson** [comment]
The test attribute for example is expanded as varying instead of uniform, and so the user data doesn't pick it up.

[attributes.usda.zip](https://github.com/Autodesk/arnold-usd/files/4225994/attributes.usda.zip)

**Comment by sirpalee** [comment]
@jhodgson the render delegate already had code in place to convert per-vertex primvars to uniform, however it didn't support uniform attributes. I submitted a pr that translates uniforms for points as well, and @sebastienblor added support for this in the procedural.
