### ISSUE TITLE
RGBA shader parameters not working with the render delegate

### ISSUE THREAD

**Issue by shycats** [Autodesk/arnold-usd#236]
**Describe the bug**
RGBA parameters on shaders are not being translated by the render delegate.

**To Reproduce**
1. Create a sphere and a material library node
2. Create a standard_surface shader
3. Create a layer_rgba shader
4. Connect the layer_rgba shader to the base_color of the standard_surface shader
5. On the layer_rgba shader, enable only the first layer, set color to red, alpha to “1” and mode to “overwrite”
6. Assign the standard_surface shader to the sphere
7. Add a light
8. Render in Hydra viewport with Arnold
9. The sphere renders black

**Expected behavior**
A render of a red sphere.

**Screenshots**

**Used Software Versions**
 - Arnold: 6.0.2.0 (HtoA 5.1.0)
 - USD: Houdini 18.0.348 shipped version
 - Compiler: N/A
 - OS: Windows 10 Pro
 - Any 3rd-party app: Houdini 18.0.348

**Additional context**
Looking at the render delegate code, there is something that looks like a mistake in [utils.cpp](https://github.com/Autodesk/arnold-usd/blob/master/render_delegate/utils.cpp) (line 453) and it may be related to this bug:

```
        case AI_TYPE_RGBA:
            if (value.IsHolding<GfVec3f>()) {
                const auto& v = value.UncheckedGet<GfVec4f>();
                AiNodeSetRGBA(node, paramName, v[0], v[1], v[2], v[3]);
            }
```

Where `value.IsHolding<GfVec3f>()` should probably be `value.IsHolding<GfVec4f>()`

**Comment by sirpalee** [comment]
Thank you for the report, I created a pull request to fix this. You were right, this was a class "copy-paste" mistake in `HdArnoldSetParameter`. Good catch!
