### ISSUE TITLE
Delegate discards light transform during params-only sync

### ISSUE THREAD

**Issue by nrusch** [Autodesk/arnold-usd#243]
Currently, when a light's params are marked dirty, the render delegate will completely reset the Arnold light node prior to syncing the params. However, unless `HdLight::DirtyTransform` is also part of the dirty mask, the light's transform will be lost after the sync due to the node reset.

https://github.com/Autodesk/arnold-usd/blob/master/render_delegate/light.cpp#L219

**Comment by sirpalee** [comment]
I added a workaround for this problem, but in the future we should get rid of the AiNodeReset call in the light sync. I created a new issue for improving this workaround #255 .

**Comment by nrusch** [comment]
Great, thanks @sirpalee!
