### ISSUE TITLE
Support USDskel

### ISSUE THREAD

**Issue by martinkindl83** [Autodesk/arnold-usd#265]
Hello.
i would like to check about support for Houdinis Crowd and USDskel.
Currently i can render USD Crowds in Karma, it saves rest pose and then bones deformation, so filesize is very small. Unfortunately with Arnold, it renders my crowd on correct spot, but in restpose.

Not sure what needs to be done, but for our company, having crowd support on USD for Arnold is huge.

Thank you very much for looking into it

Martin

**Comment by sirpalee** [comment]
Hi @martinkindl83 thank you for the report, I was able to reproduce the issue locally.

**Comment by sirpalee** [comment]
I started working on this and added some utility functions that can compute the primvars that are dynamic. (sirpalee/arnold-usd@cebb4df34405b2dddfeb05ce49da0a5f47150aa7)

The complexity comes from the Hydra computation utils not returning motion blur data by default (I based my work on HdEmbree, which does not support this), so mixing it with the current code that supports motion-blurred primvars for points and normals is going to be messy. I will aim for supporting computed primvars as soon as possible, so we can have it in the next HtoA primvar, then look into motion-blurred computed primvars in a follow-up ticket.

**Comment by martinkindl83** [comment]
Thank you very much for looking into it.

**Comment by sirpalee** [comment]
Rendering the crowds in Houdini with the latest changes look like this:

![Screenshot from 2020-03-11 12-44-23](https://user-images.githubusercontent.com/582376/76374037-2548e580-6396-11ea-8df3-b8f1d9716399.png)

**Comment by martinkindl83** [comment]
Thats great, i havent expected to get it so quick. i reported it to Julian form solidangle months ago :)

**Comment by jhodgson** [comment]
This is looking great!

@martinkindl83: we support rendering packed agents from HtoA already (see https://trac.solidangle.com/htoa/ticket/1124).

This ticket allows us to support crowds from Solaris too.

**Comment by sirpalee** [comment]
As preparing the pull request for closing this issue, I was doing some more tests and found that the Usd Skel examples from openusd.org are not working. So I'm going to recheck everything and figure out why those examples are failing.

**Comment by martinkindl83** [comment]
> 
> 
> This is looking great!
> 
> @martinkindl83: we support rendering packed agents from HtoA already (see https://trac.solidangle.com/htoa/ticket/1124).
> 
> This ticket allows us to support crowds from Solaris too.

Hello Julian
Yes i know about it, unfortunately rendering packed fragments or packed agents its much much slower then rendering unpacked geometry. Not mentioning that ass files are huge and take more then 250GB ram for stadium full of people.

**Comment by martinkindl83** [comment]
Thank you very much for this fix, it does with it for me, when using Solaris. How ever this doesnt work when using Arnold Procedural and loading USD. not sure where to report this problem. If here a github, or under Htoa ticket system.
