### ISSUE TITLE
Quotes in CMake "${Boost_LIBRARIES}" break Windows builds.

### ISSUE THREAD

**Issue by Tuftux** [Autodesk/arnold-usd#275]
**Describe the bug**
Using the master branch, when building with CMake the build fails to link "optimized.lib". Going into the individual CMakeLists.txt files and changing similar lines from this : 
`target_link_libraries(hdArnold PRIVATE "${Boost_LIBRARIES}" Python2::Python)`

To this : 
`target_link_libraries(hdArnold PRIVATE ${Boost_LIBRARIES} Python2::Python)`

Fixes the build. I think it has to do with with array cmake variables not being expanded correctly ? Not a super expert with CMake.

**To Reproduce**
1. Get latest master. Compile with CMake. My options are like so : 
`cmake -G "Visual Studio 15 2017 Win64" ../ -DCMAKE_INSTALL_PREFIX=%RELEASE_DIR% -DCMAKE_BUILD_TYPE=Release -DARNOLD_LOCATION=%ARNOLD_ROOT% -DUSD_LOCATION=%USD_ROOT% -DDPython2_ROOT_DIR=%PYTHON_ROOT% -DTBB_INCLUDE_DIR=%TBB_INCLUDE_DIR% -DTBB_LIBRARY=%TBB_LIBRARY% -DBUILD_DOCS=OFF -DBUILD_SCHEMAS=OFF
`

**Used Software Versions**
 - Arnold: 6.0.1.0
 - USD: 20.02
 - Compiler: MSVC 14.1
 - OS: Windows 10

**Comment by sirpalee** [comment]
Thank you for the report!

I generally put paths in quotes, because it solves an issue if they contain spaces. And several guides/posts on the mailing list share the same advice: quote your paths.

In cmake invocation, you don't pass anything to configure boost. Where is your boost installed?

Can you post your whole cmake log?

**Comment by Tuftux** [comment]
Hey !

Indeed manually setting `Boost_NO_SYSTEM_PATHS=ON` and BOOST_INCLUDEDIR / BOOST_LIBRARYDIR fixes the issue. For some reason I must have thought it would take Boost from the USD config. Not sure how I could get a full log that is helpful for you of the CMake build, any guidance ? Not a great expert at CMake and the CMakeOutput.log comes mostly empty right now.

Thanks !

**Comment by sirpalee** [comment]
Hey, in theory, you should see the results in the terminal. I think cmake is not finding the boost libs, and you are getting an error message about passing "-NOT_FOUND" libs to some of the cmake functions.

For now, we don't detect the boost in the USD installation, so you need to set up the variables separately. I'll create a new ticket for this case and close this down.
