### ISSUE TITLE
Lib issue in houdini 18.0.348

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#291]
**Describe the bug**
Tried to import an asset with a arnold shader on it

**To Reproduce**
1. Try to import asset with an arnold shader

**Expected behavior**

To be able to import an asset with a shader(this shader was just created in houdini)

**Screenshots**
![Screenshot from 2020-03-20 12-50-45](https://user-images.githubusercontent.com/58251706/77157246-a6e0f780-6aa9-11ea-862a-4014be1f8c61.png)

**Used Software Versions**
 - Arnold: 6.0.2.0
 - USD: 0.19.11
 - Compiler: GCC 6.3.1
 - OS: Linux 7
 - Any 3rd-party app: Houdini

**Additional context**
I tried to re-openning houdini from the terminal with the LD_Preload set but I believe im pointing to the wrong place maybe
` $ LD_PRELOAD=/home/suesauer/Documents/arnold_run/arnold_sdk/bin/libai.so
[suesauer@localhost bin]$ ./hescape
[suesauer@localhost bin]$ 00:00:00     0MB         | log started Fri Mar 20 12:57:16 2020
00:00:00     0MB         | Arnold 6.0.2.0 [f2a1d573] linux clang-5.0.0 oiio-2.1.4 osl-1.11.0 vdb-4.0.0 clm-1.1.1.118 rlm-12.4.2 optix-6.5.0 2020/02/12 13:46:16
00:00:00     0MB         | running on localhost.localdomain, pid=93889
00:00:00     0MB         |  1 x AMD Ryzen Threadripper 2990WX 32-Core Processor (32 cores, 64 logical) with 128686MB
00:00:00     0MB         |  NVIDIA driver version 430.50 (Optix 0)
00:00:00     0MB         |  CentOS Linux 7 (Core), Linux kernel 3.10.0-1062.4.1.el7.x86_64
00:00:00     0MB         |  soft limit for open files raised from 1024 to 4094
00:00:00     0MB         |  
00:00:00     0MB         | loading plugins from /home/suesauer/Documents/arnold_run/arnold_sdk/bin/../plugins ...
00:00:00     0MB         |  alembic_proc.so: alembic uses Arnold 6.0.2.0
00:00:00     0MB         |  usd_proc.so: usd uses Arnold 6.0.2.0
00:00:00     0MB         |  cryptomatte.so: cryptomatte uses Arnold 6.0.2.0
00:00:00     0MB         |  cryptomatte.so: cryptomatte_filter uses Arnold 6.0.2.0
00:00:00     0MB         |  cryptomatte.so: cryptomatte_manifest_driver uses Arnold 6.0.2.0
00:00:00     0MB         | loaded 5 plugins from 3 lib(s) in 0:00.06
00:00:00     0MB         | [htoa_op] Begin registration ...
00:00:00     0MB         | loading plugins from /home/suesauer/htoa/htoa-5.1.0_r9289183_houdini-18.0.348/htoa-5.1.0_r9289183_houdini-18.0.348/arnold/plugins ...
00:00:00     0MB         |  htoa_mandelbulb_proc.so: mandelbulb uses Arnold 6.0.2.0
00:00:00     0MB         | loaded 1 plugins from 1 lib(s) in 0:00.00
00:00:00     0MB         | [htoa_op] Loading metadata file: /home/suesauer/htoa/htoa-5.1.0_r9289183_houdini-18.0.348/htoa-5.1.0_r9289183_houdini-18.0.348/arnold/metadata/operators.mtd
00:00:00     0MB         | [htoa_op] Loading metadata file: /home/suesauer/htoa/htoa-5.1.0_r9289183_houdini-18.0.348/htoa-5.1.0_r9289183_houdini-18.0.348/arnold/metadata/lights.mtd
00:00:00     0MB         | [htoa_op] Loading metadata file: /home/suesauer/htoa/htoa-5.1.0_r9289183_houdini-18.0.348/htoa-5.1.0_r9289183_houdini-18.0.348/arnold/metadata/shapes.mtd
00:00:00     0MB         | [htoa_op] Loading metadata file: /home/suesauer/htoa/htoa-5.1.0_r9289183_houdini-18.0.348/htoa-5.1.0_r9289183_houdini-18.0.348/arnold/metadata/options.mtd
00:00:00     0MB         | [htoa_op] Loading metadata file: /home/suesauer/htoa/htoa-5.1.0_r9289183_houdini-18.0.348/htoa-5.1.0_r9289183_houdini-18.0.348/arnold/metadata/cameras.mtd
00:00:00     0MB         | [htoa_op] Loading metadata file: /home/suesauer/htoa/htoa-5.1.0_r9289183_houdini-18.0.348/htoa-5.1.0_r9289183_houdini-18.0.348/arnold/metadata/shaders.mtd
00:00:00     0MB         | [rop_operators] Registering operators ...
00:00:00     0MB         | [rop_operators] operator registration done.
00:00:00     0MB         | [vop_shaders] Registering shaders ...
00:00:00     0MB         | [vop_shaders] shader registration done.
00:00:00     0MB         | [htoa_op] End registration.
00:00:00     0MB         |  
00:00:00     0MB         | releasing resources
00:00:00     0MB         | Arnold shutdown
00:00:00   118MB         | Arnold 6.0.2.0 [f2a1d573] linux clang-5.0.0 oiio-2.1.4 osl-1.11.0 vdb-4.0.0 clm-1.1.1.118 rlm-12.4.2 optix-6.5.0 2020/02/12 13:46:16
00:00:00   118MB         | authorizing with license manager: network ...

------------------------ 'houdinicore-bin' is dying ------------------------
houdinicore-bin crashed. FATAL ERROR: [TF_DEBUG_ENVIRONMENT_SYMBOL] multiple symbol definitions.  This is usually due to software misconfiguration.  Contact the build team for assistance. (duplicate 'TF_SCRIPT_MODULE_LOADER')
in _Add at line 96 of /home/oscar/devel/arnold/tools/kook/usd/build/usd-19.05_shared_linux_clang-5.0.0/pxr/base/lib/tf/debug.cpp

The stack can be found in localhost.localdomain:/var/tmp/st_houdinicore-bin.93889
done.`

**Comment by melMass** [comment]
@suesauer Did you ever found a solution?
