### ISSUE TITLE
Empty Arnold SdrRegistry ?

### ISSUE THREAD

**Issue by Tuftux** [Autodesk/arnold-usd#293]
**Describe the bug**
The SdrRegistry does not seem to contain any Arnold nodes when using the Arnold Render Delegate with the Ndr plugin compiled. Should i attempt to get the nodes in another way ?

**To Reproduce**
Calling pxr::SdrRegistry::GetInstance().GetNodeIdentifiers() does not return any Arnold nodes. I have checked and i do get : 
`Registering shared library plugin 'ndrArnold' at 'd:/CODE_LIBRARIES_AUTO/BUILDS/Arnold-USD-XXXX-release/plugin/ndrArnold.dll'.`

**Used Software Versions**
 - Arnold: Latest Beta
 - USD: 20.02
 - Compiler: Visual Studio 2017
 - OS: Windows 10

**Comment by sirpalee** [comment]
What if you run the following script?

```
from pxr import Sdr

sdr = Sdr.Registry()

for shader in sdr.GetShaderNodesByIdentifier("arnold:standard_surface"):
    print shader
```

My result is:

```
arnold:standard_surface (context: 'arnold', version: '6', family: 'shader'); URI: '<built-in>'
```

This is tested on Linux and USD 0.20.02.

**Comment by Tuftux** [comment]
Interesting, what you suggested does work on my end as well, but i can't seem to be able to just query all the nodes that the SdrRegistry should know about. I do get to see all the Prman ones listed, but no luck with Arnold so far.
What I'm trying to get is a list of all the "availble" shading nodes from the SdrRegistry. Not a huge expert in USD so there's also a chance i might be approaching it the wrong way, but so far this seems to work for native USD shaders and Prman nodes.

Thanks for the quick answer !

**Comment by sirpalee** [comment]
Can you please share a snippet of how you are listing the shaders?

We are currently setting the family of the discovered shaders to `shader` (and later we would use the other types common in arnold). This is an optional parameter, so maybe that's throwing off your query?

```
from pxr import Sdr, Ndr

sdr = Sdr.Registry()

for shader in sdr.GetShaderNodesByFamily("shader", Ndr.VersionFilterAllVersions):
    print shader
```

This lists all the arnold shaders.

**Comment by Tuftux** [comment]
Aha ! I had no idea the Ndr.VersionFilterAllVersions was required to parse all the nodes. Thanks you very much for the help, adding this argument fixes my issue !
