### ISSUE TITLE
Detect boost and other dependencies in USD_LOCATION when using cmake

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#294]
**Describe the feature you'd like**
The cmake scripts should detect the boost and other dependencies from USD_LOCATION. This helps when users are building USD using the official build scripts and don't handle the dependencies separately.

**Comment by cpichard** [comment]
Closing as this is now implemented in the cmake build. if found cmake will use pxrConfig.cmake provided by the usd distribution and set the dependencies as described in pxrTargets.cmake.
