### ISSUE TITLE
Unitialized _instancer variable in render_delegate shape.h

### ISSUE THREAD

**Issue by Tuftux** [Autodesk/arnold-usd#298]
**Describe the bug**
Hi ! I am no git expert at all so I won't attempt submitting push request, but i've found a small mistake in shape.h in the render delegate. There is a protected member variable named _instancer at line 107 that is never initialized on simple shapes. But when the Rprim gets deleted, the shape desctructor checks for a nullptr on _instancer and crashes on the unitialized variable. Simply setting _instancer = nullptr in shape.h fixed the bug on my end.

**To Reproduce**
I am building my own tool so it's not easy to share a repro, but i've noticed the bug whenever i was resetting prims or switching layers in my usd app. Also, this may be my app not having the correct behavior, but it seems like editing materials on shapes deletes and recreates the prim, i'd have to investigate further.

**Used Software Versions**
 - Arnold: Latest Beta
 - USD: 20.02
 - Compiler: Visual Studio 2017
 - OS: Windows 10

**Comment by sirpalee** [comment]
Good catch, thanks!
