### ISSUE TITLE
Import the Shading Mode Exporter plugin from Luma Pictures

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#30]
Luma Pictures' usd-arnold provides a Maya Shading Mode Exporter plugin, which can be used to export Arnold shader definitions from usdMaya. Even though this repository might not be the final place for that exporter, we should allow early adopters to build the plugin and use it in its current form.

[The usdMaya plugin](https://github.com/LumaPictures/usd-arnold/tree/8df3f080119016ed571e1dc0db68849a1cb81c25/maya)

**Comment by sirpalee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Arnold extension for USD Exporter](https://trello.com/c/mvrNB4k2/15-arnold-extension-for-usd-exporter)

**Comment by sirpalee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Maya] Import the maya shader exporter plugin from Luma](https://trello.com/c/tD2ygAgU/85-maya-import-the-maya-shader-exporter-plugin-from-luma)

**Comment by sirpalee** [comment]
@BigRoy you will want this for usd-maya.

**Comment by kreppene** [comment]
Should we move this issue over to the maya-usd Project?
