### ISSUE TITLE
usdview cannot render ass ArnoldProcedural with Arnold

### ISSUE THREAD

**Issue by JerryKon** [Autodesk/arnold-usd#315]
**Describe the bug**
ArnoldProcedural prim cannot be rendered in usdview with Arnold Delegate.

**To Reproduce**
Below is the usd file. ass file is exported from Maya.
#usda 1.0
(
    defaultPrim = "world"
)

def Xform "world"
{
    def ArnoldProcedural "proc"()
    {
        string filename="/path/to/cube.ass"
    }
}

**Expected behavior**

**Screenshots**

**Used Software Versions**
 - Arnold: 6.0.2.1
 - USD:  0.19.11
 - Compiler: GCC 4.8.5
 - OS: Centos7
 - Any 3rd-party app: [e.g. Katana-3.2]

**Additional context**

**Comment by sirpalee** [comment]
To support this, we need to add a new module, a set of plugins for UsdImaging. These would allow us to create new Hydra primitives that the render delegate can interpret.

**Comment by sirpalee** [comment]
This should be resolved in #185 , so closing this ticket as a duplicate.
