### ISSUE TITLE
Statically linked procedural causing crashes in the render delegate

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#337]
**Describe the bug**
As of 6.0.2.0, the Arnold SDK included a procedural that statically links all its dependencies. When using the render delegate, this is causing random crashes, as `AiBegin()` loads all the procedurals in the `<arnold_sdk>/plugins` subfolder. After some investigation, initializing the work scheduler is responsible for the crash, and it always crashes when PXR_WORK_THREAD_LIMIT is set to 1. I was only able to reproduce this issue on windows so far.

For reference the core ticket number is 9435 .

**To Reproduce**
1. Set PXR_WORK_THREAD_LIMIT to 1
2. Launch usdview with any scene and set the renderer to Arnold

**Used Software Versions**
 - Arnold: 6.0.2.0
 - USD: 0.19.11
 - OS: Windows 10

**Comment by sebastienblor** [comment]
this doesn't seem to be an issue anymore, closing the ticket
