### ISSUE TITLE
Aborted render should mark render pass as converged

### ISSUE THREAD

**Issue by nrusch** [Autodesk/arnold-usd#4]
Currently, performing a blocking Hydra render to completion requires a pattern similar to the following:

```c++
auto tasks = taskController->GetRenderingTasks();
do {
    engine.Execute(renderIndex, &tasks);
}
while (!taskController->IsConverged());
```

Right now, if the render performed by `HdArnoldRenderPass` aborts for any reason, the render pass is not marked as converged, and thus the above code will block indefinitely.

I think the most "correct" thing to do in the case of an Arnold render error is to mark the pass as converged and zero the render pass' output buffers.

**Comment by kikou** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Render Delegate] Aborted render should mark render pass as converged](https://trello.com/c/lT56S2aI/96-render-delegate-aborted-render-should-mark-render-pass-as-converged)
