### ISSUE TITLE
Don't call AiLoadPlugins in the render delegate / ndr

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#418]
There is no need to call AiLoadPlugins in the render delegate or ndr, calling AiBegin already loads plugins from `ARNOLD_PLUGIN_PATH` and the `plugins` subfolder part of the Arnold SDK.

**Comment by sirpalee** [comment]
I moved loading plugins from HOUDINI_PATH to a separate issue.

**Comment by jhodgson** [comment]
For reference here is the corresponding HtoA ticket: https://trac.solidangle.com/htoa/ticket/1437
