### ISSUE TITLE
Naming for filter parameters

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#437]
We need to prefix the parameter names with the filter name now, since each filter may have a parameter with the same name but a different meaning. 

If we call the parameters arnold:variance:filter_weights instead of arnold:filter_weights and so on, this will allow for filters to create independent parameters.

See htoa ticket 1454

**Comment by sirpalee** [comment]
Note, this is a Houdini specific request, so checking for parameters namespaced with the filter type won't overwrite the current code but complement it.
