### ISSUE TITLE
[Render Delegate] Move houdini shader translation module and LOP .ds files to HtoA

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#44]
Let's move the _husdshadertranslators_ python module, and the _HdArnoldRendererPlugin*.ds_ files to HtoA, and so remove them from the _arnold_usd_ repository.

**Comment by BigRoy** [comment]
Do you have a specific link on where one could test/find this in `HtoA`? Do you currently need to be signed up for beta? Or is it available to give it a test run?
