### ISSUE TITLE
Support horizontalApertureOffset and verticalApertureOffset camera attributes

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#444]
Currently the horizontalApertureOffset and verticalApertureOffset camera attributes coming from  the camera LOP are not used in the Arnold render delegate.

See htoa ticket 1451

**Comment by cpichard** [comment]
Hi @suekieza , we are investigating now, I hope this is still relevant for you.

**Comment by cpichard** [comment]
Similar request here: https://github.com/Autodesk/arnold-usd/issues/1225

**Comment by suekieza** [comment]
yup its still relevant thanks
