### ISSUE TITLE
Build Issue Vtdictonary error: wrong number of template argument

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#455]
**Describe the bug**
Trying to build Arnold USD for Maya, doesn't build.

**To Reproduce**
1.  build usd pxr 20.05
2. download Arnold sdk 6.0.3.0
4. Install Maya 2020.1
3. Try to build

**Expected behavior**
for arnold usd to build correctly
**Terminal dump**
`scons: Reading SConscript files ...
Building Arnold-USD:
 - Build mode: 'profile'
 - Host OS: 'linux'
 - Arnold version: '6.0.3.0'
00:00:00    79MB         | log started Wed Jun  3 11:32:00 2020
00:00:00    79MB         | Arnold 6.0.3.0 [991b08e9] linux clang-9.0.1 oiio-2.2.1 osl-1.11.0 vdb-4.0.0 clm-1.1.1.118 rlm-12.4.2 optix-6.7.0 2020/04/17 09:05:24
00:00:00    79MB         | running on cpv-ws002.za.sunrise.productions, pid=40793
00:00:00    79MB         |  1 x AMD Ryzen Threadripper 2990WX 32-Core Processor (32 cores, 64 logical) with 128686MB
00:00:00    79MB         |  NVIDIA driver version 440.82 (Optix 60600)
00:00:00    79MB         |  GPU 0: GeForce RTX 2080 SUPER @ 1860MHz (compute 7.5) with 7981MB (7528MB available) (NVLink:0)
00:00:00    79MB         |  CentOS Linux 7 (Core), Linux kernel 3.10.0-1127.8.2.el7.x86_64
00:00:00    79MB         |  soft limit for open files raised from 1024 to 4094
00:00:00    79MB         |  
00:00:00    79MB         | loading plugins from /home/sue.sauer/Documents/arnold_run/arnold_sdk/bin/../plugins ...
00:00:00    79MB         | loaded 5 plugins from 3 lib(s) in 0:00.01
00:00:00    79MB         |  
00:00:00    79MB         | releasing resources
00:00:00    79MB         | Arnold shutdown
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/linux_x86_64/gcc_profile/usd-0.20.5_arnold-6.0.3.0/cmd/main.o -c -fno-operator-names -std=c++11 -w -O3 -g -O0 -pg -D_LINUX -I/home/sue.sauer/Documents/arnold_run/arnold_sdk/include -I/home/sue.sauer/Documents/USD/include -I/usr/include -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_profile/usd-0.20.5_arnold-6.0.3.0/cmd -Icmd -Itranslator/writer cmd/main.cpp
In file included from /home/sue.sauer/Documents/USD/include/pxr/usd/sdf/types.h:65:0,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/sdf/abstractData.h:29,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/sdf/data.h:29,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/sdf/layer.h:31,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/schemaRegistry.h:30,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/primDefinition.h:29,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/primData.h:33,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/object.h:32,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/prim.h:32,
                 from translator/writer/writer.h:18,
                 from cmd/main.cpp:17:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:64:53: error: wrong number of template arguments (0, should be 1)
     typedef std::map<std::string, VtValue, std::less<>> _Map;
                                                     ^
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:48:0,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/locale_classes.h:40,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/ios_base.h:41,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/ios:42,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/ostream:38,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/iostream:39,
                 from cmd/main.cpp:15:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/stl_function.h:381:12: note: provided for ‘template<class _Tp> struct std::less’
     struct less : public binary_function<_Tp, _Tp, bool>
            ^~~~
In file included from /home/sue.sauer/Documents/USD/include/pxr/usd/sdf/types.h:65:0,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/sdf/abstractData.h:29,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/sdf/data.h:29,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/sdf/layer.h:31,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/schemaRegistry.h:30,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/primDefinition.h:29,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/primData.h:33,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/object.h:32,
                 from /home/sue.sauer/Documents/USD/include/pxr/usd/usd/prim.h:32,
                 from translator/writer/writer.h:18,
                 from cmd/main.cpp:17:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:64:54: error: template argument 3 is invalid
     typedef std::map<std::string, VtValue, std::less<>> _Map;
                                                      ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:151:19: error: typedef name may not be a nested-name-specifier
     typedef _Map::key_type key_type;
                   ^~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:151:19: error: expected ‘;’ at end of member declaration
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:151:28: error: declaration does not declare anything [-fpermissive]
     typedef _Map::key_type key_type;
                            ^~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:152:19: error: typedef name may not be a nested-name-specifier
     typedef _Map::mapped_type mapped_type;
                   ^~~~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:152:19: error: expected ‘;’ at end of member declaration
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:152:31: error: declaration does not declare anything [-fpermissive]
     typedef _Map::mapped_type mapped_type;
                               ^~~~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:153:19: error: typedef name may not be a nested-name-specifier
     typedef _Map::value_type value_type;
                   ^~~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:153:19: error: expected ‘;’ at end of member declaration
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:153:30: error: declaration does not declare anything [-fpermissive]
     typedef _Map::value_type value_type;
                              ^~~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:154:19: error: typedef name may not be a nested-name-specifier
     typedef _Map::allocator_type allocator_type;
                   ^~~~~~~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:154:19: error: expected ‘;’ at end of member declaration
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:154:34: error: declaration does not declare anything [-fpermissive]
     typedef _Map::allocator_type allocator_type;
                                  ^~~~~~~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:155:19: error: typedef name may not be a nested-name-specifier
     typedef _Map::size_type size_type;
                   ^~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:155:19: error: expected ‘;’ at end of member declaration
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:155:29: error: declaration does not declare anything [-fpermissive]
     typedef _Map::size_type size_type;
                             ^~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:157:43: error: template argument 2 is invalid
     typedef Iterator<_Map*, _Map::iterator> iterator;
                                           ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:158:55: error: template argument 2 is invalid
     typedef Iterator<_Map const*, _Map::const_iterator> const_iterator;
                                                       ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:183:50: error: template argument 1 is invalid
     VtDictionary(std::initializer_list<value_type> init);
                                                  ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:183:5: error: ‘pxrInternal_v0_20__pxrReserved__::VtDictionary::VtDictionary(int)’ cannot be overloaded
     VtDictionary(std::initializer_list<value_type> init);
     ^~~~~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:164:14: error: with ‘pxrInternal_v0_20__pxrReserved__::VtDictionary::VtDictionary(int)’
     explicit VtDictionary(int size) {}
              ^~~~~~~~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h: In member function ‘void pxrInternal_v0_20__pxrReserved__::VtDictionary::insert(_InputIterator, _InputIterator)’:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:285:23: error: request for member ‘insert’ in ‘((pxrInternal_v0_20__pxrReserved__::VtDictionary*)this)->pxrInternal_v0_20__pxrReserved__::VtDictionary::_dictMap->’, which is of non-class type ‘int’
             _dictMap->insert(f, l);
                       ^~~~~~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h: In function ‘bool pxrInternal_v0_20__pxrReserved__::VtDictionaryIsHolding(const pxrInternal_v0_20__pxrReserved__::VtDictionary&, const string&)’:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:384:13: error: base operand of ‘->’ is not a pointer
     return i->second.IsHolding<T>();
             ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:384:33: error: expected primary-expression before ‘>’ token
     return i->second.IsHolding<T>();
                                 ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:384:35: error: expected primary-expression before ‘)’ token
     return i->second.IsHolding<T>();
                                   ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h: In function ‘bool pxrInternal_v0_20__pxrReserved__::VtDictionaryIsHolding(const pxrInternal_v0_20__pxrReserved__::VtDictionary&, const char*)’:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:398:13: error: base operand of ‘->’ is not a pointer
     return i->second.IsHolding<T>();
             ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:398:33: error: expected primary-expression before ‘>’ token
     return i->second.IsHolding<T>();
                                 ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:398:35: error: expected primary-expression before ‘)’ token
     return i->second.IsHolding<T>();
                                   ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h: In function ‘const T& pxrInternal_v0_20__pxrReserved__::VtDictionaryGet(const pxrInternal_v0_20__pxrReserved__::VtDictionary&, const string&)’:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:423:13: error: base operand of ‘->’ is not a pointer
     return i->second.Get<T>();
             ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:423:27: error: expected primary-expression before ‘>’ token
     return i->second.Get<T>();
                           ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:423:29: error: expected primary-expression before ‘)’ token
     return i->second.Get<T>();
                             ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h: In function ‘const T& pxrInternal_v0_20__pxrReserved__::VtDictionaryGet(const pxrInternal_v0_20__pxrReserved__::VtDictionary&, const char*)’:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:438:13: error: base operand of ‘->’ is not a pointer
     return i->second.Get<T>();
             ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:438:27: error: expected primary-expression before ‘>’ token
     return i->second.Get<T>();
                           ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:438:29: error: expected primary-expression before ‘)’ token
     return i->second.Get<T>();
                             ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h: In function ‘T pxrInternal_v0_20__pxrReserved__::VtDictionaryGet(const pxrInternal_v0_20__pxrReserved__::VtDictionary&, const string&, const pxrInternal_v0_20__pxrReserved__::Vt_DefaultHolder<U>&)’:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:482:36: error: base operand of ‘->’ is not a pointer
     if (i == dictionary.end() || !i->second.IsHolding<T>())
                                    ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:482:56: error: expected primary-expression before ‘>’ token
     if (i == dictionary.end() || !i->second.IsHolding<T>())
                                                        ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:482:58: error: expected primary-expression before ‘)’ token
     if (i == dictionary.end() || !i->second.IsHolding<T>())
                                                          ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:484:13: error: base operand of ‘->’ is not a pointer
     return i->second.UncheckedGet<T>();
             ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:484:36: error: expected primary-expression before ‘>’ token
     return i->second.UncheckedGet<T>();
                                    ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:484:38: error: expected primary-expression before ‘)’ token
     return i->second.UncheckedGet<T>();
                                      ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h: In function ‘T pxrInternal_v0_20__pxrReserved__::VtDictionaryGet(const pxrInternal_v0_20__pxrReserved__::VtDictionary&, const char*, const pxrInternal_v0_20__pxrReserved__::Vt_DefaultHolder<U>&)’:
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:494:36: error: base operand of ‘->’ is not a pointer
     if (i == dictionary.end() || !i->second.IsHolding<T>())
                                    ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:494:56: error: expected primary-expression before ‘>’ token
     if (i == dictionary.end() || !i->second.IsHolding<T>())
                                                        ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:494:58: error: expected primary-expression before ‘)’ token
     if (i == dictionary.end() || !i->second.IsHolding<T>())
                                                          ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:496:13: error: base operand of ‘->’ is not a pointer
     return i->second.UncheckedGet<T>();
             ^~
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:496:36: error: expected primary-expression before ‘>’ token
     return i->second.UncheckedGet<T>();
                                    ^
/home/sue.sauer/Documents/USD/include/pxr/base/vt/dictionary.h:496:38: error: expected primary-expression before ‘)’ token
     return i->second.UncheckedGet<T>();
                                      ^
scons: *** [build/linux_x86_64/gcc_profile/usd-0.20.5_arnold-6.0.3.0/cmd/main.o] Error 1
scons: building terminated because of errors.
`

**Used Software Versions**
 - Arnold: 6.0.3.0
 - USD: 20.05
 - Compiler: gcc 6.3.1
 - OS: Linux 7.7
 - Any 3rd-party app: Maya 2020.1

Tried both:
branch fix-6.0.3 3b18972bac7cee2e1d4d33dc778995a1c5b40a30
and master branch commit cea93ef989f8bf29f43597aa36ae390af445d0e2

both give the same result.

**Additional context**
Houdini builds fine.

**Comment by sirpalee** [comment]
You need to pass 'CXX_STANDARD=14' when building arnold-usd for Maya, and make sure the appropriate compiler is used (gcc 6.3.1). You can do so by setting the SHCXX scons parameter.

**Comment by suesauer** [comment]
Thanks, Pal. Trying that now.

**Comment by suesauer** [comment]
Looks all good thanks for the help :D
