### ISSUE TITLE
Point instancer should prune the primitives under its hierarchy

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#458]
**Describe the bug**
In usdview / hdstorm, a primitive below the hierarchy of a point instancer is hidden. 
This should be ported to the procedural, which is currently consider the actual visibility of each primitive.

**Comment by frenchdog** [comment]
@sebastienblor if I remember correctly, primitives bellow a point instancer are ignored by UsdImaging if they are bellow a parent of type "over". This behaviour is working as expected in HdArnold, so for consistency, the same logic should be used when rendering USD file directly in Arnold.
