### ISSUE TITLE
GeomSubset Material bindings not working in Arnold Delegate

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#460]
**Describe the bug**
Arnold delegate seems to not be working with Material bindings to Geomsubsets in Houdini 18.0.348

**To Reproduce**
1.  Assign shaders to GeomSubsets
2. Try to render with Arnold delegate

**Expected behavior**
To behave like Karma does in the example video below

**Screenshots**
Example:
[2020-06-11 10-58-44.zip](https://github.com/Autodesk/arnold-usd/files/4763813/2020-06-11.10-58-44.zip)

**Used Software Versions**
 - Arnold: 6.0.3.0
 - USD: 0.19.11
 - Compiler: GCC 6.3.1
 - OS: Linux Centos 7.7
 - Any 3rd-party app: Houdini 18.0.348

**Additional context**

**Comment by sirpalee** [comment]
Hi Sue,

this is a known limitation. We already have a ticket for this #29 so I'm going to close this as a duplicate.

**Comment by suesauer** [comment]
Great thanks :D/
