### ISSUE TITLE
Building against 20.08 and latest SDK

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#477]
**Describe the bug**
Arnold delegate doesnt build against 20.08

**To Reproduce**
1.  build USD 20.08
2. Try to build Arnold delegate with sdk 6.0.3.1

**Expected behavior**
for arnold delegate to build

**Screenshots**
`Install file: "build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/schemas/_usdArnold.so" as "/home/sue.sauer/Documents/Maya_arnold-usd/lib/python/UsdArnold/_usdArnold.so"
Install file: "plugInfo.json" as "/home/sue.sauer/Documents/Maya_arnold-usd/lib/usd/plugInfo.json"
Install file: "build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/schemas/source/generatedSchema.usda" as "/home/sue.sauer/Documents/Maya_arnold-usd/lib/usd/usdArnold/resources/generatedSchema.usda"
Install file: "build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/schemas/source/plugInfo.json" as "/home/sue.sauer/Documents/Maya_arnold-usd/lib/usd/usdArnold/resources/plugInfo.json"
Install file: "build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/schemas/schema.usda" as "/home/sue.sauer/Documents/Maya_arnold-usd/lib/usd/usdArnold/resources/usdArnold/schema.usda"
Install file: "render_delegate/plugInfo.json" as "/home/sue.sauer/Documents/Maya_arnold-usd/plugin/hdArnold/resources/plugInfo.json"
g++ -o build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate/config.os -c -fPIC -fno-operator-names -std=c++14 -w -O3 -g -O0 -pg -fPIC -D_LINUX -DUSD_HAS_FULLSCREEN_SHADER -DHDARNOLD_EXPORTS -I/home/sue.sauer/Documents/arnold_run/arnold_sdk/include -I/home/sue.sauer/Documents/USD/include -I/usr/include -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate -Irender_delegate render_delegate/config.cpp
g++ -o build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate/constant_strings.os -c -fPIC -fno-operator-names -std=c++14 -w -O3 -g -O0 -pg -fPIC -D_LINUX -DUSD_HAS_FULLSCREEN_SHADER -DHDARNOLD_EXPORTS -I/home/sue.sauer/Documents/arnold_run/arnold_sdk/include -I/home/sue.sauer/Documents/USD/include -I/usr/include -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate -Irender_delegate render_delegate/constant_strings.cpp
g++ -o build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate/debug_codes.os -c -fPIC -fno-operator-names -std=c++14 -w -O3 -g -O0 -pg -fPIC -D_LINUX -DUSD_HAS_FULLSCREEN_SHADER -DHDARNOLD_EXPORTS -I/home/sue.sauer/Documents/arnold_run/arnold_sdk/include -I/home/sue.sauer/Documents/USD/include -I/usr/include -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate -Irender_delegate render_delegate/debug_codes.cpp
g++ -o build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate/instancer.os -c -fPIC -fno-operator-names -std=c++14 -w -O3 -g -O0 -pg -fPIC -D_LINUX -DUSD_HAS_FULLSCREEN_SHADER -DHDARNOLD_EXPORTS -I/home/sue.sauer/Documents/arnold_run/arnold_sdk/include -I/home/sue.sauer/Documents/USD/include -I/usr/include -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate -Irender_delegate render_delegate/instancer.cpp
g++ -o build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate/light.os -c -fPIC -fno-operator-names -std=c++14 -w -O3 -g -O0 -pg -fPIC -D_LINUX -DUSD_HAS_FULLSCREEN_SHADER -DHDARNOLD_EXPORTS -I/home/sue.sauer/Documents/arnold_run/arnold_sdk/include -I/home/sue.sauer/Documents/USD/include -I/usr/include -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate -Irender_delegate render_delegate/light.cpp
g++ -o build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate/material.os -c -fPIC -fno-operator-names -std=c++14 -w -O3 -g -O0 -pg -fPIC -D_LINUX -DUSD_HAS_FULLSCREEN_SHADER -DHDARNOLD_EXPORTS -I/home/sue.sauer/Documents/arnold_run/arnold_sdk/include -I/home/sue.sauer/Documents/USD/include -I/usr/include -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate -Irender_delegate render_delegate/material.cpp
g++ -o build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate/mesh.os -c -fPIC -fno-operator-names -std=c++14 -w -O3 -g -O0 -pg -fPIC -D_LINUX -DUSD_HAS_FULLSCREEN_SHADER -DHDARNOLD_EXPORTS -I/home/sue.sauer/Documents/arnold_run/arnold_sdk/include -I/home/sue.sauer/Documents/USD/include -I/usr/include -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate -Irender_delegate render_delegate/mesh.cpp
render_delegate/mesh.cpp: In member function ‘virtual void pxrInternal_v0_20__pxrReserved__::HdArnoldMesh::Sync(pxrInternal_v0_20__pxrReserved__::HdSceneDelegate*, pxrInternal_v0_20__pxrReserved__::HdRenderParam*, pxrInternal_v0_20__pxrReserved__::HdDirtyBits*, const pxrInternal_v0_20__pxrReserved__::TfToken&)’:
render_delegate/mesh.cpp:205:95: error: ‘struct pxrInternal_v0_20__pxrReserved__::PxOsdOpenSubdivTokens_StaticTokenType’ has no member named ‘catmark’; did you mean ‘catmullClark’?
         if (scheme == PxOsdOpenSubdivTokens->catmullClark || scheme == PxOsdOpenSubdivTokens->catmark) {
                                                                                               ^~~~~~~
scons: *** [build/linux_x86_64/gcc_profile/usd-0.20.8_arnold-6.0.3.1/render_delegate/mesh.os] Error 1
scons: building terminated because of errors.
`

**Used Software Versions**
 - Arnold:  6.0.3.1
 - USD:  20.08
 - Compiler: GCC 6.3.1
 - OS:  Centos 7.7
 - Any 3rd-party app: Maya,Houdini

**Additional context**
Built delegate fine against Houdini 18.0.499(USD 19.11), Trying to build delegate against USD 20.08 for Maya 2020 doesn't work

Thanks Sue

**Comment by sirpalee** [comment]
Thank you for reporting this! This is fixed in #479
