### ISSUE TITLE
Building against Houdini Libraries

### ISSUE THREAD

**Issue by Tuftux** [Autodesk/arnold-usd#48]
Hi !

Amazing to see this repo go live !
I've been successfully able to compile against Houdini's shipped libraries with a few modifications and was wondering if these could become part of the main build system.

First, USD libs in Houdini have the libpxr_ prefix, so it would be nice to have a build option like BOOST_LIB_NAME for USD.
Second, it seems like the USD_HAS_UPDATED_COMPOSITOR doesn't set correctly when building against Houdini's USD libs. Setting it up manually has fixed it in my experience.

Thanks !

**Comment by sirpalee** [comment]
Hey!

You can already build parts of the repository for Houdini 18 (and prior). Here is my example custom.py setting the build up:

```
COMPILER='gcc'
ARNOLD_PATH='...'

USD_PATH='./'
USD_BIN='./'
USD_INCLUDE='/opt/hfs18.0/toolkit/include'
USD_LIB='/opt/hfs18.0/dsolib'
USD_LIB_PREFIX='libpxr_'
USD_1910_UPDATED_COMPOSITOR=True

PREFIX='...'

BOOST_INCLUDE='/opt/hfs18.0/toolkit/include/hboost'
BOOST_LIB='/opt/hfs18.0/dsolib'
BOOST_PREFIX='hboost_'

PYTHON_INCLUDE='/usr/include/python2.7'
PYTHON_LIB='/usr/lib'
PYTHON_LIB_NAME='python2.7'

USD_BUILD_MODE='shared_libs'

DISABLE_CXX11_ABI=True
BUILD_SCHEMAS=False
BUILD_RENDER_DELEGATE=True
BUILD_NDR_PLUGIN=True
BUILD_PROCEDURAL=False
BUILD_TESTSUITE=False
BUILD_USD_WRITER=False
BUILD_HOUDINI_TOOLS=True
BUILD_DOCS=True
```

**Comment by Svenito** [comment]
It should be rather simple if those components also respected `USD_LIB_PREFIX`. I ended up having to add

```
try:
    usd_deps = [env['USD_LIB_PREFIX']+x for x in usd_deps]
except KeyError:
    pass
```

to the SConscript files in `procedural` and `cmd`

**Comment by sirpalee** [comment]
@Svenito that's not going to be a universal solution. If USD_LIB_PREFIX does not start with 'lib' the libraries won't build.

Here is some ongoing work for the issue: sirpalee/arnold-usd@e035fc4d67f73e853052848098d6d5de70fc28a8 . It's not yet ready for a PR; I need to support the static/monolithic cases and do some tests.

**Comment by Svenito** [comment]
Seems to work for me for now, as the compiler will prefix the `lib` component automatically.

good to see something better in the pipe though
