### ISSUE TITLE
Add a schema for custom procedurals

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#487]
Today we have a schema `ArnoldProcedural` for the arnold node `procedural` (loading .ass files), as well as `ArnoldAlembic` and `ArnoldUsd`. 
But if a studio uses a custom procedural, they would need to define a new usd schema for their specific arnold node.

It could make more sense to define a schema `ArnoldCustomProcedural` with a token that determines what the arnold node type is, in a very similar way to what `UsdShade` does for shaders. So for a procedural called "myProc", instead of having a primitive `ArnoldMyProc`, we would have a primitive `ArnoldCustomProcedural` with an attribute  `nodeType = "myProc"`

**Comment by kikou** [comment]
The name should be `ArnoldProceduralCustom`.
