### ISSUE TITLE
Add support for using a USD build with Python 3

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#509]
**Describe the feature you'd like**
Add support for using a USD with Python 3. At the moment all the build scripts, both scons, and cmake are looking for python 2.7 modules.

**Additional context**
I'm not planning to update scons, as we are on the track of moving over to cmake.

**Comment by sirpalee** [comment]
@furby-tm what components are you planning to use? It's already possible to override the python library's name when linking, so you could still build most of the components with python 2, but link against python 3.

**Comment by furby-tm** [comment]
Hmm, well currently I cannot seem to get it to build

**Comment by furby-tm** [comment]
The delegate is great, interactive, and easy to use on Linux -- however it crashes on windows. Any ideas?

**Comment by sirpalee** [comment]
Hey!

Both HtoA and KtoA includes a build of this repository, so it is exactly the same code. About the schema builds, you can disable building the schemas by passing `BUILD_SCHEMAS` to abuild. The procedural, render delegate and the ndr plugin should work without them.

About the crash on windows, is there a way we can reproduce it on our side? Could you please create a separate ticket for it?

**Comment by furby-tm** [comment]
I have created a new ticket for this [issue](https://github.com/Autodesk/arnold-usd/issues/622#issue-765457177). Perhaps the delegate works from the `hdx` api on windows, but not the `UsdImagingGLEngine` api on windows?

**Comment by BigRoy** [comment]
Is this issue still relevant?

This looks similar to this https://github.com/Autodesk/arnold-usd/issues/767 which is resolved with https://github.com/Autodesk/arnold-usd/pull/781 about three years ago.

A lot of applications using Arnold-USD are also already Py3 so I assume the current state is perfectly ready for Python 3. If so, we can close this issue.

**Comment by cpichard** [comment]
Thanks @BigRoy . Closing as we now build with python 3.
