### ISSUE TITLE
AV in createSchemaFile.py

### ISSUE THREAD

**Issue by trebconnell** [Autodesk/arnold-usd#536]
**Describe the bug**
After Arnold is initialized by createSchemaFile.py I get an AV, logs below.
I can assist with debugging here, but unsure how, so if there're any suggestion let me know.  I have ensured there are no issues loading dlls.

**To Reproduce**
I ran cmake with following environment variables set:
```
"USD_LOCATION": "{usd build dir}",
"ARNOLD_LOCATION": "{Arnold-6.0.4.0-windows}",
"BOOST_ROOT": "${env.USD_LOCATION}",
"TBBROOT": "${env.USD_LOCATION}",
"TBB_INSTALL_DIR": "${env.USD_LOCATION}/lib"
```

and following cmake vars:
```
BUILD_SHARED_LIBS = On
BUILD_DOCS = Off
```

**Expected behavior**
CMake Generation

**Used Software Versions**
 - Arnold: 6.0.4.0 (also tried 6.0.3.0)
 - USD: 20.08
 - Compiler: CMake/VS2019
 - OS: Win 10

**Additional context**
Relevant Logs:

I tried removing usd_proc.dll plugin, but still hit same AV
```
log started Wed Sep 16 11:52:08 2020
Arnold 6.0.4.0 [3fad32b9] windows icc-17.0.2 oiio-2.2.1 osl-1.11.6 vdb-4.0.0 clm-1.1.1.118 rlm-12.4.2 optix-6.6.0 2020/07/31 08:11:38
running on treb-dev, pid=49692
 1 x Intel(R) Core(TM) i9-7920X CPU @ *
 NVIDIA driver version 452.6 (Optix 60600)
 GPU 0: GeForce RTX 2080 Ti @ 1545MHz (compute 7.5) with 11264MB (8928MB available) (NVLink:0)
 
 soft limit for open files raised from 512 to 2048
 
loading plugins from C:\Users\treborc\Downloads\Arnold-6.0.4.0-windows\bin\..\plugins ...
 alembic_proc.dll: alembic uses Arnold 6.0.4.0
 cryptomatte.dll: cryptomatte uses Arnold 6.0.4.0
 cryptomatte.dll: cryptomatte_filter uses Arnold 6.0.4.0
 cryptomatte.dll: cryptomatte_manifest_driver uses Arnold 6.0.4.0
 usd_proc.dll: usd uses Arnold 6.0.4.0
loaded 5 plugins from 3 lib(s) in 0:00.18
signal caught: error C0000005 -- access violation

****
* Arnold 6.0.4.0 [3fad32b9] windows icc-17.0.2 oiio-2.2.1 osl-1.11.6 vdb-4.0.0 clm-1.1.1.118 rlm-12.4.2 optix-6.6.0 2020/07/31 08:11:38
* CRASHED in DllCanUnloadNow at 00:00:00
* signal caught: error C0000005 -- access violation
*
* backtrace:
*  0 0x00007ffe9fc2f66e [ai        ]                           
*  1 0x00007ffe9fc2e83f [ai        ]                           
*  2 0x00007fff38b4b8b7 [KERNELBASE] UnhandledExceptionFilter  
*  3 0x00007fff3b0749b3 [ntdll     ] memset                    
*  4 0x00007fff3b05b766 [ntdll     ] _C_specific_handler       
*  5 0x00007fff3b07111f [ntdll     ] _chkstk                   
*  6 0x00007fff3b01b474 [ntdll     ] RtlRaiseException         
*  7 0x00007fff3b06fc4e [ntdll     ] KiUserExceptionDispatcher 
>> 8 0x00007fff1b0fec93 [_ctypes   ] DllCanUnloadNow           
*
* loaded modules:
*    0x00007ffe9f870000  ai
*    0x00007fff38a40000  KERNELBASE
*    0x00007fff3afd0000  ntdll
*    0x00007fff1b0f0000  _ctypes
****
Access violation
```

**Comment by sirpalee** [comment]
Hey! I wasn't able to reproduce the crash on Winodws.

I assume you are running the cmake generation from the terminal, can you share your environment variables with me? There might be something in the PATH or some Arnold specific value that's causing the crash.

**Comment by mwkm** [comment]
I share the same experience when building with USD 21.08 with Python 3.7 on Win64.  In my case, it was solved by patching <code>'schema/createSchemaFile.py'</code> line no. 109:

Replace:
<code>if t is None:</code>
with
<code>if t == '':</code>

the crash was apparently caused by an out-of-bound index <code>i</code> being sent to line no. 108
<code>t = ai.AiEnumGetString(paramEnum, i)</code>
because line no. 109 could not reliably terminate the <code>while True:</code> loop in Python 3.X
