### ISSUE TITLE
USD asset doesnt have any shaders attached to the material prim.

### ISSUE THREAD

**Issue by foundryskit** [Autodesk/arnold-usd#547]
On export the USD asset, I do see a material prim on the asset but there are no shaders attached to it. So the material binding appears to work but the shaders are not included in the exported USD file. 

Here's an example of the exported USD file. 

```
def Scope "Looks"
    {
        def Material "aiStandardSurface1SG"
        {
        }
    }
```

Am I missing a step here? I didn't get any errors while building the render delegate. Any help appreciated.

**Comment by sebastienblor** [comment]
How was this scene exported ? if it comes from the arnold menus to export to USD, this shouldn't happen and we'd need a repro.

But if it comes from the maya USD exporter, this is expected. Currently, maya USD will not export any of the arnold shaders as it doesn't know how to translate them to USD. This is currently being worked on, and the work for that is happening in the MtoA repository.

**Comment by sebastienblor** [comment]
Closing as this was clearly related to mayaUSD exports.There are now options to export the arnold shaders through mayaUSD exports
