### ISSUE TITLE
Handle metadata in the Ndr plugin and store arnold specific metadata

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#55]
We should handle arnold metadata and store additional information in the ndr plugins.

This include:
- metadata on arnold nodes
- metadata on arnold parameters
- metadata storing the arnold type of the parameter (there are arnold types that map to the same sdf type)

**Describe the solution you'd like**
We need to extend `ndr/utils.cpp` to deal with metadata. Add additional USD metadata to store the raw arnold type on the primitives in the Usd Stage returned by `NdrArnoldGetShaderDefs`. And pass metadata to Usd in the Discovery and Parser plugins.

**Comment by JGamache-autodesk** [comment]
For reference: MaterialX metadata transfer to Sdr has been submitted as https://github.com/PixarAnimationStudios/USD/pull/1895 following discussions in https://github.com/PixarAnimationStudios/USD/issues/1874.
