### ISSUE TITLE
Aces colorspace conversion using the hair shader

### ISSUE THREAD

**Issue by janikotterbach** [Autodesk/arnold-usd#562]
Hey everyone, 

I am using the Htoa Plugin 5.4.0 (Arnold 6.0.4.0, Arnold-USD 6b712999b241a86bd80bac5c704d8c94bc82e2e8)
with Houdini 18.0.566 on Windows. 
I configured Houdini with OCIO to use ACES. 
I noticed some unpredicted behaviour when it comes to colorspace conversion using the Hair Shader.

Using the same Hair Shader in USD (Solaris) and outside of Solaris I get different results:

![grafik](https://user-images.githubusercontent.com/54793617/94916998-ffa93800-04af-11eb-8795-58c305905ecf.png)
The upper image is rendered inside of Solaris using the Hydra Render Delegate.

![grafik](https://user-images.githubusercontent.com/54793617/94916859-be188d00-04af-11eb-9cf4-910240fb2628.png)
The upper image is rendered outside of Solaris. 

I noticed that I get the same result as in Solaris when I switch the Render Colorspace from ACES CG to linear sRGB. 

To me it seems like some parameters on the HairShader are not converted correctly. 

Also I dont know if this is related, but I still get the same warnings as mentioned here #82 .

**Comment by podorvan** [comment]
Hey guys, in our studio we have the same issue. It seems like in arnold materialbuilder we are not able to perform any color conversion in node "Image".

**Comment by janikotterbach** [comment]
I have figured out that this issue boils down to the melanin parameter. 
It seems like the color value derived by the melanin parameter is not converted correctly to the the render colorspace using the Render Delegate. 
Disabling melanin by setting it to zero and only using the color parameter works fine.

**Comment by AdrienHerubel** [comment]
We improved support for Standard Hair Melanin and Redness in Arnold 7.1.4, it should now perform much better. See https://help.autodesk.com/view/ARNOL/ENU/?guid=arnold_core_7140_html
