### ISSUE TITLE
Test the j-cube USD assets

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#563]
**Describe the feature you'd like**
We should check [the example USD assets from j-cube](https://j-cube.jp/solutions/multiverse/assets/) and test if everything appears as it should in the Render Delegate and Procedural.

**Comment by sirpalee** [comment]
I started testing the scenes in Solaris.

- `Maneki USDZ for AR` does not load textures, we are missing a feature to use textures from usdz files. See #70 
- `Maneki USD Static Model` works as expected.
![image](https://user-images.githubusercontent.com/582376/95452008-56cd7200-09b4-11eb-8496-2f35b8304934.png)
- `Maneki USD Animated Model` works as expected, including motion blur.
![image](https://user-images.githubusercontent.com/582376/95451927-3a313a00-09b4-11eb-9d59-e78fe6443de1.png)


`Esper Room USD Composition`: This is a bit trickier as the scene does not fully follow the USD standards, so we can't render it directly.
- Material assignments are done via 'multiverse:material' which does not work with Solaris by default.
- Lights are using an incorrect prim type name `UsdLuxRectLight` instead of `RectLight`.
The rest of the elements showed up correctly, but I noticed some oddities with normals, which require some more testing.

**Comment by sebastienblor** [comment]
Tried with the procedural,
↕`Maneki USD Static` works out of the box : 
![maneki_v3 jog](https://user-images.githubusercontent.com/13153907/109985281-e2012880-7d04-11eb-8e5b-726c4d471f62.JPG)

`Maneki animated model` also works with the proper textures : 
![maneki_anim](https://user-images.githubusercontent.com/13153907/109985371-fb09d980-7d04-11eb-8e8d-0f1ecc048e58.jpg)

`Esper Room` also works except for the lights which have an incorrect prim type (see above with the render delegate results).
The materials do show properly, as opposed to the delegate which is limited by hydra.
![esper_room_v3](https://user-images.githubusercontent.com/13153907/109985595-3a382a80-7d05-11eb-828d-72ca956f82aa.jpg)

The USDZ file doesn't work, which is a known limitation

**Comment by sebastienblor** [comment]
Since the purpose of this ticket was to check these usd scenes on both the delegate and the procedural, I will close this ticket now.
