### ISSUE TITLE
Changing topology 

### ISSUE THREAD

**Issue by kreppene** [Autodesk/arnold-usd#564]
**Describe the bug**
When rendering a prim with changing topology,  only the first frame of the usd file works, 
on other frames i get messages like this
 Error: [polymesh] p_liquidMilk_001/p_liquidMilk_001Shape: wrong number of vertex indices (found 189872, expected 200200) // 

we should also make sure we use velocities when avalible

**To Reproduce**
Try rendering different frames of a usd file with changing topology, 

**Used Software Versions**
 - Arnold: 6.0.4.0
 - USD: 0.20.05
 - Compiler: vs
 - OS: Windows 10

**Comment by bsilvaAX** [comment]
Hello! To clarify, does this only apply to a monolithic USD file? i.e. if we were to split this into per-frame files, this error could be avoided?

**Comment by sebastienblor** [comment]
> Hello! To clarify, does this only apply to a monolithic USD file? i.e. if we were to split this into per-frame files, this error could be avoided?

possibly yes, but then you'd be missing motion  blur on these geometries. What we need to do is to read the velocities when they're present, and in this case we shouldn't try to look at how the topology changes.

Maybe we could check if the topology changes, and in this case we would only use static data. Not having motion blur might be better than not being able to render at all

**Comment by bsilvaAX** [comment]
Ah, thanks! I see velocity motion blur is also on the to-do list.

I agree that it would be better to have the cache render w/o motion blur than not at all. But of course, supporting changing topology and velocity motion blur is vital for FX work.

**Comment by jhodgson** [comment]
Example file with changing topology

[test.usd_rop1.usda.zip](https://github.com/Autodesk/arnold-usd/files/6050208/test.usd_rop1.usda.zip)
