### ISSUE TITLE
strange issue with arnold_usd

### ISSUE THREAD

**Issue by dietchmatch** [Autodesk/arnold-usd#573]
**Describe the bug**
We have some problems with our own compiled arnold_usd procedural inside maya
When we open maya, it complains with the following:

> Coding Error: in _DefineCppType at line 947 of X:\pixar_usd\pxr\base\tf\type.cpp -- TfType 'UsdRenderProduct' already has a defined C++ type; cannot redefine
> Coding Error: in _DefineCppType at line 947 of X:\pixar_usd\pxr\base\tf\type.cpp -- TfType 'UsdRenderSettings' already has a defined C++ type; cannot redefine
> Coding Error: in _DefineCppType at line 947 of X:\pixar_usd\pxr\base\tf\type.cpp -- TfType 'UsdRenderSettingsAPI' already has a defined C++ type; cannot redefine
> Coding Error: in _DefineCppType at line 947 of X:\pixar_usd\pxr\base\tf\type.cpp -- TfType 'UsdRenderSettingsBase' already has a defined C++ type; cannot redefine

and we can't load our usd procedurals with alembic inside properly

**we've managed to solved this by doing**
`import pxr
import pxr.UsdRender`
just before loading mtoa

**To Reproduce**
1. We Have compiled pixar_usd ( **with alembic support** ), maya_usd against that and arnold_usd against that too
No fancy things, just followed compile-install instructions on all repos.
2. removed usd_proc.dll and usd folder from both mtoa installation and arnold_core

**Expected behavior**
Should load without problems

**Used Software Versions**
 - Arnold: 6.0.4.0
 - USD: 0.20.08, 0.19.11
 - Compiler: visual studio 2017
 - OS: windows
 - Any 3rd-party app: 

**Additional context**
Been checking this issue with Pal on slack for a while

**Comment by kikou** [comment]
After investigation, this turned out to be a build issue.
