### ISSUE TITLE
Arnold shader Network edit not working between maya/houdini

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#587]
Hey there,

**Describe the bug**
We are having issues editing shader networks that are saved out of Maya Arnold to Houdini. Please see attached videos

**To Reproduce**
1.  Export shader network with usdmaya out of Maya, import into Houdini try to edit.

**Expected behavior**
As shown in this video: 
[USD shaders network edit.zip](https://github.com/Autodesk/arnold-usd/files/5493205/USD.shaders.network.edit.zip)

Behavior we are getting that is not as expected:
[arnold shaders network edit.zip](https://github.com/Autodesk/arnold-usd/files/5493213/arnold.shaders.network.edit.zip)

**Used Software Versions**
 - Arnold: MtoA 4.1.0.  HtoA 5.5.0.0. SDK is 6.1.0.0.
 - USD: [e.g. 20.11]
 - Compiler: [e.g. GCC6.3.1]
 - OS: [e.g. linux centos7]
 - Any 3rd-party app: [e.g. Maya 2020.2, Houdini 18.5.351]

Thanks Sue

**Comment by sebastienblor** [comment]
Hi Sue, 
I'm sorry, I don't understand what the videos are showing exactly.
You say that you're saving arnold shaders out of maya-usd, but this is not supported yet (it's being worked on right now).
So if you export something from mayaUSD's export, you shouldn't have any shader in the usd file. 
Could you give us more details about that step and how you export from Maya ? a resulting usd file would be helpful too.

Currently, the best way to export arnold shaders from maya is to use the arnold menu "Arnold-> Scene -> Export to USD" (which is different from the maya usd one).
