### ISSUE TITLE
Have a merge transform with Shape option like in maya usd

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#607]
**Describe the feature you'd like**

Could we have an option to merge the transform and shape node like we have in mayausd?

![mergeshape](https://user-images.githubusercontent.com/58251706/100743725-6336df80-33e5-11eb-8283-b276ad519916.png)

**Describe the solution you'd like**

Something like maya usd has would be great

**Additional context**
https://drive.google.com/file/d/1Zdj8EkEMbbLy3Cir31DSCe5g4K3eqrNv/view?usp=sharing

Thanks Sue

**Comment by sebastienblor** [comment]
That's a great option to add, and it could even become the new default. This actually needs to be implemented on the MtoA side, because it all depends on how MtoA names out the arnold nodes. I have created a MtoA ticket #4442 for that.

**Comment by sebastienblor** [comment]
This was implemented in MtoA, with the option "Export Dag Name" in "System". By setting it to "Transform" the exported name of the geometries will be the transform name, which will produce the same result as mayaUSD's option. I'll close this ticket

![exportDagName](https://user-images.githubusercontent.com/13153907/109975474-f4766480-7cfa-11eb-972c-3d5c8324a089.jpg)
