### ISSUE TITLE
Windows Crash: When selecting Arnold as a Hydra Delegate

### ISSUE THREAD

**Issue by furby-tm** [Autodesk/arnold-usd#622]
When selecting Arnold as a Hydra delegate, running through the same plugin selection process as Embree, Renderman, and Storm, the following is where the arnold delegate crashes the client application:

```
m_engine->SetRendererPlugin(m_renderer)
```

* `m_engine` referring to `UsdImagingGLEngine`.
* `m_renderer` referring to `"HdArnoldRendererPlugin"`.

At first I thought it was a issue regarding USD being built as a monolithic build, as lots of plugins just give back unexpected behavior and act oddly with this build option set. However, even when everything is compiled as separate shared USD libraries (pretty much the only stable way to run things on windows at the moment) - I receive the same behavior, the Arnold delegate crashes at that line of code on Windows every time.

The only insight I have currently is the following coding errors reported from USD upon registering of the `usdArnold` ("core plugin") and the `hdArnold`, `ndrArnold`, and `usdImagingArnold` ("imaging plugins"):

```bash
Coding Error (secondary thread): in _InstantiateParserPlugins at line 858 of C:\xyz\dev\USD\pxr\usd\ndr\registry.cpp -- Failed verification: ' pluginFactory '

Coding Error (secondary thread): in _FindAndInstantiateDiscoveryPlugins at line 822 of C:\xyz\dev\USD\pxr\usd\ndr\registry.cpp -- Failed verification: ' pluginFactory '
```

Note: On Linux, this is not an issue. The Arnold Hydra Delegate spools up and behaves as expected, and does not have the above warnings.

**Comment by sirpalee** [comment]
Hey! Have you seen this behavior in any of the applications that use Hydra? Usdview, Usdrecord, Maya, Houdini, or Katana? If not, could you share a simple code that reproduces the problem? Either C++ or Python.

One thing I can imagine is how the Ndr plugin creates an Arnold universe, and maybe it overlaps with the one created by the render delegate. You could try forcing our ndr plugin to run before creating setting the renderer plugin by listing the Arnold shaders using the USD shader registry.

**Comment by furby-tm** [comment]
Now that you mention it, I believe I experienced a similar crashing situation with Houdini.

Let me try that with `ndr`. Presumably you mean listing the arnold shaders like so?:
```cpp
NdrStringVec shaders = NdrRegistry::GetInstance().GetNodeNames();
for(auto shader = shaders.cbegin(); shader != shaders.cend(); ++shader)
{
  printf("\nDEBUG PLUGINS: LIST SHADERS\n");
  printf("* %s\n", shader->c_str());
}

m_engine->SetRendererPlugin(m_renderer);
```

If this doesn't work I'll create a simple C++ program for you to reproduce the crash.

**Comment by sirpalee** [comment]
Yes, I believe this should trigger our plugin. Or the other approach is to query the SdrRegistry, and just `GetShaderNodeByIdentifier("arnold:standard_surface")`.

**Comment by furby-tm** [comment]
Would you also be able to tell me a proper linking workflow with the delegate? I simply treat the delegate as I do the rest of the USD libraries and it looks like the following:

```cmake
# The following is all linked with
# the client application's libraries
# that depend on USD:
set(USD_LIBRARIES
  ${LIBDIR}/usd/lib/ar.lib
  ${LIBDIR}/usd/lib/arch.lib
  ${LIBDIR}/usd/lib/cameraUtil.lib
  ${LIBDIR}/usd/lib/embree3.lib
  ${LIBDIR}/usd/lib/garch.lib
  ${LIBDIR}/usd/lib/gf.lib
  ${LIBDIR}/usd/lib/glf.lib
  ${LIBDIR}/usd/lib/hd.lib
  ${LIBDIR}/usd/lib/hdPrman.lib
  ${LIBDIR}/usd/lib/hdSt.lib
  ${LIBDIR}/usd/lib/hdx.lib
  # ALL THE REST OF THE USD LIBRARIES
  # ...

  # Not yet tested, however,
  # it could allow users the ease
  # of needing to set `ARNOLD_HOME`
  ${LIBDIR}/arnold/lib/ai.lib

  # These libraries get treated like the rest of
  # USD's libraries.
  ${LIBDIR}/arnold-usd/procedural/usd_proc.lib
  ${LIBDIR}/arnold-usd/lib/usdArnold.lib
)

# ...

# These get installed into the
# client applications `bin` dir
# so they are resolved at
# runtime.

install(FILES
  # All USD Libraries
  ${LIBDIR}/usd/lib/ar.dll
  ${LIBDIR}/usd/lib/arch.dll
  ${LIBDIR}/usd/lib/cameraUtil.dll
  ${LIBDIR}/usd/lib/garch.dll
  ${LIBDIR}/usd/lib/gf.dll
  ${LIBDIR}/usd/lib/glf.dll
  ${LIBDIR}/usd/lib/hd.dll
  ${LIBDIR}/usd/lib/hdPrman.dll
  ${LIBDIR}/usd/lib/hdSt.dll
  ${LIBDIR}/usd/lib/hdx.dll
  # ALL THE REST OF THE USD LIBRARIES
  # ...
  # Arnold USD runtime libraries...
  ${LIBDIR}/arnold/bin/ai.dll
  ${LIBDIR}/arnold-usd/procedural/usd_proc.dll
  ${LIBDIR}/arnold-usd/lib/usdArnold.dll
  # etc... Hydra delegate, arnold/bin, all plugins, etc.
  ```
And all `plugInfo.json` file's library paths are adjusted to point here to the `bin` directory. I have not noticed any improper behavior in USD's API or any of it's plugins within an installation architecture such as this - I just want to ensure this installation configuration is suitable for the Arnold USD components as well.

**Comment by sirpalee** [comment]
If you are just using hydra to load the Arnold render delegate you don't have to link any of the Arnold libraries to your application, simply make sure ai.dll is in the PATH, and put the plugInfo.json next to hdArnold and ndrArnold in PXR_PlUGINPATH_NAME. There is no need to modify the plugInfo.json we generate during the build.

If you are copying ai.dll from the SDK to an installation folder, you also have to copy any other dll next to it. Those are related to licensing etc., and ai.dll will try to load them.

**Comment by furby-tm** [comment]
Beautiful, that's what I figured. Those `Ndr` coding errors just threw me off since they happen at plugin registration, which in the context of this application happen before a renderer plugin, or even the viewport GL context for that matter - is instantiated.

Obviously nothing will work properly if the plugin registration gets borked at all. So I figured I should make sure that's completely solid before attempting to activate arnold and expecting it to work properly.

I wouldn't suppose those coding error debug messages pop up for you on windows when you register the arnold-usd plugins, correct?

I've been working on smoothing things out here on Linux where I haven't experienced any of these issues, and I'll finally have a chance to test your suggested fix on Windows and give you the results of my findings late tonight.

In either case - I hope to provide you with something fruitful in return for your time and generosity in helping me out thus far. Thanks for everything!

**Comment by furby-tm** [comment]
Sorry about that, finally back, holidays and what not. I cannot get arnold's NDR to register at all on windows. When parsing the shaders none of the Arnold ones appear:

```bash
FORGE IO: ::: LIST SHADERS :::
* HwPtexTexture
* HwUvTexture
* HwFieldReader
* HwFieldReader_float
* HwFieldReader_float2
* HwFieldReader_float3
* HwPrimvar
* PxrLayer
* PxrLayerMixer
* PxrShadedSide
* PxrWireframe
* UsdPreviewSurfaceParameters
* UsdPrimvarReader_float
* UsdPrimvarReader_float2
* UsdPrimvarReader_float3
* UsdUVTexture
* aaOceanPrmanShader
* d_deepexr
* d_it
* d_null
* d_openexr
* d_png
* d_pointcloud
* d_targa
* d_texture
* d_tiff
* OmnidirectionalStereo
* PxrAdjustNormal
* PxrAovLight
* PxrAttribute
* PxrBackgroundDisplayFilter
* PxrBackgroundSampleFilter
* PxrBakePointCloud
* PxrBakeTexture
* PxrBarnLightFilter
* PxrBlack
* PxrBlackBody
* PxrBlend
* PxrBlockerLightFilter
* PxrBump
* PxrBumpManifold2D
* PxrCamera
* PxrChecker
* PxrClamp
* PxrColorCorrect
* PxrCombinerLightFilter
* PxrConstant
* PxrCookieLightFilter
* PxrCopyAOVDisplayFilter
* PxrCopyAOVSampleFilter
* PxrCross
* PxrCryptomatte
* PxrCurvature
* PxrCylinderCamera
* PxrCylinderLight
* PxrDebugShadingContext
* PxrDefault
* PxrDiffuse
* PxrDirectLighting
* PxrDirt
* PxrDiskLight
* PxrDisney
* PxrDisplace
* PxrDisplayFilterCombiner
* PxrDispScalarLayer
* PxrDispTransform
* PxrDispVectorLayer
* PxrDistantLight
* PxrDomeLight
* PxrDot
* PxrEdgeDetect
* PxrEnvDayLight
* PxrExposure
* PxrFacingRatio
* PxrFilmicTonemapperDisplayFilter
* PxrFilmicTonemapperSampleFilter
* PxrFlakes
* PxrFractal
* PxrGamma
* PxrGoboLightFilter
* PxrGradeDisplayFilter
* PxrGradeSampleFilter
* PxrHairColor
* PxrHalfBufferErrorFilter
* PxrHSL
* PxrImageDisplayFilter
* PxrImagePlaneFilter
* PxrIntMultLightFilter
* PxrInvert
* PxrLayeredBlend
* PxrLayeredTexture
* PxrLayerSurface
* PxrLightProbe
* PxrLightSaturation
* PxrManifold2D
* PxrManifold3D
* PxrMarschnerHair
* PxrMatteID
* PxrMeshLight
* PxrMix
* PxrMultiTexture
* PxrNormalMap
* PxrOcclusion
* PxrOrthographic
* PxrPanini
* PxrPathTracer
* PxrPerspective
* PxrPortalLight
* PxrPrimvar
* PxrProjectionLayer
* PxrProjectionStack
* PxrProjector
* PxrPtexture
* PxrRamp
* PxrRampLightFilter
* PxrRandomTextureManifold
* PxrRectLight
* PxrRemap
* PxrRodLightFilter
* PxrRoundCube
* PxrSampleFilterCombiner
* PxrSeExpr
* PxrShadowDisplayFilter
* PxrShadowFilter
* PxrSphereCamera
* PxrSphereLight
* PxrSurface
* PxrSwitch
* PxrTangentField
* PxrTee
* PxrTexture
* PxrThinFilm
* PxrThreshold
* PxrTileManifold
* PxrToFloat
* PxrToFloat3
* PxrUnified
* PxrValidateBxdf
* PxrVariable
* PxrVary
* PxrVCM
* PxrVisualizer
* PxrVolume
* PxrVoronoise
* PxrWatermarkFilter
* PxrWhitePointDisplayFilter
* PxrWhitePointSampleFilter
* PxrWorley
* UsdPreviewSurface
* UsdPrimvarReader_float4
* UsdPrimvarReader_int
* UsdPrimvarReader_string
* UsdPrimvarReader_normal
* UsdPrimvarReader_point
* UsdPrimvarReader_vector
* UsdPrimvarReader_matrix
* UsdTransform2d
```

**Comment by sirpalee** [comment]
A few things to try:

- run `kick -ADP` and opt-out of ADP
- if you build/register the USD procedural with the core, please disable that and make sure there are no leftover binaries
- remove usd_proc.dll and the `usd` folder next to it from the Arnold SDK folder

**Comment by furby-tm** [comment]
I have done all three of those, still experiencing the same behavior, does houdini and katana register plugins like this?
```cpp
const string core_plugin_path = TfStringCatPaths(DATAFILES_PATH, "usd/");
PlugRegistry::GetInstance().RegisterPlugins(core_plugin_path);

const string thirdparty_plugin_path = TfStringCatPaths(DATAFILES_PATH, "plugin/");
PlugRegistry::GetInstance().RegisterPlugins(thirdparty_plugin_path);
```

**Comment by sirpalee** [comment]
In other plugins, we either rely on a mechanism to load usd plugins from a folder with a specific name (like Houdini) or setting up the `PXR_PLUGINPATH_NAME` env var (like Katana).

Let's focus on the Linux case first. Do you `LD_PRELOAD` libai.so? That's a known limitation with the Linux usd/hydra plugins.

How do you load our ndr and hd plugin? Using the `PXR_PLUGINPATH_NAME` env var, or manually invoking the PlugRegistry in your application?

**Comment by furby-tm** [comment]
I do not `LD_PRELOAD` I simply configured `INSTALL_RPATH` to all the libraries, and had no issues there. I just want to clarify that on Linux there are 0 issues, I can run the Arnold Hydra Render Delegate as I can with Renderman and Storm and there are no issues. ("It's quite speedy by the way, really great work on the delegate!!") On windows, I install all needed libs to the bin directory. And on both platforms, I invoke `PlugRegistry` at the startup of my application.

**Comment by furby-tm** [comment]
Linux behaves exactly as expected, NDR is properly populated with Arnold shaders and the delegate launches in all it's glory. It's only on windows that things are having a bad day.

**Comment by sirpalee** [comment]
Hey! Sorry about the misunderstanding regarding Linux, I thought that the crash log is from there, but re-reading your comment I can see what you meant there.

When the NDR registers, we create an Arnold universe, which by defaults tries to output information to stdout. This works on Linux just fine if you launch from the terminal, which is very common there, but on windows, you generally launch apps without a stdout. At this moment there isn't a way to disable this.

**Comment by sirpalee** [comment]
Let's try to simplify the environment to see what's causing the issue. Could you get rid of all the prman/sdrosl etc. libraries, just install/compile base USD/Hydra and hdArnold/ndrArnold?

What did you mean by `On windows, I install all needed libs to the bin directory`? Which files do you install from the arnold sdk's bin folder?

**Comment by furby-tm** [comment]
My application supports STDOUT because I have the linker flag `/SUBSYSTEM:CONSOLE` set, which is all that is required to launch with stdout I believe.

Within my application's `main()` I simply hide the terminal window, so the user doesn't know the difference:
```cpp
#ifdef _WIN32
HWND hwnd = GetConsoleWindow();
ShowWindow(hwnd, 0);
#endif
```

**Comment by furby-tm** [comment]
Yeah, I could try that, just disable renderman and OSL and such to ensure they aren't conflicting? And what I meant was _all_ usd libraries are installed into `bin` optionally, this can include Arnold's libraries to remove the need to set `ARNOLD_HOME` which will then install all libraries in Arnold's SDK `bin` folder.

**Comment by sirpalee** [comment]
`ARNOLD_HOME` is only used during the build process so that shouldn't matter much. I'm more curious about what gets installed in the runtime environment or how are you making sure the Arnold libraries are found at runtime on Windows.

**Comment by furby-tm** [comment]
On windows, my philosophy is simply "stick it next to the `.exe`" and everything will magically be found. Presumably this is not the best way to ensuring Arnold's libraries are found?

**Comment by furby-tm** [comment]
![image](https://user-images.githubusercontent.com/18516968/103720034-a9a0d080-4f87-11eb-85c5-e18c45c742e9.png)

It's worth noting I manually linked and called `AiBegin()` to retrieve this stack trace for the hydra delegate. Otherwise, I don't get any error messaging regarding the Arnold delegate becoming activated and my application segfaults. I have no reason to believe arnold's `AiBegin` is working at all from the delegate "picking it up", how does the delegate call Arnold at runtime?

**Comment by sirpalee** [comment]
> On windows, my philosophy is simply "stick it next to the `.exe`" and everything will magically be found. Presumably this is not the best way to ensuring Arnold's libraries are found?

What if you add the arnold_sdk/bin subfolder to the PATH? There are a few things that Arnold looks up relative to its dll, which might be an issue if it's missing.

**Comment by furby-tm** [comment]
Same behavior it seems, even with Arnold's bin directly in `PATH`

**Comment by sirpalee** [comment]
Yes, this should help. I'll let you know what I find.

Note: USD automatically looks for plugins relative to its libraries. If your apps directory layout matches the original USD installation folder, you might load plugins twice.

**Comment by furby-tm** [comment]
Here is my application layout, tons of libraries...
![image](https://user-images.githubusercontent.com/18516968/103721473-f934cb80-4f8a-11eb-9aa1-619620f2db86.png)

and eventually my executable, `wingg.exe`:
![image](https://user-images.githubusercontent.com/18516968/103721529-19648a80-4f8b-11eb-9777-bde4cad7f557.png)

Plugins are found here -- relative to the `wingg.exe` this is `1.91/datafiles`:
![image](https://user-images.githubusercontent.com/18516968/103721596-487afc00-4f8b-11eb-90c7-e33d56401bb0.png)

**Comment by furby-tm** [comment]
`1.91/datafiles/usd` looks like the following, with all libraries moved to `bin`, and the paths in `plugInfo.json` for all these plugins point to `bin` where they are located:
![image](https://user-images.githubusercontent.com/18516968/103721642-66486100-4f8b-11eb-846c-9eff90fc17a8.png)

`1.91/datafiles/plugin` looks like the following:
![image](https://user-images.githubusercontent.com/18516968/103721662-76604080-4f8b-11eb-9d98-7b4eb70b8210.png)

**Comment by furby-tm** [comment]
To make things simple, if you would like to contact me directly at `wabi.film@gmail.com` I can send you the closed source project and precompiled libraries (OSL, USD, Qt, everything needed to compile) (only other dependency outside of these precompiled libs needed is visual studio)

**Comment by sirpalee** [comment]
`AiADPAddProductMetadata` showing up in the stack trace is most likely a red herring, our signal handler is installed when the crash happens, and it can't find a name for a symbol and it incorrectly reports `AiADPAddProductMetadata`.

**Comment by furby-tm** [comment]
You can disregard most of that stack trace however, since I manually linked to arnold and called `AiBegin()` manually to get the stack trace report, I don't believe `AiBegin()` is getting called at all from the Arnold Hydra Delegate

**Comment by sirpalee** [comment]
Do you call `AiEnd()` after calling `AiBegin()` in your application?

**Comment by furby-tm** [comment]
No, I never call Arnold directly from my application, I have USD/Hydra take care of all the third-party plugin/access. This `AiBegin()` call that I made was simply for testing purposes.

**Comment by sirpalee** [comment]
When you call `AiBegin()` in your app for testing purposes, do you call `AiEnd()` as well?

**Comment by furby-tm** [comment]
I did not, I could go ahead and test a `AiEnd()` call if you'd like, where would be a good time to call that? After registering the plugins?

**Comment by sirpalee** [comment]
No, no need for that. I just wanted to know, because AiEnd uninstalls our signal handler.

`Unless this second usage of AiBegin() forced the AiBegin() call from the Arnold Hydra Delegate to properly present itself` can you explain this? What do you mean by the Arnold Hydra Delegate to properly present itself? Do you mean it's now showing up in the list of render delegates? Or that our stack trace shows up?

**Comment by furby-tm** [comment]
Sorry for the confusion, Arnold has always showed in the list of render delegates, I meant to force the arnold stack trace to show up.

**Comment by sirpalee** [comment]
Gotcha. The reason why you see our stack trace is that `AiBegin` installs our signal handler. I think the crash happens outside our plugins, due to either a USD misconfiguration (not loading DLLs correctly, incorrect plugInfo, something like this) or some combination of DLLs misbehaving.

It would help if you tried stripping down the app first, removing all the unnecessary extra USD plugins.
If that works, you can try adding back everything one by one to see which combination of DLLs are causing the crash.
If that fails, you need to debug the app and pinpoint the location of the crash.

**Comment by furby-tm** [comment]
Okay, I can try that. I must have went over those `plugInfo.json` files nearly a dozen times but I'll verify again. Perhaps instead of relying on `PlugRegistry` I could `DL_OPEN` all the libraries instead?

**Comment by sirpalee** [comment]
That won't help, as plugInfos are also used to register types etc.

**Comment by furby-tm** [comment]
As a side note, I noticed `usd_proc.lib` and `usd_proc.dll` from this repo compile to much smaller sizes compared to the Arnold SDK, is that normal?

**Comment by sirpalee** [comment]
Yes. The usd_proc from the arnold sdk statically links against USD (but namespaces the symbols) and all its dependencies.

**Comment by furby-tm** [comment]
One last note, would any of these paths needs to be modified in the `usdArnold` schema.usda file?
```
#usda 1.0
(
"This file describes the Arnold USD schemas."
    subLayers = [
        @usd/schema.usda@,
        @usdGeom/schema.usda@,
        @usdShade/schema.usda@,
        @usdLux/schema.usda@
    ]
)
over "GLOBAL" (
    customData = {
        string libraryName = "usdArnold"
        string libraryPath = "./"
        string libraryPrefix = "Usd"
        string tokensPrefix = "UsdArnold"
    }
) {
```

**Comment by sirpalee** [comment]
Let's forget about usdArnold for now, it's not used by hdArnold or ndrArnold. Can you try without usdArnold?

**Comment by furby-tm** [comment]
Ah, my bad I thought they all relied on each other in some way, however no noticeable effect when removing `usdArnold`

**Comment by sirpalee** [comment]
Ok, what about removing the unnecessary USD plugins?

**Comment by furby-tm** [comment]
Hey! I just want to circle back on this, I have fixed this issue, with the following change in my cmake configuration, allowing Arnold to work again on release builds:

Reference for this issue here: https://github.com/PixarAnimationStudios/USD/issues/1279

```cmake
if(WIN32)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:rvalueCast /Zc:strictStrings")

  # The /Zc:inline option strips out the "arch_ctor_<name>" symbols used for
  # library initialization by ARCH_CONSTRUCTOR starting in Visual Studio 2019,
  # causing release builds to fail. Disable the option for this and later
  # versions.
  #
  # For more details, see:
  # https://developercommunity.visualstudio.com/content/problem/914943/zcinline-removes-extern-symbols-inside-anonymous-n.html
  if (MSVC_VERSION GREATER_EQUAL 1920)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:inline-")
  else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:inline")
  endif()
endif()
```
