### ISSUE TITLE
Building on Ubuntu : usdGenSchema not found

### ISSUE THREAD

**Issue by johhnry** [Autodesk/arnold-usd#626]
Hi,

**Describe the bug**
I am trying to build arnold-usd on Pop!_OS 20.10 (Ubuntu based) by using the `abuild` script (scons). This is the output of the build : 

```
scons: Reading SConscript files ...
Building Arnold-USD:
 - Build mode: 'profile'
 - Host OS: 'linux'
 - Arnold version: '6.1.0.0'
00:00:00   100MB         | log started Wed Dec 16 14:03:25 2020
00:00:00   100MB         | Arnold 6.1.0.0 [250260fb] linux clang-10.0.1 oiio-2.2.1 osl-1.11.6 vdb-4.0.0 clm-1.1.1.118 rlm-12.4.2 optix-6.6.0 2020/10/27 10:47:45
00:00:00   100MB         | running on pop-os, pid=19686
00:00:00   100MB         |  1 x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (4 cores, 8 logical) with 32012MB
00:00:00   100MB         |  NVIDIA driver version 455.38 (Optix 60700)
00:00:00   100MB         |  GPU 0: GeForce GTX 1060 6GB @ 1708MHz (compute 6.1) with 6069MB (5460MB available) (NVLink:0)
00:00:00   100MB         |  Pop!_OS 20.10 (groovy), Linux kernel 5.8.0-7630-generic
00:00:00   100MB         |  soft limit for open files raised from 1024 to 1048574
00:00:00   100MB         |  
00:00:00   100MB         | loading plugins from /opt/autodesk/arnold-6.1.0.0/bin/../plugins ...
00:00:00   100MB         |  alembic_proc.so: alembic uses Arnold 6.1.0.0
00:00:00   100MB         |  cryptomatte.so: cryptomatte uses Arnold 6.1.0.0
00:00:00   100MB         |  cryptomatte.so: cryptomatte_filter uses Arnold 6.1.0.0
00:00:00   100MB         |  cryptomatte.so: cryptomatte_manifest_driver uses Arnold 6.1.0.0
00:00:00   104MB         |  usd_proc.so: usd uses Arnold 6.1.0.0
00:00:00   106MB         | loaded 5 plugins from 3 lib(s) in 0:00.00
00:00:00   106MB         |  
00:00:00   106MB         | releasing resources
00:00:00   106MB         |  unloading 3 plugins
00:00:00   106MB         |   closing alembic_proc.so ...
00:00:00   106MB         |   closing cryptomatte.so ...
00:00:00   106MB         |   closing usd_proc.so ...
00:00:00   106MB         |  unloading plugins done
00:00:00   106MB         | Arnold shutdown
RuntimeError: Command /usr/local/USD/bin/usdGenSchema not found. Impossible to generate Schemas:
  File "/home/josephhenry/Downloads/arnold-usd/SConstruct", line 446:
    duplicate = 0, exports = 'env')
  File "/home/josephhenry/Downloads/arnold-usd/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/josephhenry/Downloads/arnold-usd/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/josephhenry/Downloads/arnold-usd/schemas/SConscript", line 85:
    raise RuntimeError('Command {} not found. Impossible to generate Schemas'.format(genSchema))
```

Looks like there's no `usdGenSchema` executable in the USD installation folder.

**To Reproduce**
1. Install USD into `/usr/local/USD` using the `build_usd.py` script : https://github.com/PixarAnimationStudios/USD#linux
2. Clone the `arnold-usd` repo and use this build command : 
```
arnold-usd $ sudo ./abuild MODE="profile" ARNOLD_PATH="/opt/autodesk/arnold-6.1.0.0" USD_PATH='/usr/local/USD' USD_BUILD_MODE='shared_libs' BOOST_INCLUDE='/usr/include' PYTHON_INCLUDE='/usr/include/python2.7' PYTHON_LIB='/usr/lib' PYTHON_LIB_NAME='python2.7' PREFIX='/opt/autodesk/arnold-usd'
```

**Expected behavior**
I suppose that when building USD, it should provide a `usdGenSchema` executable in the bin folder?

This is strange because USD provides this script in `USD/pxr/usd/usd/usdGenSchema.py` but it should be available in the bin folder of the installation?

I saw that there's the information here : https://github.com/PixarAnimationStudios/USD/blob/release/BUILDING.md#usd-schema-generation
So it means that I need to compile USD with cmake?

**Used Software Versions**
 - Arnold: 6.1.0.0
 - USD: 20.11
 - Compiler: gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
 - OS: Pop!_OS 20.10 (Linux pop-os 5.8.0-7630-generic)
 - Any 3rd-party app: [e.g. Katana-3.2]

Thanks

**Comment by sirpalee** [comment]
Hi, correct, you need usdGenSchema to build the schemas. Alternatively, you can disable building of the schemas by setting BUILD_SCHEMAS to False.

**Comment by sirpalee** [comment]
One additional note, the USD build scripts should put usdGenSchema in the binary folder, given you have the required python dependencies installed. (`jinja2` and `argparse`) I suggest looking at the build logs, there should be a warning/error message about these libraries missing.

**Comment by johhnry** [comment]
Ok thanks for the answer but I reinstalled USD, deleted the `/usr/local/USD` directory and rerun the build script with `jinja2` and `argparse` installed. There's no error message nor `usdGenSchema` executable...

If I set the BUILD_SCHEMAS option to False, it's disabling a lot of functionalities?

**Comment by sirpalee** [comment]
No, we are don't rely on the schemas for now, but that's going to change in the future.

In my local tests, usdGenSchema got built in the expected location, so it's either due to an incorrect build configuration or an issue with the Ubuntu-based system. I suggest asking about the missing usdGenSchema either on the usd-interest google group or on Pixar's GitHub repository.

If you find any further issues, feel free to open a new ticket, or use the discussion page, but note, we target CentOS7/RHEL based systems.
