### ISSUE TITLE
Curves: invalid number of points 

### ISSUE THREAD

**Issue by kreppene** [Autodesk/arnold-usd#645]
**Describe the bug**
We get this error on some curve primitives, 
`00:00:00   179MB ERROR   |  [curves] /Root/RootOffset/g_geometry/groom/head_hair/head_hairShape: invalid number of points (found 0, expected 252312)`
The error does not happen randomly, if a curve fails to render it will always fail,
but if we just change the density of the curve slightly it renders fine.

**To Reproduce**
I attach a .zip file containing a usd file that has this error, and a renderMe.ass file
run kick renderMe.ass to reprocude the problem. 
we tested this on arnold 6.2.0.0 and 6.1.0.0 with the same error

**Screenshots**
This is the result we get in usdView, 
![image](https://user-images.githubusercontent.com/7374105/106121063-6b966700-6157-11eb-80ad-24ca45099277.png)

**Used Software Versions**
 - Arnold: [e.g. 6.2.0.0]
 - USD: [e.g. 0.20.08]
 - Compiler: vs 2015
 - OS: Windows 10

[invalid_num_points.zip](https://github.com/Autodesk/arnold-usd/files/5886299/invalid_num_points.zip)

**Comment by sebastienblor** [comment]
The render logs say 
`00:00:02   161MB WARNING |  resetting parameter points on /Root/RootOffset/g_geometry/groom/head_hair/head_hairShape (found: nans or infs)`

If I convert the scene to .ass, by running \kick.exe head_hair.usd -resave test.ass -db``  I can see a bunch of invalid positions

```
 -1.67249155 9.55797577 2.8598671 0.0734042525 10.8496428 3.59215379 -nan(ind) -nan(ind) -nan(ind)
  -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind)
  -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind)
  -nan(ind) -nan(ind) -nan(ind) 0.106919825 10.8574924 3.64024115 -nan(ind) -nan(ind) -nan(ind)
  -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind)
  -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind)
  -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind)
  -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan(ind) -nan

```
so the tool that was used to create this usd file can create such invalid data, depending on the hair density. Here it's a binary usd, but if you export it as an ascii .usda, you will probably see these errors in the usda file as well.

**Comment by kreppene** [comment]
I think the reason you se this problem with nan(ind) in your usda file, is that you are using the arnold translator to convert to usda, 
if i convert the file to a usda file using usdCat i dont get the same problem.

**Comment by sebastienblor** [comment]
you don't see any `(nan) ` in the usda file ? I don't have a working usdcat right now, but these nans are what I receive as input. If just after loading the usd file I resave it to usda (using USD 20.11) I get lots of these

**Comment by sebastienblor** [comment]
we've just tried with usdCat and the nans are indeed present in the ascii file

**Comment by kreppene** [comment]
hmm, yes you are right, I tested again now using USD19.11, 20.05 and 20.11 and all produce the same result.
how did i miss this the first time i tested it.

Sorry about that, the problem must be coming from Houdini. 
I guess this issue can be closed
