### ISSUE TITLE
USD procedural cannot render crowd cache

### ISSUE THREAD

**Issue by arnold-support** [Autodesk/arnold-usd#652]
Reported by nozon.
The attached crowd USD file does not render properly with the USD procedural (I tested in Maya).

I get about 3.6K messages like this:

`Warning (secondary thread): in _DeprecatedBindingCheck at line 200 of S:\tmp\arnold\tools\kook\usd\build\usd-20.11_static_windows_vc-14.2_cxx14\pxr\usd\usdSkel\cacheImpl.cpp -- Found binding property </crowd/Female_03_stanging7/geometry/default_geo_skin.skel:joints>, but the SkelBindingAPI was not applied on the owning prim. In the future, binding properties will be ignored unless the SkelBindingAPI is applied (see UsdSkelBindingAPI::Apply)
`

and then 1470 WARNINGS:

`00:00:15  2588MB WARNING |  /crowd/Female_04_717/geometry/default_geo_skin/mesh_0: varying user-data count wrong! (found 31248 expected 7812) -- disabling user-data 'skel:jointIndices'
`

and all the crowd agents are standing in a T post, when they should be sitting

If I render in Solaris without Arnold, or with husk on the command line, I gets thousands of " bad primvar sample size for shapelib_includes" warnings, but the render looks right: most of the crowd is sitting, some have their arms up cheering, others don't.

[crowd.zip](https://github.com/Autodesk/arnold-usd/files/5934609/crowd.zip)

**Comment by sebastienblor** [comment]
Unfortunately, the skinning is a black-box for the procedural, we just call `UsdSkelBakeSkinning` which will ask USD to apply the skinning to the whole scene, but we don't control what happens in that usd function.

The 3.6k messages come from this function, when USD is trying to apply the skinning, it says that something wasn't applied properly when the file was saved. If I comment  `UsdSkelBakeSkinning` in the procedural code , the errors go away. The fact that it works with husk, might be related to the version of usd maybe ? (the errors say that such binding properties will be ignored "in the future").
It's also possible that hydra doesn't call `UsdSkelBakeSkinning`  but instead applies the skinning differently. But as per the usd docs, this is the intended way to apply skinning for a renderer.

I assume this scene was saved from Solaris ? Which version of Houdini was used ?

**Comment by sebastienblor** [comment]
Closing as there are other tickets for similar issues, and there hasn't been any feedback
