### ISSUE TITLE
Add RPATH to SCons build

### ISSUE THREAD

**Issue by robpieke** [Autodesk/arnold-usd#670]
It would be great to see `hdArnold.so` build with RPATH support to help find `libai.so` at runtime.

For example, adding this to `SConstruct`:
```
env['RPATH'] = ARNOLD_BINARIES
```

**Comment by sirpalee** [comment]
Hi @robpieke !

I created #745 for this issue, please let me know if it's what you are looking for. I don't want to add anything to RPATH unconditionally, so I added a build variable for Linux/OSX.

**Comment by robpieke** [comment]
That looks exactly like the kind of thing I'm after :)
