### ISSUE TITLE
Allow user to set compiler with full path

### ISSUE THREAD

**Issue by Svenito** [Autodesk/arnold-usd#71]
**Describe the feature you'd like**
The ability to specify a full path to the gcc compiler, rather than restricting it to `gcc` only

**Describe the solution you'd like**
Able to set `COMPILER="/path/to/bin/gcc` in the `custom.py` file

**Describe alternatives you've considered**
Tried to set it, but `ALLOWED_COMPILERS` does not permit this. Also tried setting `CXX` and `CC` in the `custom.py` file with no luck

**Comment by BigRoy** [comment]
@Svenito would be it be good enough for you to first add the `gcc` directory to the beginning of your `PATH` variable so that calling `gcc` refers to the same one? That would be you customizing it before running the build.

```py
import os

os.environ ["PATH"] = "/path/to/gccfolder/" + os.pathsep + os.environ ["PATH"]
```

It should at least allow you to continue for now.

**Comment by Svenito** [comment]
We have a variety of compilers and versions installed into their own directories. We can select which one we need by either setting the CXX or CC variables, or just specifying the full path, depending on the build system.

This is both to support multiple distros and requirements for different DCCs, so it's kind of required. 

The path fix above will work for now though, thanks.

**Comment by sirpalee** [comment]
Since USD 20.05 requires GCC 6.3.1 and the use of C++14, I'm extending the documentation detailing how to build arnold-usd against this version on Linux and using gcc 6.3.1. That will solve this issue.
