### ISSUE TITLE
Udim assignment erroring out for textures

### ISSUE THREAD

**Issue by dlekanis** [Autodesk/arnold-usd#713]
When trying to render the usd loading it as a procedural in either Houdini or Maya, arnold cannot understand the syntax, so it errors out. When rendering through husk in Solaris everything works fine.

**To Reproduce**
Load a geo with multiple tiles in the uvs, and try to assign a material in Solaris. The usd will render find in Solaris with arnold, but the render will fail if rendered with arnold through a procedural

**Expected behavior**
The render should work fine

**Screenshots**
![image](https://user-images.githubusercontent.com/80894127/111620384-8ba0e900-87de-11eb-9bfc-9837d0c749c1.png)

**Used Software Versions**
 - Arnold: [6.2.0.1]
 - Houdini [18.5.499]
 - htoa [5.6.0.2]
 - OS: [Centos 7]

**Additional context**
Tried loading multiple formats and also loading the straight the tx files and still the same thing

**Comment by sebastienblor** [comment]
Hi, thanks for the feedback. 
Could you please post an example of a usd file that is failing for you with the procedural ? (no need to post the textures, just the usd file). As there are different ways to author usd scenes, it will make it simpler to ensure we're talking about the same thing.

Thanks !

**Comment by compso** [comment]
Can not reproduce closing for now.

We will repo if we can reproduce the issue
