### ISSUE TITLE
Arnold does not use wrapS and wrapT values on UsdUVTexture shader node when rendering UsdPreviewSurface

### ISSUE THREAD

**Issue by TechArtistG** [Autodesk/arnold-usd#727]
**Describe the bug**
Changing the wrapS and wrapT values on UsdUvTexture shader node when rendering UsdPreviewSurface does not affect the texture wrap in Arnold.  Arnold will always render the texture in repeat mode regardless of wrap values.

**To Reproduce**
1. Create a very basic UsdPreviewSurface graph which uses a UsdUvTexture for diffuseColor input.  I pretty much copy/pasted the materials example from the Pxr USD site.
2. Scale the UVs so you can see the wrap value changes.
2. Add wrapS and wrapT inputs to the texture sampler, here I'm setting to clamp:

```
texSampler.CreateInput("wrapS", Sdf.ValueTypeNames.Token).Set(UsdHydra.Tokens.clamp)
texSampler.CreateInput("wrapT", Sdf.ValueTypeNames.Token).Set(UsdHydra.Tokens.clamp)
```
or build one in Houdini and set the wrap values:
![image](https://user-images.githubusercontent.com/1031627/112570393-339c5080-8da3-11eb-8650-cb532a58971c.png)

3. Render the resultant USD in GL, you'll see the wrap values behaving as expected.
4. Switch to Arnold, wrap is always set to repeat.

**Expected behavior**
Rendering with Arnold should apply wrap values to UsdUvTexture nodes.

**Screenshots**
Rendered with GL and wrap set to clamp:
![image](https://user-images.githubusercontent.com/1031627/112570110-aa851980-8da2-11eb-8fd1-0688e08e92fa.png)

Rendered in Arnold with wrap set to clamp:
![image](https://user-images.githubusercontent.com/1031627/112570192-d0aab980-8da2-11eb-823c-15785de51c1f.png)

**Used Software Versions**
 - Arnold: HtoA 5.6.0.2 /  Arnold 6.2.0.1
 - USD: 20.11
 - Compiler: Don't know
 - OS: Win 10
 - Any 3rd-party app: Houdini 18.5.499

**Additional context**
This was happening in Houdini viewport when Hydra delegate set to Arnold.  Haven't tested renders through husk

**Comment by compso** [comment]
need a ticket for the procedural to implement the same
