### ISSUE TITLE
Motion Blur UsdSkel, Hydra

### ISSUE THREAD

**Issue by dronepiece** [Autodesk/arnold-usd#738]
**Describe the bug**
Motion blur on a mesh deformed by UsdSkel does not work. 
Same result in both hydra (Solaris) and in the procedural (Arnold StandIn).
The motion blur from transformations works, but not from the deformed mesh.

It looks like this issue should be fixed in this pull request: https://github.com/PixarAnimationStudios/USD/pull/1455
However, I'm not sure if this automatically will fix any issues in the arnoldstandin? Or if this just helps the Hydra implementation?

**To Reproduce**
1. Download the UsdSkel example file from https://graphics.pixar.com/usd/downloads.html
2. In Maya, read the file in Arnold Stand-In.
3. Enable motion blur in arnold rendersettings.
4. Render.
5. You will see that motionblur exists but its only the transformation of the skeleton that shows up.
6. Mute the transform animation on the top group.
7. The character will now walk on the same spot, with no motion blur whatsoever.

**Expected behavior**
A fully motion blurred character

**Screenshots**
Examples from Houdini Solaris Arnold (Same result in Arnold StandIn)
Deformed by UsdSkel = Transform motion blur
![skel](https://user-images.githubusercontent.com/39924609/113324913-f6dad700-9317-11eb-9334-87e8063ce79d.png)

Baked with Bake Skinning LOP = Expected result
![baked](https://user-images.githubusercontent.com/39924609/113324917-f93d3100-9317-11eb-853c-0b98a8c32a91.png)

**Used Software Versions**
 - Arnold: 6.2.0.1
 - USD: 20.11
 - OS: Win 10
 - Any 3rd-party app: Houdini 18.5.462, Maya 2022

**Comment by sirpalee** [comment]
Hi @dronepiece !

Thanks for reporting this and letting us know that this has been improved upstream! We'll look into supporting the new APIs in the render delegate, and investigate if the functions we use in the procedural pick up the new functionality automatically.

**Comment by compso** [comment]
Need to confirm if fixed in procedural already, if not create a separate ticket

**Comment by sebastienblor** [comment]
Same issue exists in the procedural so I created #951. 
However, based on what I see this is a USD bug in `UsdSkelBakeSkinning`, but we could check if we find a workaround on our side.
