### ISSUE TITLE
Error rendering point attributes in procedural

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#749]
This may relate to #228, it seems like the colors are being created now but the points are in the wrong place. 

[test.zip](https://github.com/Autodesk/arnold-usd/files/6277746/test.zip)

**Comment by sebastienblor** [comment]
No, it's actually related to the changes from #676 . This usd file has static positions, but velocities on the points. The camera has a shutter so we're rendering it with motion blur. As opposed to before, we're now applying the velocities on the points, so the result is now different than before. Possibly an important look-breaking change to report

**Comment by jhodgson** [comment]
Makes, sense - nothing to report then, this is a new feature.   Closing, thanks.
