### ISSUE TITLE
usd procedural: UsdPrimvarReader varname connection does not work

### ISSUE THREAD

**Issue by arnold-support** [Autodesk/arnold-usd#763]
**Describe the bug**
No UV coordinates for texturing when UsdPrimvarReader_float2 varname is connected to the name parameter

**To Reproduce**
1. Extract the attached archive
2. kick test.ass

**Expected behavior**
We should see the texture.

**Screenshots**
<img width="480" alt="usd_test_texture" src="https://user-images.githubusercontent.com/6383425/115750607-556b0200-a366-11eb-9e80-aabd861a12df.png">

**Used Software Versions**
 - Arnold: 6.2.0.1
 - USD: from 3ds max
[repro.zip](https://github.com/Autodesk/arnold-usd/files/6359817/repro.zip)

**Comment by sebastienblor** [comment]
this has already been fixed at some point. Closing the ticket
