### ISSUE TITLE
Can't compile when using USD 21.05

### ISSUE THREAD

**Issue by robpieke** [Autodesk/arnold-usd#765]
At present, it's not possible to compile when using USD 21.05 due to several issues:
- names of several light tokens have changed which breaks `render_delegate/light.cpp`
- changed signature of `UsdImagingGprimAdapter::Get` breaks compiling `UsdImagingArnoldShapeAdapter`
- removal of `_GetMaterialNetworkSelector` from `UsdImagingPrimAdapter`

**Comment by sirpalee** [comment]
Hi Rob! I'm going to update the ticket title/description to cover all the USD 21.05 related issues, as there are more problems than just the light tokens in the render delegate.
