### ISSUE TITLE
USD resource folder not properly copied during the testsuite

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#78]
In order to use the usd procedural, the resource `usd` folder must be found next to the procedural. It contains all the ` .json` files that are needed to render. When this folder isn't found, the procedural ends up crashing with a message like 
```
Coding Error (secondary thread): in _OpenLayerAndUnlockRegistry at line 2939 of
D:\arnold\core\arnold\tools\kook\usd\build\usd-19.05_shared_windows_vc-14.0\pxr\
usd\lib\sdf\layer.cpp -- Cannot determine file format for @sphere.usd@
Coding Error (secondary thread): in Open at line 978 of D:\arnold\core\arnold\to
ols\kook\usd\build\usd-19.05_shared_windows_vc-14.0\pxr\usd\lib\usd\stage.cpp --
 Invalid root layer
```

When we run the testsuite, this folder isn't copied properly, so it's hard to make it work out of the box

**Comment by BigRoy** [comment]
> In order to use the usd procedural, the resource usd folder must be found next to the procedural. 

If that's the case. How come it is only an issue when running the `testsuite`? Is it because only then it is unable to find them in `USD` itself? And if so, why is that?

**Comment by sebastienblor** [comment]
It's not a problem only during the testsuite, the `usd` folder must be found for the procedural to run properly. But we always build the procedural against a static USD, maybe that's the difference with your setup ? Since there's no USD lib to link against, the resource folder must be next to the procedural.

**Comment by BigRoy** [comment]
> It's not a problem only during the testsuite, the usd folder must be found for the procedural to run properly. But we always build the procedural against a static USD, maybe that's the difference with your setup ? Since there's no USD lib to link against, the resource folder must be next to the procedural.

Well, then shouldn't that mean that copying the `USD/lib/usd` tree in #79 should also be copied when just building the `procedural` as opposed to only when building the `testsuite`?

**Comment by sebastienblor** [comment]
Right, we could always copy the folder during any build of the procedural.
