### ISSUE TITLE
Add support for curve pinning

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#800]
**Describe the feature you'd like**
We should add support for curve pinning when rendering BasisCurves. Details can be found here: https://github.com/PixarAnimationStudios/USD/blob/090ef0d849ced875b3b99a15e454b69148ccd8e1/pxr/usd/usdGeom/schema.usda#L1235

**Comment by suekieza** [comment]
Hey hey, is this going to get looked at soon?
