### ISSUE TITLE
Unrecognized colorspace in Solaris

### ISSUE THREAD

**Issue by Tuftux** [Autodesk/arnold-usd#82]
Hi !

Trying out a fresh build of the Arnold render deleguate (using 5.4.0.2) with H18.0.287 i'm getting the following error when using the Image node with an OCIO env variable (for ACES) :

`[texturesys] unable to convert from color space "ACES - ACEScg", ignoring color transform`

This is happening with an OpenEXR texture. This works fine in MtoA with Arnold 5.4.
On Windows 10.

Thanks !

**Comment by sirpalee** [comment]
Hey, @Tuftux can you share an example scene, including the texture, and share your env setup?

**Comment by Tuftux** [comment]
Hey guys, happy to let you know that this issue seems to be fixed with the very latest HtoA Beta :) !

**Comment by BigRoy** [comment]
I'm getting these errors with Windows 10 + Houdini 20.0.547 + HtoA 6.2.5.1 currently. It just looks like the OCIO color manager does not load my OCIO config at all and defaults to the HtoA default one (that's inside the plug-in folder).

Aside of setting the `OCIO` env var prior to launch of Houdini is there anything special I still need to do for HtoA (IPR) to actually use my defined OCIO config?
