### ISSUE TITLE
SSS not translating correctly

### ISSUE THREAD

**Issue by Tuftux** [Autodesk/arnold-usd#83]
Hi !

Testing with Houdini 18.0.287, the Standard Surface SSS does not seem to be handled correctly, set the SSS weight to 1 and the object turns black.

**Comment by sirpalee** [comment]
Hey, @Tuftux can you upload an example scene showcasing the issue?

**Comment by Tuftux** [comment]
[SSSBlack.zip](https://github.com/Autodesk/arnold-usd/files/3905836/SSSBlack.zip)

Here it is ! In the ZIP there is both a Houdini 18 HIP file and a Maya File as well as screenshots of what i'm getting in both.
Further investigating, if you set the value of the SSS to something incredibly small (like 0.00000001) you start to see somewhat of a difference on some edges of the mesh but its barely there. Maybe there's an issue with units/scale ?

Thanks !

**Comment by sirpalee** [comment]
@Tuftux I was able to open your file and see the black geometry and confirm your Maya test scene renders very differently.

**Comment by sirpalee** [comment]
@Tuftux the issue happened because the render delegate's mesh adapter did not take the topology orientation into account. Thanks for reporting this issue!
