### ISSUE TITLE
directional light angle affects exposure in hydra

### ISSUE THREAD

**Issue by hehuapoka** [Autodesk/arnold-usd#893]
set arnold angle  for usd dir light. light 
Brightness will changes too much

**Comment by sirpalee** [comment]
Hi @hehuapoka regarding the distant light's `Angle`, please make sure that `Normalize Power` is set to on (to its default value). That should fix your issues regarding intensity changes when modifying the `Angle` parameter.

**Comment by sirpalee** [comment]
Created a second ticket for adaptive sampling: #913 , closing this ticket.
