### ISSUE TITLE
Use 32 bit precision for the beauty if using a newer USD build

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#9]
Newer USD expanded the HdxCompositor to allow for non-8 bit int buffers for the color. We should take advantage of this and use f32 for beauty.

Related to: #8

**Comment by sirpalee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Render Delegate] Use the render buffer to pass AOV data to Hydra](https://trello.com/c/sbund34Y/57-render-delegate-use-the-render-buffer-to-pass-aov-data-to-hydra)

**Comment by nrusch** [comment]
I think maybe the render delegate should respect the `HdAovDescriptor` definition from the task controller...
