### ISSUE TITLE
UDIM with relative path in Mtoa

### ISSUE THREAD

**Issue by hehuapoka** [Autodesk/arnold-usd#914]
When I finished the scene in 'Houdini'. Texture missing when reading with Maya Arnold stand in. Finally, it is found that the relative path of 'udim' cannot be resolved. I hope Arnold can support it

**Comment by JenusL** [comment]
udim is case sensitive in USD and needs to be uppercase... so have you tried <UDIM> ?

**Comment by hehuapoka** [comment]
> udim is case sensitive in USD and needs to be uppercase... so have you tried <UDIM> ?

i was use uppercase! houdini ,katana is right。mtoa have this problem in stand-in

**Comment by compso** [comment]
please prove a repo for the issue or steps to reproduce a USD file that causes the issue

**Comment by compso** [comment]
closing this issue, we will reopen it when we can successfully repro the issue
