### ISSUE TITLE
The Render delegate does not work within Maya to Hydra

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#92]
**Describe the bug**
I have a video showing bug.

[2019-12-03 10-58-44.flv.tar.gz](https://github.com/Autodesk/arnold-usd/files/3915613/2019-12-03.10-58-44.flv.tar.gz)

**To Reproduce**
1. Opened maya tried working with arnold(hydra)

**Expected behavior**
To be able to use arnold(hydra)

**crash log**
[dumpdata.zip](https://github.com/Autodesk/arnold-usd/files/3915631/dumpdata.zip)

**Used Software Versions**
 - Arnold: 5.4.0.2
 - USD: 0.19.11
 - Compiler:  GCC 4.8.5
 - OS: Linux Centos 7
 - Any 3rd-party app: Maya

**Additional context**
I built yesterday using shared_lib flag could this be part of the problem? If so what do I need to do to check into it?

**Comment by sirpalee** [comment]
Hey @suesauer can you try compiling with BUILD_HOUDINI_TOOLS off?

**Comment by suesauer** [comment]
Will rebuild now and see if that helps

**Comment by suesauer** [comment]
Thanks @sirpalee :D

**Comment by suesauer** [comment]
Hey, @sirpalee 

rebuilt without Houdini, still got same result. I do want houdini though.

`[suesauer@sunrise28 arnold-usd]$ ./abuild MODE="opt" BUILD_SCHEMAS=False BUILD_RENDER_DELEGATE=True BUILD_NDR_PLUGIN=True BUILD_USD_WRITER=False BUILD_DOCS=False BUILD_HOUDINI_TOOLS=False USD_BUILD_MODE="shared_libs" DISABLE_CXX11_ABI=True ARNOLD_PATH="/opt/solidangle/mtoa/2019" PYTHON_INCLUDE="/usr/include/python2.7" PYTHON_LIB="/usr/lib" PYTHON_LIB_NAME="python2.7" USD_PATH="/home/suesauer/Documents/USD" USD_BIN="/home/suesauer/Documents/USD/bin" USD_INCLUDE="/home/suesauer/Documents/USD/include" USD_LIB="/home/suesauer/Documents/USD/lib" PREFIX="/home/suesauer/Documents/arnold-usd" USD_1910_UPDATED_COMPOSITOR=True
scons: Reading SConscript files ...
Building Arnold-USD:
 - Build mode: 'opt'
 - Host OS: 'linux'
 - Arnold version: '5.4.0.2'
scons: done reading SConscript files.
scons: Building targets ...
Install file: "build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/arnold_usd.h" as "/home/suesauer/Documents/arnold-usd/include/arnold_usd.h"
Install file: "ndr/api.h" as "/home/suesauer/Documents/arnold-usd/include/ndr/api.h"
Install file: "ndr/discovery.h" as "/home/suesauer/Documents/arnold-usd/include/ndr/discovery.h"
Install file: "ndr/ndrarnold.h" as "/home/suesauer/Documents/arnold-usd/include/ndr/ndrarnold.h"
Install file: "ndr/parser.h" as "/home/suesauer/Documents/arnold-usd/include/ndr/parser.h"
Install file: "ndr/utils.h" as "/home/suesauer/Documents/arnold-usd/include/ndr/utils.h"
Install file: "render_delegate/api.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/api.h"
Install file: "render_delegate/config.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/config.h"
Install file: "render_delegate/constant_strings.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/constant_strings.h"
Install file: "render_delegate/debug_codes.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/debug_codes.h"
Install file: "render_delegate/hdarnold.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/hdarnold.h"
Install file: "render_delegate/instancer.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/instancer.h"
Install file: "render_delegate/light.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/light.h"
Install file: "render_delegate/material.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/material.h"
Install file: "render_delegate/mesh.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/mesh.h"
Install file: "render_delegate/openvdb_asset.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/openvdb_asset.h"
Install file: "render_delegate/points.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/points.h"
Install file: "render_delegate/render_buffer.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/render_buffer.h"
Install file: "render_delegate/render_delegate.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/render_delegate.h"
Install file: "render_delegate/render_param.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/render_param.h"
Install file: "render_delegate/render_pass.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/render_pass.h"
Install file: "render_delegate/renderer_plugin.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/renderer_plugin.h"
Install file: "render_delegate/shape.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/shape.h"
Install file: "render_delegate/utils.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/utils.h"
Install file: "render_delegate/volume.h" as "/home/suesauer/Documents/arnold-usd/include/render_delegate/volume.h"
Install file: "render_delegate/plugInfo.json" as "/home/suesauer/Documents/arnold-usd/plugin/hdArnold/resources/plugInfo.json"
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/config.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/config.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/constant_strings.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/constant_strings.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/debug_codes.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/debug_codes.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/instancer.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/instancer.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/light.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/light.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/material.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/material.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/mesh.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/mesh.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/openvdb_asset.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/openvdb_asset.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/points.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/points.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/render_buffer.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/render_buffer.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/render_delegate.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/render_delegate.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/render_param.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/render_param.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/render_pass.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/render_pass.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/renderer_plugin.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/renderer_plugin.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/shape.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/shape.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/utils.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/utils.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/volume.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/volume.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/nodes/driver.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/nodes/driver.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/nodes/nodes.os -c -fno-operator-names -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -w -O3 -fPIC -D_LINUX -DUSD_HAS_UPDATED_COMPOSITOR -DHDARNOLD_EXPORTS -I/opt/solidangle/mtoa/2019/include -I/home/suesauer/Documents/USD/include -I/home/suesauer/Documents/USD/include/boost-1_61 -I/usr/include/python2.7 -Ibuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Irender_delegate render_delegate/nodes/nodes.cpp
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/hdArnold.so -Wl,--no-undefined -shared build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/config.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/constant_strings.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/debug_codes.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/instancer.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/light.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/material.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/mesh.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/openvdb_asset.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/points.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/render_buffer.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/render_delegate.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/render_param.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/render_pass.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/renderer_plugin.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/shape.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/utils.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/volume.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/nodes/driver.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/nodes/nodes.os -L/opt/solidangle/mtoa/2019/bin -L/opt/solidangle/mtoa/2019/bin -L/home/suesauer/Documents/USD/lib -Lbuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate -Lrender_delegate -L/usr/lib -lai -ldl -ltbb -larch -lplug -ltf -lvt -lgf -lwork -lhf -lhd -lhdx -lsdf -lusdImaging -lusdLux -lpxOsd -lpython2.7 -lboost_python
Install file: "build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/render_delegate/hdArnold.so" as "/home/suesauer/Documents/arnold-usd/plugin/hdArnold.so"
Install file: "ndr/plugInfo.json" as "/home/suesauer/Documents/arnold-usd/plugin/ndrArnold/resources/plugInfo.json"
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/ndr/ndrArnold.so -Wl,--no-undefined -shared build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/ndr/discovery.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/ndr/parser.os build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/ndr/utils.os -L/opt/solidangle/mtoa/2019/bin -L/opt/solidangle/mtoa/2019/bin -L/home/suesauer/Documents/USD/lib -Lbuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/ndr -Lndr -L/usr/lib -lai -ltbb -larch -ltf -lgf -lvt -lndr -lsdr -lsdf -lusd -lpython2.7 -lboost_python
Install file: "build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/ndr/ndrArnold.so" as "/home/suesauer/Documents/arnold-usd/plugin/ndrArnold.so"
Install file: "plugInfo.json" as "/home/suesauer/Documents/arnold-usd/plugin/plugInfo.json"
g++ -o build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/procedural/usd_proc.so -Wl,--no-undefined -shared build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/procedural/main.os -L/opt/solidangle/mtoa/2019/bin -L/opt/solidangle/mtoa/2019/bin -L/home/suesauer/Documents/USD/lib -Lbuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/procedural -Lprocedural -L/usr/lib -Lbuild/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/translator -Ltranslator -lai -lusd_translator -lsdf -ltf -lusd -lar -lusdGeom -lusdShade -lvt -lusdLux -lpython2.7 -lboost_python
Install file: "build/linux_x86_64/gcc_opt/usd-0.19.11_arnold-5.4.0.2/procedural/usd_proc.so" as "/home/suesauer/Documents/arnold-usd/procedural/usd_proc.so"
scons: done building targets.
`

Thanks

**Comment by sirpalee** [comment]
The build log looks fine, I don't think there is a problem with your build anymore. There are some problems with Maya to Hydra looking at the behavior (like the missing function to generate the options menu - which should be automatically created in Maya to Hydra).

When disabling Houdini tools and using that build with Maya to Hydra, the TF_ERROR should be gone (ie, the warning about the bprimHoudiniFieldAsset in the script window), can you confirm that the error message is gone? When using this build, did the stack trace change?

Regarding the `BUILD_HOUDINI_TOOLS` option, it enables some Houdini specific features in the Render Delegate, like directly accessing in-memory OpenVDB volumes from Houdini, however that's not useful in Maya. Are you planning to use the same render delegate library in Maya and Houdini?

**Comment by suekieza** [comment]
Hey there @sirpalee, 
Looks like its still doing some really weird stuff even after the disabling of houdini tools.
See video:
[2019-12-05 11-30-42.flv.tar.gz](https://github.com/Autodesk/arnold-usd/files/3926035/2019-12-05.11-30-42.flv.tar.gz)

FYI: I rebuilt today.

**Comment by sirpalee** [comment]
@suekieza thank you the information! I'll have to configure and test usd-maya locally to make progress on this. I'll let you know when I can get it up and running.

**Comment by sirpalee** [comment]
@suekieza I assume this is fixed now with the updates? Ie, your other tickets show the render delegate working on maya to hydra.

**Comment by suesauer** [comment]
Yup it works now thanks
