### ISSUE TITLE
arnold can‘t save images

### ISSUE THREAD

**Issue by hehuapoka** [Autodesk/arnold-usd#931]
In solaris, when the Subdivision Scheme attribute of the Mesh model is catmull clark, arnold cannot output pictures
[mesh_subdivision.zip](https://github.com/Autodesk/arnold-usd/files/7575920/mesh_subdivision.zip)

**Comment by kikou** [comment]
Thanks for reporting, we're having a look a the scene to figure out the problem.

**Comment by hehuapoka** [comment]
> 

CheckVisibilityAndSidedness(sceneDelegate, id, dirtyBits, param);

    if (HdChangeTracker::IsDisplayStyleDirty(*dirtyBits, id)) {
        param.Interrupt();
        const auto displayStyle = GetDisplayStyle(sceneDelegate);
        AiNodeSetByte(
            GetArnoldNode(), str::subdiv_iterations, static_cast<uint8_t>(std::min(4,std::max(0, displayStyle.refineLevel))));
    }
Maybe default subdivi too high. it is can normal save image when i clamp max to 4

**Comment by sebastienblor** [comment]
What controls the subdivision iterations is the "complexity" parameter in UsdRender 
![usd_complexity](https://user-images.githubusercontent.com/13153907/156830422-7aed970b-04b9-4968-8127-c227e72df28c.png)
by default it's set to "very high" which sets the subdiv_iterations to 8 (Low is 0, Medium is 2, high is 4, very high is 8). This is different from the usual viewport display in Solaris, which sets it to set 0. We should perhaps find a different logic to control the subdiv iterations as this is way too much for Arnold.

**Comment by sebastienblor** [comment]
The Hydra documentation says that this attribute is indeed meant to be between 0 and 8. I think we should remap it to be 0, 1, 2, 3 instead of 0, 2, 4, 8.
```
 /// Returns the refinement level for the given prim in the range [0,8].
    ///
    /// The refinement level indicates how many iterations to apply when
    /// subdividing subdivision surfaces or other refinable primitives.
    HD_API
    virtual HdDisplayStyle GetDisplayStyle(SdfPath const& id);
```
