### ISSUE TITLE
Instance primvars are ignored in the procedural

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#944]
**Describe the bug**
When a point instancer prim has primvars, they are not propagated to arnold.
The rule is that a point instancer can have a list of values (matching the amount of instances), and the point instancer should distribute these values to each instance.

Also, regular usd instances should read their primvars. This will just work for constant/uniform primvars, as I don't think arnold supports varying/vertex user datas on ginstances

**Comment by pphansc** [comment]
Great to see this added! :) I built the latest master and tried on my test scene and it seems that the primvars on the point instancer are now working as expected. The primvars on the native instances don't seem to be populated correctly though. I attached my test scene including an ass file that should work when you cd into that directory first.

[usdarnold_instancing.zip](https://github.com/Autodesk/arnold-usd/files/7675883/usdarnold_instancing.zip)


On the left is some scattered cubes using pointInstancer which now does include the color coming from the primvars. Unfortunately it does have a double transform when translating the Xform above the instancer as you can see by the gap between the two cube assets that increased between the viewport and the render.  (Created a new issue #956) 

On the right there is scattered cubes using native instancing which are now all rendering black as that is the default color for the user_data_color node if the primvar wasn't found.

Viewport:
 ![viewport](https://user-images.githubusercontent.com/86960151/145206685-0cc1cd4b-87f5-47a6-ace7-a9185a00d141.png)
Render:
![render](https://user-images.githubusercontent.com/86960151/145206705-ebedd09c-7962-4147-b98a-416f047a0b3d.png)
