### ISSUE TITLE
Hiding an item in usdView does not rerender

### ISSUE THREAD

**Issue by digicpictures** [Autodesk/arnold-usd#95]
**Describe the bug**
When hiding something in usdView the Arnold render does not update the change. If I move the camera then the hidden object disappears, so the visibility states are probably set. Showing a hidden object updates properly though.

**To Reproduce**
1. Open anything in usdView
2. Set Arnold Hydra renderer
3. Hide an object
4. Move the camera

**Used Software Versions**
 - Arnold: 5.4.0.2
 - USD: 0.19.11
 - Compiler: MSVC 2019
 - OS: Win 10

**Comment by sirpalee** [comment]
I was able to reproduce the issue, thank you for reporting!
