### ISSUE TITLE
PointInstancer double transformations

### ISSUE THREAD

**Issue by pphansc** [Autodesk/arnold-usd#956]
**Describe the bug**
When translating a prim that contains an instancer with the prototypes as children, both the points and the prototypes are being translated resulting in double transformations.

**To Reproduce**
1. render the attached point_instance_offset.usd file with the usd procedural

**Expected behavior**
When translating an instancer I expect only the points to be moved (and the prototypes being scattered on those new translated points) the prototype offset from the point should be relative to the parent of the prototype rather than relative to world space.
For the attached scene the two instanced cubes (screen-left) should be touching the normal cube (screen right).

**Screenshots**
Current:
![instace_offset_actual](https://user-images.githubusercontent.com/86960151/145210221-ea47ad5e-a48e-4bc1-a6ba-be3bfe648aa3.png)

Expected:
![instace_offset_expected](https://user-images.githubusercontent.com/86960151/145210257-3decf5a0-d0e3-44fd-a16b-39c9e277c9dd.png)

**Used Software Versions**
 - Arnold: 7.0.0.1
 - USD: 0.21.08
 - Compiler: gcc 6.3.1
 - OS: CentOS 7

**Additional context**

[point_instance_offset.zip](https://github.com/Autodesk/arnold-usd/files/7676033/point_instance_offset.zip)

**Comment by kikou** [comment]
This might be solved when we switch to the procedural instancer, see #949
