### ISSUE TITLE
Support USD 21.11

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#957]
**Describe the bug**
USD 21.11 comes with incompatible changes, in particular regarding the UsdLux API.
We need to port it to the code, and still make it backwards compatible

**Comment by sirpalee** [comment]
Reopened the ticket as there is a build failure in our USD imaging plugin.

**Comment by sirpalee** [comment]
My mistake, it was a merge issue when merging fix-7.0.0 to master, and the changes are missing from the master.
