### ISSUE TITLE
Schemas fail to generate when using cmake with the python 3 build of USD

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#966]
**Describe the bug**
Arnold schemas fail to generate when targeting a python 3 build of USD using cmake. The same code path works ok with a python 2 build of USD.

**Comment by mwkm** [comment]
This might be related to this issue:
https://github.com/Autodesk/arnold-usd/issues/536#issuecomment-1047561908

I had a quick fix working, please see the above issue.
