### ISSUE TITLE
Environment shaders in the procedural

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#969]
**Describe the feature you'd like**
Support the environment shaders added to Hydra in #873 in the procedural.

**Comment by jhodgson** [comment]
Example file authored in Solaris that creates a background and atmosphere linked to the render settings node, and which renders correctly in the render delegate.

[backround_shader_demo.usda.txt](https://github.com/Autodesk/arnold-usd/files/7942947/backround_shader_demo.usda.txt)
