### ISSUE TITLE
Solaris RenderSettings node instant crash

### ISSUE THREAD

**Issue by Tuftux** [Autodesk/arnold-usd#97]
**Describe the bug**
Using Houdini 18.0.287 adding a RenderSettings node with Arnold as the Render Delegate will instant crash.

`00:00:13  3308MB WARNING |   render terminating early:  received abort signal
4880: Fatal error: Segmentation fault`

**To Reproduce**
1. Add a RenderSettings node in an empty Solaris Stage

**Used Software Versions**
 - Arnold: Latest Beta (build : refcfc150)
 - OS: Windows 10
 - Any 3rd-party app: Houdini 18.0.287

**Comment by sirpalee** [comment]
I was able to reproduce the issue and find what's going on. To fill the contents of the Render Settings node, we need to create a file named HdArnoldRendererPlugin_Global.ds and set up the parameters we want to control via the Render Settings LOP node. However, these scripts have been moved to HtoA from this repository, so we can't resolve this ticket here.

**Comment by sirpalee** [comment]
You can temporarily resolve the crash if you add a file named `HdArnoldRendererPlugin_Global.ds` to HtoA's `soho/parameters` sub-folder with the following contents:

```
#include "$HFS/houdini/soho/parameters/CommonMacros.ds"
{
    name    "arnold"
    label   "Arnold"
    parmtag { spare_opfilter  "!!SHOP/PROPERTIES!!" }
    parmtag { spare_classtags "render" }
}
```

I'm closing the issue as this was handed off to the HtoA team. For reference, the HtoA ticket number is 1353.

**Comment by Tuftux** [comment]
Awesome, thank you !
