### ISSUE TITLE
HdArnold Cannot Be Loaded When Build With MSVC 2019 Unless /Zc:inline Is Explicitly Disabled.

### ISSUE THREAD

**Issue by SimonCSmith** [Autodesk/arnold-usd#978]
Due to a bug in VS 2019, unless the compiler flag /Zc:inline is turned off, it will strip out the code generated by the `ARCH_CONSTRUCTOR `macro which is used to set up the factory constructor for the arnold plugin via the `TF_REGISTRY_FUNCTION(TfType) { HdRendererPluginRegistry::Define<HdArnoldRendererPlugin>(); }` declaration.

I believe this is the same issue as was raised in Issue 622 [here](https://github.com/Autodesk/arnold-usd/issues/622#issuecomment-775019861) which had a propsed fix, but it was closed without further comment (I think the reporter fixed the issue locally and it did not make its way back into the master branch). It has also been reported and fixed in the USD codebase itself [here](https://github.com/PixarAnimationStudios/USD/issues/1279).

To Reproduce:
If you have this compiler flag set and are compiling under Visual Studio 2019 (16.11.6) and using the v142 toolset, then when you try to load the Arnold Hydra Delegate using a `SetRendererPlugin` call on the `UsdImagingGLEngine` class it will crash due to the hdArnold plugin factory instance in the USD registry being NULL.

My Setup:
I used a pull from the master branch (17th Dec 2021)
USD 21.11 (monolithic build)
Visual Studio 2019 (16.11.16)
v142 Toolset
Windows 10
All dependencies for USD and arnold-usd compiled with the above setup

Notes:
When I turn that compiler flag off, I can see that when the DLL is loaded and `RunConstructors()` in attributes,cpp (USD codebase) is called, there are entries being returned in the `GetConstructorEntries()` call. Previously that call would return 0 entries.

**Comment by sirpalee** [comment]
I tried compiling using Visual Studio (Community) 2019 - 16.11.8 and the DLL loads fine. Looking at the `16.11.8` and `16.11.7` logs nothing obvious points to fixing this: [release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.11.8) , unless it was

```Corrected an issue in C++ compiler where a templated destructor involved in a class hierarchy with data member initializers may be instantiated too early, potentially leading to incorrect diagnostics about uses of undefined types or other errors.```

I also used shared libs, not a monolithic library, I'll give it another try using the monolithic USD build.
