### ISSUE TITLE
change `uv smoothing` mode is no effect. it is linear mode in solaris. but is normal in th usd procedural

### ISSUE THREAD

**Issue by hehuapoka** [Autodesk/arnold-usd#982]
**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Used Software Versions**
 - Arnold: [e.g. 5.4.0.2]
 - USD: [e.g. 0.19.11]
 - Compiler: [e.g. GCC 4.8.5]
 - OS: [e.g. MacOS 10.15]
 - Any 3rd-party app: [e.g. Katana-3.2]

**Additional context**

**Comment by hehuapoka** [comment]
![Screenshot 2021-12-23 170648](https://user-images.githubusercontent.com/44811934/147216465-088ea11e-e4b2-4fed-8ff9-065116e13955.png)

**Comment by sirpalee** [comment]
I believe this is solved by #632 which is not yet available in any of the public HtoA builds.
