### ISSUE TITLE
Arnold(Hydra) renders yellow or not at all

### ISSUE THREAD

**Issue by suekieza** [Autodesk/arnold-usd#99]
**Describe the bug**
A have two videos showing two problems.
Normal maya sphere renders yellow(regardless of shader)
Usd objects "are not there"
Rebuilt today 4 December

**To Reproduce**
Steps to reproduce the behaviour:
1. open Maya try rendering.

**Expected behaviour**
Render looks correct and can see usd objects 

**Screenshots**
[2019-12-05 11-16-49.flv.tar.gz](https://github.com/Autodesk/arnold-usd/files/3925990/2019-12-05.11-16-49.flv.tar.gz)
[2019-12-05 11-14-18.flv.tar.gz](https://github.com/Autodesk/arnold-usd/files/3925991/2019-12-05.11-14-18.flv.tar.gz)

**Used Software Versions**
 - Arnold: 5.4.0.2
 - USD: 0.19.11
 - Compiler: GCC 4.8.5
 - OS: Linux Centos 7
 - Any 3rd-party app: None

**Additional context**
Slow and crashes a lot.

**Comment by suesauer** [comment]
This issues seems to have gone away with new build

**Comment by sirpalee** [comment]
@suesauer thank you for getting back to us about this. Are you referring to the latest arnold-usd builds or the latest usd-maya builds? Or both?

**Comment by suesauer** [comment]
Both :D/
